### ISSUE TITLE
Request: Wallet Backup is not compatible with Bitcoin

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1004]
On the input from #757. Our backup command behaves different than bitcoin backup command. This causes problems for services and people running many bitcoin-derived coin wallets. Breaks scripts. The backup path cannot be specified, moreover the result of rpc does not include the path where backup was done.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
and whats with the oddball " gridcoinresearch.conf-2018-02-26T11-01-11 " and " wallet.dat-2018-02-26T11-01-11 " that suddenly appeared I think @ 3.5.8.0 when the wallet does auto backups? The format should be a standard date maybe but this oddball junk really makes it look crappy and almost as if its not the right type of file due to the file extension " gridcoinresearch.conf-2018-02-23T18-22-23 vs gridcoinresearch-02-23-2018.conf " so windows for example does not know what type of file it is or what to open it with ( yes you can right click , always open with and select notepad.exe ) but this current method since merging the community devs with robs work might be really confusing for new/newer users when trying to backup and or restore their client.

**Comment by denravonska** [comment]
You have a point, the date should maybe go before the suffix.

**Comment by tomasbrod** [comment]
The format looks like ISO 8601 standard, but it is not.

**Comment by denravonska** [comment]
It should be ISO 8601 with the exception that Windows cannot use colon in filenames. Or is there anything else wrong with the format?

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
seemed a little random , but after googeling ISO 8601 I understand the attempted results but since we have src to compile on anything ( I have sun/alpha/mips and other RISC machines now and I am going to work on porting to just like the halted ppc64 port me and denravonska did I will be doing AIX , Solaris and other Architectures and Platforms )  , Windows precompiled .msi/.exe and OSX .dmg (BSD) it should be settled on a format that is not platform dependent and only compilable with *nix/posix compliannt systems especially when we want more Windows clients than *nix due to the lack of the neural network on everything but Windows until you guys finally get the neural network non platform and architecture dependent. Looking at my year and a half of daily backups it changed when the Rob only tree and the community dev team trees were merged and there was no problem with the previous method that was in place , do we/you really need to know what week number it is in a wallet.dat or gridcoinresearch.conf when there is Month/Day/Year in the filename itself already? That also seems like it could cut back on even if , a few kb less code let alone possible memory freeing etc since its less that the binary has to do? Sorry I don't code , unless its mixing Google snippets and thats far limited when it comes to Windows. We need a workable standard for everything we currently have developed and working src/pre-compiled gridcoinresearchd , as I said that could really confuse new users , heck it confused me and I am not new. Or change the code to remove the .conf from the middle of the filename and make it append it to the the middle so it shows the file ending as a .conf file along with the .dat this really could screw up somebody trying to backup their wallet or restoring from a backup and is a newb or not tech savvy and check github and search threw issues etc and they reinstall their system after backing up wallet files and copy them like the instructions say ( or update the instructions on the guides/wiki on how to restore the wallet from a backup explaining " ISO 8601 and really there was no need to change it ) that you need to in essence change the file extension manually due to imo a change that was not necessary to make that only complicate things. Not everybody into block-chain/cryptocurrency or part of our community is tech savvy. Maybe per denravonska's issue #1016 not only an option to disable backups but options for the backup file format the end user wants used and can make a choice to select ISO 8601 or plane text original month number , day number and year like the old pre 8.5.3.0-unk change that was done without any warning or notification nor instructions for new users? Either way , it needs to be added into the documentation and wiki instruction pages and guides from www.gridcoin.us along with www.gridcoin.science and the plethora of instructional pages " how to backup and how to recover/restore your Gridcoin wallet from backup files " .

**Comment by denravonska** [comment]
@grcjamezz You might want to hold the porting effort. When we do a rebase we will get that for free, though it will take a while.

**Comment by jamescowens** [comment]
In Bitcoin's current master branch as of this writing, it is unclear what code actually backs up the configuration file. the walletbackup only backs up the wallet.dat file to the specified filename/directory. For now, I am leaving the gridcoin walletbackup alone, as we don't get any complaints about it. I am adding backup file management per https://github.com/gridcoin-community/Gridcoin-Research/pull/1735

**Comment by jamescowens** [comment]
I am closing this. I think most people are happy with the backup functionality the way it is now, and also we have implemented backup file management, which is more than what Bitcoin Core does.
