### ISSUE TITLE
Change color of "Out of Sync" transactions in wallet

### ISSUE THREAD

**Issue by jeffreyhorne** [gridcoin-community/Gridcoin-Research#1011]
On MacOS High Sierra (only OS that I've tested on), the "Out of Sync" text for recent transactions is light blue. The contrast of light blue on the current background of the wallet makes it difficult to notice and read the text.

Suggest making that text red, like the text for when the wallet is out of sync. Assuming that the text color might be different from the wallet "out of sync" text currently for a reason, if it needs to be a different color than the text for the wallet being out of sync, I suggest a shade of orange or brown for the transactions "out of sync" text.

![gridcoin-mac_1](https://user-images.githubusercontent.com/35817504/37175051-f1b6eb4a-22dd-11e8-8b81-d0f121f43a44.png)

**Comment by iFoggz** [comment]
I'm wondering if the color in development branch is different to support the new upcoming color scheme and design. i'll look into this

**Comment by ghost** [comment]
Does not look like its Fixed in Dev Branch. With the "Dark" Theme it is OK . But i think it is the best if we do it the same Red as the (out of sync) on the "Wallet"  text

Have not much Time now to check it now, will look later more into it.
master Branch: 
Gridcoin-Research/src/qt/forms/overviewpage.ui:95: ##Take this as Reference #d31360
Gridcoin-Research/src/qt/forms/overviewpage.ui:561: ##Change the Color: #dfffff part. (Not tested) 

Dev Branch:
Devel/src/qt/forms/overviewpage.ui:84: ##Reference
Devel/src/qt/forms/overviewpage.ui:505:   ##Change the color: #dfffff part (Not Tested)

**Comment by denravonska** [comment]
Fixed with #1017.
