### ISSUE TITLE
Noob HELP!! with wallet and exchanges.

### ISSUE THREAD

**Issue by HopSling** [gridcoin-community/Gridcoin-Research#1026]
I have been with Gridcoin for about 3 months now coming over from Seti since 2002.
All is working fine in that regard with about 100 GRC in client so far.
I have now decided to purchase (monthly) a very significant amount of GRC not so much as to mine/crunch/trade but to store away into offline hardware wallet.
The problem I have found, after a whole day of trying/searching, is purchasing GRC ...in an easy world It would be nice to just click a link inside the Gridcoin Wallet that I could go right to and make a purchase but that aint happening for sure :)... All I want to do is make very significant monthly purchases of GRC and hold on to it. Way easier said then done !!!
I opened a separate bank account just for this purpose then went to coinbase....all was fine until I tried to link my bank to coinbase and after waiting and waiting to see the small deposit verifiers show up...and nothing happened so I got in touch with coinbase and they said sorry but you have to try a debit card or another account....then tried a debit card and it said we ran into a problem try back later....so in disgust I deleted the coinbase account.. To make a very long days journey short....I tried Bittrexx and they are not accepting new accounts...I tried poloniex and said verification could take weeks...I tried every US exchange and pretty much the same song and dance......
I apologize if this post is in wrong area...Tomas...but I felt I could get the best aide with this matter from the Gridcoin Scholars ....So my question is:
I want to monthly purchase very significant amounts of GRC ($10k or more annually to be exact) and how in the heck can a person get this done here in the US or am I just SOL or is there some kind of Wallet/exchange combo I need to do...I do not want to trade/crunch etc I just want to deal with a BTC/GRC purchase only...and btw most of it will be donated back into projects for sure (maybe a Dev tip-jar).
Thank You Devs for all your hard work and putting up with us newbies.

**Comment by tomasbrod** [comment]
I see you mention me, but I do not know how the background on exchanges works. I was lucky enough to open accounts before the restrictions came into effect. Even if you could get bittrex account, their gridcoin wallet is "offline". The issues that were, were fixed almost a month ago now. Poloniex the same, because they are lazy. BTC fell in price, and with it fell the profits of exchanges.
There is one exchange that lists Gridcoin on it's front page, Holy transactions, but I no not have account there.
Last, but not least, have a look at [decentralized exchanges](https://gridcoin.us/exchange.htm), but verify you can withdraw before making big deposit.

**Comment by RoboticMind** [comment]
Can we close this?
