### ISSUE TITLE
Display total wallet balance in transactions screen

### ISSUE THREAD

**Issue by mpenguin** [gridcoin-community/Gridcoin-Research#1036]
Currently in the "Transactions" tab, the Date, Type, Address, and Amount are displayed. I would like to see the option (or just make it standard) to include a Balance column on the far right, so that one can see the running balance and any given balance after a transaction.

Thanks.

**Comment by nathanielcwm** [comment]
i think that it should be standard (ofc with an option to disable it maybe in the gridcoinresearch.conf file) just my opinion

**Comment by jamescowens** [comment]
We are just not going to do this right now. Maybe we can look at it as part of the GUI rewrite #847, but it may be too complicated and sap performance. This is especially true of the existing gui, because each transaction received that is displayable will invalidate ALL rows in the UI transaction display model, which is really ugly.

**Comment by jamescowens** [comment]
We are not doing this for a variety of reasons, starting with performance problems for wallets with large numbers of transactions.
