### ISSUE TITLE
3.7.11.0+ listtransactions rpc call fails to list sent transactions

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#1055]
Apparently sent transactions are not listed in the listtransactions rpc call, although they are properly listed in the GUI transactions grid. This is confirmed behavior for 3.7.11.0. It does not have anything to do with change accounts, because I did a test with an entire UTXO as input so there would be no change. It appears that only "received" and "generate" transaction categories are being shown, not "sent". This behavior has not been confirmed for staging/dev.

**Comment by barton2526** [comment]
Note that this is a regression from previous behavior.  This issue was not present before 3.7.0.0 (v9).

**Comment by iFoggz** [comment]
interesting will look at previous commits and this area of the code. thank u

**Comment by jamescowens** [comment]
Paul,

There was a good discussion about this on rocketchat/slack #development. Francesco at Flyp.me reported this behavior, and apparently it is the reason they have taken Gridcoin back off line.

**Comment by iFoggz** [comment]
i think i see the issue let me compile 3.7.11.0 for further testing on a fix.

**Comment by jamescowens** [comment]
Confirmed to be occurring in dev branch as well.

**Comment by jamescowens** [comment]
I tried to look at this a bit tonight. I am heading where @Foggyx420 was going... it looks like a filter issue. The GUI doesn't seem to use ListTransactions or ListTransactions2, but instead builds the transaction table directly in the model from (transactiontablemodel.cpp:100) std::map<uint256, CWalletTx>::iterator mi = wallet->mapWallet.find(hash); and then (line 113) bool showTransaction = (inWallet && TransactionRecord::showTransaction(mi->second)). The send transactions are displayed properly on the GUI grid. That may be a clue...

**Comment by iFoggz** [comment]
It been this way for years so im wondering how flype me says its now. U
need to set watch only true with bool to show send

**Comment by jamescowens** [comment]
It is the age old case of nitpicking when something else goes wrong. People start looking under the hood and noticing things that they never noticed before...

**Comment by iFoggz** [comment]
Ok from what I see is gridcoin has a second function of `listtransaction2` to support gridcoins different blocks. I cannot get send transactions to show unless iswatchonly bool is set to true in argument however we cant in master as the conversion does not exist yet which I can apply in a hot fix. when set to true it shows the send transactions. when its default of false it shows receive and generated. the gui processes the data differently and does not use these functions. Bitcoins listransaction code is pretty much identical to gridcoins.


Ill add bool conversion and they can simply do a `listtransactions * # # true` to show the send transactions as well. # being the int arguments needed. i am wondering if they just never used the bool because the string to bool conversion error.

**Comment by jamescowens** [comment]
I think that is more than enough to fix a problem that has existed essentially forever. I really don't know why they made an issue out of this anyway, except my earlier comment.

**Comment by holycto** [comment]
I'll note this is giving us two problems, one is sent tx don't appear in listtransactions, the other is change output does appear as received in listtransactions. 

This deviates from how bitcoin compatible coins do it and yes it's been giving us problems. We are now being more strict on quality control, and also I believe grc has been disabled for long times due to network problems, so maybe that's why we haven't really payed attention to the issue. Anyways this only affects us in that we can't detect confirmations in outgoing tx so probably support has been confirming them manually so developers haven't noticed also. The change outputs being detected as received also gives us problems and makes it more difficult to support grc, but we have worked around it for some time already.

In case it helps we're doing the rpc call for all bitcoin compatible coins as: listtransaction("*", n) and it works as expected except for gridcoin.

**Comment by holycto** [comment]
I added some example rpc output for btc and grc at https://github.com/gridcoin/Gridcoin-Research/pull/1059#issuecomment-383520892

this shows the incorrect listtransaction behaviour in gridcoin, imo the bool conversion is not a proper fix for this issue but more like a fix for a workaround that can be done

**Comment by denravonska** [comment]
Blackcoin doesn't use the filter at all while we default to spendable. This seems to have been added by us at some point and we should most likely revert that and remove ListTransactions2.

**Comment by tomasbrod** [comment]
@holycto It is not a problem to change the RPC output according to your service needs. We just did not know that anything was wrong. Is certainly helps that you included the used commands, ~but it would also help when you specify~ what output you are expecting. I can even create commands that is specific to needs of a service.
It seems to me that `gettransaction` command is the one to be used to check status of transaction.

**Comment by holycto** [comment]
Yes, sorry, we should have reported this a long time ago but we didn't really know what was going on until we have debugged it recently.

I think listtransactions should return information in a compatible way to other bitcoin rpc implementing daemons, and there could be a different rpc call for when a different behaviour is needed. Ourselves are using it in the same way for all cryptocurrencies, and I believe other users of the rpc api would also expect the same compatibility.

**Comment by jamescowens** [comment]
Why don’t we just remove the filter as the default behavior and make the filter argument optional and a pass-through... Seems the easiest solution. The filter constants in scrypt.h are two bits if I read it correctly.

**Comment by denravonska** [comment]
We should make our code and API as close to Bitcoin's as possible which means removing the modifications made to `listtransactions` (and `GetAmounts2`). However we also need to make the smallest change possible for hotfix as staging has not been fully tested yet. What is the smallest change we can make which satisfies HolyTransaction's requirements?

**Comment by jamescowens** [comment]
I don't think we can revert to the standard listtransactions and getamounts because of the coinstake transaction. Now that I am done with the stress test of staging/dev RPC, I am going to switch to the hotfix branch and put in some debugs to try and troubleshoot this some more...

**Comment by denravonska** [comment]
@Foggyx420 This is fixed now, no?
