### ISSUE TITLE
Individual reported an abnormal payment

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#108]
http://explorer.gridcoin.asia/tx/f6682b8ce0bd901c748f3a8ea88f44e56ff610178a890b029f2e55f75415e96d
http://explorer.gridcoin.asia/api/getrawtransaction?txid=f6682b8ce0bd901c748f3a8ea88f44e56ff610178a890b029f2e55f75415e96d&decrypt=1

http://www.gridcoin.co/?cpid=42cd7cb96d8cae69169906fa4a52157a
http://www.gridresearchcorp.com/gridcoin/?cpid_dashboard&CPID=42cd7cb96d8cae69169906fa4a52157a

Individual reported his mag jumping from 30 to 360, then received a 7500 GRC DPOR payment which is higher than his expected payouts.

**Comment by AEM7** [comment]
Actual guy that this happened to.

http://puu.sh/qHzXv/c3a552750f.jpg

Returned after 5 months without staking. I had a machine running and had a 20 mag. I started staking a few days ago and doing a few projects. Resent a beacon a day or two ago too. Just a few minutes ago, mag jumped to 360 and I got the three payments seen in pic. Actual mag should be 60.

Thanks.

**Comment by AEM7** [comment]
Here is the debug.log: https://drive.google.com/open?id=0B23ck3hMqiHaWHFjSklNN09qVUU

Db.log was empty...

Thanks.

**Comment by gridcoin** [comment]
Thanks, well there are a lot of components to this, and fortunately I can see most of what happened and we can try to reconcile this.
The calculation payment amount itself is correct but based on the wrong magnitude.
We can see his last POR block was 169 days ago, and with a prior mag of 20 and a bad reported mag of 360, our system believes he has an average mag within that span of 222, and the GrcMagUnit was .20 at the time.
Thats 169 x 222 x .20 = 7503.60 grc.  That was taken from the daily kitty, so therefore it was paid in full.
The real issue is, how did we assess his mag at 360?  I assume somehow the neural network pegged him at 360, and he was already in the superblock at 360 before he fired up the machine to stake and thats where the figure came from (prior neural network consensus of 360 in the superblock).  Putting his avg mag at 222 for the block span.

So, Ill have to take a look at the superblock next for anomalys.  There is a high liklihood that if his was off, some other project was calculated too low.  Usually what happens is, if a segment of our researchers download lets say 90% of the project files, and the same network sites are down for the whole group, that would raise the mag up extrordinarily for the projects In the superblock, and down to 0 for the missing projects.  Most likely we had a consensus at the same time, resulting in a bad superblock that day.

Ill look into the superblock.

Thanks for reporting this.    

Rob

**Comment by gridcoin** [comment]
Looking at the superblock it looks like the problem is it only contains mags for projects:
asteroids@home: 13000 - 2944285.71
atlas@home 1560 - 134000
burp 2960 - 203333.33

giving people huge GRC for those 3 projects... today only (hopefully).

Ill check the neural network to see if its going to stake a good block tomorrow.

**Comment by AEM7** [comment]
Odd, since I haven't crunched for Atlas or Asteroids in months, and not even that much to give me a decent mag then.

**Comment by gridcoin** [comment]
Yeah, I see what you mean - Im looking into this superblock deeper.    You dont even have mag on asteroids atlas and burp:
http://cpid.gridcoin.us:5000/get_user.php?cpid=42cd7cb96d8cae69169906fa4a52157a

But, continuing where we left off yesterday, those 3 projects that I posted were the only projects with network averages in the superblock, so I guess what I failed to test next is the problem of missing averages.  IE if we only gathered network averages for 3 projects, would that not drive up the mag for projects other than these 3 (needs to be tested).

**Comment by AEM7** [comment]
I am actually crunching on BURP right now but the mag should be around 35. I'm also crunching on Mindmodeling, GPUGrid, Distributed Data Mining, SZTAKI (no WU yet), and WUProp.

Additionally, my Actual PPD shows to be 539, and my fulfilment % is 748.61 as of right now.

**Comment by gridcoin** [comment]
Ok yes, I see BURP on the link I posted 2 messages ago now - thought it was in alphabetical order at first.  Yeah I see avg RAC of 1956 on it.  Anyway to summarize, we somehow had a bad superblock, and with 93% of the projects missing in it, you were assessed with a higher mag on Burp due to the lack of competition.
(Your mag is 60 right now on my external node) if nothing else changes today.  We have half a day left before the new block starts to stake.

Most of the time this problem would have been much less severe if the span wasnt so long between blocks and it happened, but it was.

**Comment by AEM7** [comment]
Updating to say that I just got PoR of ~71 GRC. Mag got cut in half and it seems like NN was counted my projects twice. With a 30 mag, I should get about 6 GRC, so I don't know if the problem is still persisting.

Also, NN still shows my mag as 360 and it got put on the site too: http://www.gridresearchcorp.com/gridcoin/?cpid_dashboard&CPID=42cd7cb96d8cae69169906fa4a52157a

Thanks.

**Comment by gridcoin** [comment]
Hi AEM, thanks man.  Well if you want I can show you some of the fields in 'showblock blocknumber' that explain the reward (its an average of your last stake, current stake and duration between).  The 360 being posted on researchcorp is correct - its your last staked block when the magnitude was elevated.  His site has not counted your new stake yet.
What block number did you stake for 71 grc?  You can double click on it to see.

Im planning on chalking this issue up as a bad superblock, a one time occurrence where your payment was elevated due to lack of competition in that particular days emissions.  We can do that after we prove your client stabilizes and the last block shows correctly on RTMs dashboard.

**Comment by AEM7** [comment]
Block number is 641527.

Mag has dropped to 75 but actual PPD is still 544, which I'll assume won't affect me.

Thanks.

**Comment by gridcoin** [comment]
Looking at your last 5 POR stakes, it looks like they all occurred within 24 hours of block 640444 and all of them had the 360 magnitude (since they were based on 640444s super block).  

Im waiting to see your next POR block, one based on 641973 (the last superblock).  Please post your next POR block # and Ill take a look at it and see if your average mag drops.  Yeah, the PPD will just go down over time, it is used for certain BL, but since you have been researching for such a long period it wont cause any alarms in the payment check function.

**Comment by grctest** [comment]
Has the superblock recovered? Whilst this was occurring, my neural network window had all the stats compared to only 3 in the staked superblock.

**Comment by gridcoin** [comment]
It looks like he got two stakes @75 mag, so I think we are going to be OK:
http://www.gridresearchcorp.com/gridcoin/?cpid_dashboard&CPID=42cd7cb96d8cae69169906fa4a52157a

AEM, does your list rsa look pretty good now , and how do the last 2 PORs look to you?

**Comment by AEM7** [comment]
I haven't gotten any PoR's since I last posted about getting one with 71 GRC. I don't know if you are referring to that one and the one before that that I got for 2.1 GRC, or another two that I cannot see in my client.

Here is my list rsa: `
￼
[
{
"RSA Report" : "1471994965"
},
{
"CPID" : "42cd7cb96d8cae69169906fa4a52157a",
"PoolMining" : false,
"RSA Weight" : 0.00000000,
"RSA block count" : 7.00000000,
"Last Payment Time" : "08-21-2016 02:54:08",
"Earliest Payment Time" : "12-04-2015 06:35:12",
"Magnitude" : 75.00000000,
"Research Payments (14 days)" : 7613.92000000,
"Interest Payments (14 days)" : 11.05000000,
"Interest %" : 0.02170149,
"Daily Paid" : 543.85142857,
"Expected Earnings (14 days)" : 210.00000000,
"Expected Earnings (Daily)" : 15.00000000,
"Fulfillment %" : 3623.26068335,
"CPID Lifetime Interest Paid" : 16.70000000,
"CPID Lifetime Research Paid" : 11329.57000000,
"CPID Lifetime Avg Magnitude" : 208.90547927,
"CPID Lifetime Payments Per Day" : 42.96152793,
"Last Blockhash Paid" : "a04214c5e68e4772f05c8600ab0c922ff6aa45556ac3daeadb71e3862a7fbdaa",
"Last Block Paid" : 641527.00000000,
"Tx Count" : 75.00000000
},
{
"Magnitude Unit (GRC payment per Magnitude per day)" : 0.20000000
}
]
`

**Comment by gridcoin** [comment]
Oh sorry, you are correct, looking a little closer: Your last por stake was 641527 still, which was _before_ our last 2 "normal" superblocks that contain your normal mag of 76 (the superblock After 641527 was 641973.  So I guess we still need to wait a while for you to stake a POR then we can look at it :)

**Comment by AEM7** [comment]
No PoR in 5 days, and I've been staking for 4 days since 16 hours a day. Maybe that lump of GRC made the system think I got my PoR for the next few years?

**Comment by grctest** [comment]
https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1174#entry222631

Individuals in cryptocointalk have reported the same neural network issue occuring again?

**Comment by gridcoin** [comment]
Hi Aem,
Yes looking at the block validator code, yes, the issue is a stake wont be approved til your daily paid drops to 75.  As of a few days ago you had Daily Paid : 543.85142857, and expected PPD of 15.  Once you drop below 75, it should stake again.  I realize that might take 60 days to water down, but we can leave this issue open until you stake.

GrcTest, when you say "same issue" do you mean we staked a bad superblock today and people have high mags?

**Comment by grctest** [comment]
@gridcoin I mean users are reporting in the announcement thread that we staked a bad superblock again, one user says he only sees the one project (yoyo@home) in the latest superblock. I have been unable to verify my neural network because attempting to open the neural network window froze my client. 

I've ran 'execute syncdpor2' to get an accurate neural network. 

Shall we create a separate github issue for superblock inaccuracies rather than posting in this issue?

**Comment by gridcoin** [comment]
Yes please open another issue on github.

**Comment by AEM7** [comment]
Here is my latest PoR id: c1383f9cbbd20cd3acb2074d10c5fe33b0cc0ec230b7b597ecbcc9aead6c1de6-000

I got ~410 GRC.

Thanks.

**Comment by AEM7** [comment]
Another 2 PoR's: 1bae00ed0d1a29847f8e31b7d7a7b40bf29da632369563bab9130d0096722bc5-000

10cc149291d5a038368434f58e040103031b96885fde35c5036227f8585f03f8-000

Seems like I'm getting PoR's again.

**Comment by Quezacoatl1** [comment]
I also got an abnormal payment which I can not explain:
16fc14628af9d7fa828ff38fb02fc44fb6fe7992931ba211a121d457a2d2655b-000

This is the CPID
http://www.gridresearchcorp.com/gridcoin/?cpid_dashboard&CPID=1a7c8f7bbe5a14b0c1e205af3bd2d3d5
