### ISSUE TITLE
Automake doesnt detect QT5 unless all libqt5 Packages are installed

### ISSUE THREAD

**Issue by Lenni** [gridcoin-community/Gridcoin-Research#1082]
On Debian 7 automake wont compile the QT GUI Unless all libqt5 packages are installed. The ones mentioned in the build document are not enough.

**Comment by jamescowens** [comment]
Is this still true? @caraka?

**Comment by caraka** [comment]
We're talking Wheezy here, and I confess I have never built for Wheezy and they don't even list the packages for it any more. I was unaware of the note in the build instructions: "If ./configure fails to detect your QT installation, you have to run:	sudo apt-get install libqt5* to install all QT5 packages available for your Linux Distribution."  I have never had to do that, in fact I don't even have every package shown in the instructions in my build depends. This may be/have been a Wheezy specific issue? If so, because Wheezy is well past EOL and this is not an issue on => oldstable (Jessie), I'm not sure it is even worth trying to figure out - I suggest this issue be closed @jamescowens

**Comment by jamescowens** [comment]
I concur.
