### ISSUE TITLE
FrancisNH -  WCG mining work is missing.

### ISSUE THREAD

**Issue by FrancisNH** [gridcoin-community/Gridcoin-Research#1120]
Something has gone wrong because since 2018-05-25 Gridcoin Research mining payout to FrancisNH has dropped 60% while my mining levels remain at 100%.  Confirming the mistake, Gridcoin Stats which I think interprets the blockchain, first showed zero (0) out of five (5) projects alive, followed a day later by only the WCG project missing.  

In fact all FrancisNH host computers are actively crunching and reporting to all their their projects normally - WCG, Milkyway, GPUGRID, and Einstein.  All CPU’s crunch only for WCG while  GPU’s crunch either for Milkyway, GPUGRID, or Einstein.

I am now printing the daily production reports from the  WCG project if useful.  WCG reports show all FrancisNH computers are running at full  production while Gridcoin Research 60% payout reduction matches the missing WCG also shown at  GRIDCOINstats and Gridcoin Stats.  I sent two private emails to Willy at GRIDCOINstats, but no reply.

In summary, the 60% drop in GCR mining payout tends to confirm Gridcoin Research is missing the same WCG mining work wrongly reported as zero (0) at the other two sites.  However, the WCG project shows FrancisNH production is normal at 100%.  WCG is my dominant contribution.

I've been crunching three (3) years before becoming a solo member at Gridcoin Research, therefore the small losses are not a big deal.  Several years ago, before starting Gridcoin Research, I had to change my email address which seemed to block me from some of the statistics sites I had enjoyed watching (even though I corrected the email address everywhere).  I've never found out how to fix that, and wonder if the same old problem could be related to this new problem that cropped up a week ago?

I am mildly addicted to watching the reports, therefore do appreciate help in getting them straightened out.  With Appreciation,  FrancisNH

[FrancisNH-WCG-Production-2018-05-27.pdf](https://github.com/gridcoin-community/Gridcoin-Research/files/2045814/FrancisNH-WCG-Production-2018-05-27.pdf)

[FrancisNH-BAM-ProjectList-TodayErrorsReportingZero(0)-2018-05-27.pdf](https://github.com/gridcoin-community/Gridcoin-Research/files/2045818/FrancisNH-BAM-ProjectList-TodayErrorsReportingZero.0.-2018-05-27.pdf)

**Comment by jamescowens** [comment]
WCG has changed their policy about exporting project statistics due to GDPR. They now require signing an agreement (which is not available yet BTW) to get a special token for access. Until IBM completes the agreement and we agree to its terms, WCG is off the white list. Neuralminer is in contact with them to try and get this resolved but there is no ETA.

The brain damage of this is beyond comprehension, but IBM is taking a very cautious interpretation of GDPR rules. Unfortunately it means no GRC research rewards for WCG until the issue is resolved.

https://steemit.com/gridcoin/@neuralminer/wcg-not-rewarding-grc-at-this-time

**Comment by FrancisNH** [comment]
Many Thanks for the explanation, James.
