### ISSUE TITLE
windows client never credits nothing... 

### ISSUE THREAD

**Issue by necrose99** [gridcoin-community/Gridcoin-Research#1130]
cpuid added to config with email..  bonic bam cpuid... added appropriately 
download blocks , forced blockchain sync for weeks on windows 10...
![gc](https://user-images.githubusercontent.com/2396239/40795356-7147ffea-64c7-11e8-9cc6-791a3c5ecb31.PNG)
resynced blocks , resynced blockchain... 

```
#datadir=
boincappdir=C:\Program Files\BOINC 
#boincdatadir=/var/lib/boinc-client/
boincdatadir=C:\ProgramData\BOINC
#boincdatadir=/Library/Application Support/BOINC Data
CPID=5aee................  anony'd 
email=mike@........
#PrimaryCPID=5aee................  anony'd 
PrimaryCPID=5aee................  anony'd 
## Use as many addnode= settings as you like to connect to specific peers
addnode=grcnode.tahvok.com
addnode=grcexplorer.neuralminer.io
addnode=grcnode01.neuralminer.io
addnode=grcnode02.neuralminer.io
addnode=grcnode03.neuralminer.io
addnode=grcnode04.neuralminer.io
addnode=grcnode05.neuralminer.io
addnode=gridcoin.bunnyfeet.fi
addnode=gridcoin.certic.info
addnode=gridcoin.crypto.fans
addnode=gridcoin.hopto.org
addnode=ils.gridcoin.co.il
addnode=la.grcnode.co.uk
addnode=london.grcnode.co.uk
addnode=miami.grcnode.co.uk
addnode=node.gridcoin.network
addnode=node.gridcoin.us
addnode=node.gridcoinapp.xyz
addnode=node1.chick3nman.com
addnode=nuad.de
addnode=quebec.gridcoin.co.il
addnode=seeds.gridcoin.ifoggz-network.xyz
addnode=singapore.grcnode.co.uk
addnode=toronto01.gridcoin.ifoggz-network.xyz
addnode=vancouver01.gridcoin.ifoggz-network.xyz
addnode=node.gridcoin.us 
addnode=www.grcpool.com 
addnode=seeds.gridcoin.ifoggz-network.xyz 
## Alternatively use as many connect= settings as you like to connect ONLY to specific peers
#connect=
#listen=1
#maxconnections=
#maxoutboundconnections=
NEURAL_07252017=CLEARING
UpdatingLeaderboard=false
enablespeech=true
suppressupgrade=false
#daemon=1
#rpcuser=<username>
#rpcpassword=<password>
#server=1

```

**Comment by Pythonix** [comment]
What do you mean by never credits nothing? You don't earn GRC for the BOINC work you've done?

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
For future reference you can use the latest Gridcoin block-chain snapshot located @ http://download.gridcoin.us/download/downloadstake/signed/snapshot.zip so you do not have to sync from 0 , as I type this we are at block @ 1262760.
Additionally , are you crunching via one of the pools or solo?
You can always give out your CPID its safe and it actually would had been helpful so we could assist you as I was going to check gridcoinstats.eu to see if you had sent a beacon and are in the neural network because if it was not automatically sent you would need to goto " help " and then click "debug window" and type " execute advertisebeacon " ( new recent command interface changes so if it says execute is depreciated as I just ran into with " execute encrypt password " it told me just to do the command and no need to pass execute to the client commands and you did not say what version you have installed mines 3.7.12.0 so basing help off assumption you are running the same ) if the beacon was not automatically sent and it does cost like .001grc or something to send it still you will need to acquire some Gridcoin from someone ( below , I provided a link to thefreenode and gave you a link and there is a rain/tip bot so you do not have to beg for such a small amount to send the beacon if that is the issue. 
I tried looking up necrose99 and necrose , to see if either were in the neural network trying to guess your user name and do not see either so I could only go by the information provided and there is a little bit more that we need in order to help you that is lacking in your post. 
I hope this reply at least helps you if you need to sync the blockchain ever again . I am unsure the date of the snapshot and how recent it is since we cannot browse the directory any more but it would take way less time. 
Can you please provide your CPID so we can see if you are in the network , CPID's are public and nobody can hack you by knowing your CPID (mine is 1ac793c529cd6ffa942afaef7c5068c2 ) or user name ( mine is jamezz ) but we can use that info to help you. 
Your email and your Private Key and as goes without saying , your password if in plain text vs encrypted if stored in the .conf is private but the rest is kosher to share and necessary for us on our end with tools like gridcoin.network and gridcoinstats.eu to help vs us sitting at your machine :) although there is team viewer/vnc and other remote services I am more than happy to assist you remotely and have done so with new clients before , such as on a mac before we had a .dmg and had to install by compiling by source. But it's not something I assume or expect people in the Crypto Coin world to want to do , nor is it safe.
You can also find real time help @ irc.freenode.org #gridcoin and #gridcoin-help along with our discord server @ https://discord.me/page/gridcoin
In my config its PrimaryCPID= but the .conf could be dynamically changing since I installed 2 1/2 years ago... 

Please refer to http://wiki.gridcoin.us/Gridcoinresearch_config_file it states you need double \\ at the end of boincappdir=C:\Program Files\BOINC  and boincdatadir=C:\ProgramData\BOINC so your config would be " boincappdir=C:\Program Files\BOINC\\ "if that is where the application is along with " boincdatadir=C:\ProgramData\BOINC\\ " and if its all caps vs Boinc may matter? Github wont show the 2nd \\ but its here in my post.

Additionally this is not a problem that belongs in issues as its only you and not related to the code or new release bugs etc and I recommend even if you use http://kiwiirc.com/client/irc.freenode.org:6667/#gridcoin if you do not have an irc client installed or download mIRC but its just a trial and not free or Adiirc based off mIRC but is opensource. I just believe since you are annoyed and frustrated awaiting an answer or help from here that is supposed to be for bugs and its not a bug its just IMO a step that was missed such as the beacon. You can get help faster who knows if anyone will comment further I will check this when I wake up and see if you provided the needed info in order to help you , or if someone else has helped you and or its been resolved. I would expect it to be closed and directed to a live help channel as I provided a web client interface you can just click after setting a nickname and join #gridcoin , if you are not familiar with IRC I just made it easier. If you join freenode for help do /join #gridcoin-help to get to the help specific channel as #gridcoin may be just people mucking around chatting it up and #gridcoin-help is easier to focus on for help. 
Hope this helps you to get help and get your client up and running , do not forget you must join team Gridcoin under any and all projects in order to get paid for processing work. @

**Comment by necrose99** [comment]
BOINCstats BAM! ID | 103148 |  
-- | -- | --
CPID | 5aeeb0ab5bc858c726b5664e9e04d3ee

I've tried everything , so far only the **faucet pays**...  and i've tried for months figured patience .... 

I did have pool mine setup, however client still fails to set poper CPUID , teams have moved to Gridcoin from US ARMY or other longstanding teams...    
If gridcoin payed for old work .......   https://boincstats.com/en/stats/-1/user/detail/2244568/bestxdays 
the GC fairy would rain out years worth...  however just getting it to even pay out fractions or even register properly...... 

API key might be an option to login to BAM poll cpuid , and set id in clients also adds simplicity if I get a few Pine64's in Linux mini cluster , when not bagging out packages... for arm64 ... 
also Conf file would likely be less snafu'd...

**Comment by necrose99** [comment]
client auto update broke , forced update from new MSI , droped beta bonic for cur... stable... 

old client ver was giving me lip , new working better....
