### ISSUE TITLE
unavailable hosts in src/net.cpp as DNS seeds

### ISSUE THREAD

**Issue by wilkart** [gridcoin-community/Gridcoin-Research#1172]
DNS seeds are not all working.

node.gridcoin.us - DOWN
london.grcnode.co.uk - OK
gridcoin.crypto.fans - OK
www.grcpool.com - DOWN 
nuad.de - OK
seeds.gridcoin.ifoggz-network.xyz - OK

I base on this monitoring page
https://status.gridcoin.pl/?page=2

On master branch we have only two not working nodes and when I build it, without adding any addnodes I finish with 
`tcp        0      1 by.gridcoin.pl:42002    47.188.231.176:32749    SYN_SENT`
and
`05/29/18 22:56:29 connect() failed: 101`

I intend also to remove them from
https://wiki.gridcoin.us/List_of_Addnodes

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
I would refrain from doing so , as I used to audit the wiki node list regularly first checking for valid DNS and then ping replies and if needed dig further. I would not recommend doing that as the issue could be on your side not the node. But I see you did not wait , you should have said " I just removed them from the addnode list " vs saying you " intend " to.
 
Recently @barton2526 updated /src/net.cpp if I remember off the top of my head lines 113-117 and now i think i few extra lines with 1 other seed node after my pointing out some issues with the old seed nodes list.

Not everything responds to ping and many of us block icmp replies thanks to ddos , you would have to use nmap or tcping for example and efficiently check if port 32749 is open and listening on the node side and #2 you have no idea why that node may be down and if its temporary due to updates both hardware or operating system etc and have no idea the reason or time.
Personally I do not trust results on free cloud software such as what is used by gridcoin.pl or other sites like statuscake etc but its better than nothing as a reference to help new users and it would be awesome if we could all agree to use something like xymon and someone host a server for the webpage and each node used the client side software or netdata as many of us have running and used to run so you could just pull up the dns entry for the node directly or with /netdata and see that the node was up and what block it was currently at.
Or for someone to write up something either in the gridcoinresearchd daemon and we used a central website that communicates with clients using the " listen-1 " flag and reports back to a site showing up/down and a list of nodes using a certificate system that would add the node as an entry.

node.gridcoin.us is a main node for one thing ran by iirc Rob himself and I believe he is offline atm and its a known situation hence low difficulty and www.grcpool.com is well maintained by its host and yes I get filtered vs open as a reply for both , where I got open on the others..
It's not like the wiki list is old , it is regularly edited and maintained and nodes are added and removed by the people that run their nodes themselves.
This right here is why I hate that we use wiki and a dns forward from gridcoin.us vs our own website , people can just edit and remove things prematurely without properly checking. Pretty much anybody can remove and or deface anything wiki based such as the node list and guides and any information hosted on the wiki pages such as the .config pages etc or node list. I defaced the wiki page " the meaning of life " when the site first was put online thanks to anybody can edit wiki pages.
You need to use nmap or tcping or a proper tool imo more than one redundantly and from multiple locations thanks to peering and the internets backbones and outages , ddos and other possible provider related issues to check along with give time for a reply ffs especially for the person whom hosts said nodes to fix the issue or remove the entry.
It could be a simple client crashed or they have a vps and have no idea the host rebooted the host node and currently gridcoinresearchd is not running and they manually start it.  I see not only did you intend but you already removed them without any comments or responses by anybody vs waiting. That does not change those lines in your /src/net.cpp anyways so what was/is the point of being impatient? We are global and people are on different time zones & those nodes may be down for maintenance or other planned reasons.

**Comment by barton2526** [comment]
@grcjamezz I see no removals recently from the addnodes page on the wiki: https://wiki.gridcoin.us/index.php?title=List_of_Addnodes&action=history

**Comment by tomasbrod** [comment]
The nodes are redundant for the reason that they can fail.

**Comment by wilkart** [comment]
I monitor nodes correctly. They should be available across world on TCP/32749 otherwise they are not public nodes. I am aware they are all in the code for redundancy.
My issue was at some moment I was on the branch where all redundant nodes are unavailable, they were only two.

node.gridcoin.us
www.grcpool.com

And they are down since March 2018 at least and that's is why I came to thinking it might be a time to suggest removal from the code and wiki.

I do not even think the www.grcpool.com will ever open public node at the same IP as they have WWW. They moved to CloudFlare and they would need Enterprise plan to do so as far as I know.

I can contact maintainers for confirm what is an official statement of that two nodes. 

The other idea I have is we are keeping that two nodes in the code for testing or internal purposes.

Anyway I keep my monitors running and I will keep eyes of all nodes.

Thanks all for comments.

**Comment by wilkart** [comment]
I have a confirmation from admin-grcpool-com  about current public node maintained by them. It is "node.grcpool.com". BGB updated our wiki page too. 
So, I believe the "www.grcpool.com" in the code should be updated to "node.grcpool.com" safely.

**Comment by denravonska** [comment]
Closed by #783.
