### ISSUE TITLE
rpcconnect from windows desktop to linux docker container not working

### ISSUE THREAD

**Issue by meilon** [gridcoin-community/Gridcoin-Research#1191]
Hi there,

I just thought I could create a docker container to host a staking wallet on my server. Getting gridcoinresearchd to run in a container was somewhat easy, but I can't connect to it from my windows desktop to check the balance etc. What am I doing wrong?

The docker container runs with the following in its gridcoinresearch.conf

    rpcuser=thisismyuser
    rpcpassword=thisismypassword
    rpcallowip=172.17.0.1
    server=1

and this is in the gridcoinresearch.conf of the Windows client:

    rpcconnect=hostip
    rpcport=15715
    rpcuser=thisismyuser
    rpcpassword=thisismypassword

If I do a curl request like 

    curl --user thisismyuser:thisismypassword --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"getinfo","params":[]}' -H 'content-type:text/plain;' http://hostip:15715/

I get a response, so the RPC server is working. I can't get the client to connect, it always opens my local wallet, not the one on the server.

Both are running the latest versions, the server is running 3.7.13.0-28~ubuntu16.04.1 and the Windows client is running v3.7.13.0-g9c821ca73.

What am I doing wrong?

**Comment by iFoggz** [comment]
so your trying to rpc from your windows wallet to your docker wallet?

the -rpcconnect command itself is for use with daemon i believe. and when used as command line argument it will not load wallet but connect to the ip port with user/pass to the rpc server. then perform command and exit the application.

the daemon does not work with windows. so u cannot even load the windows wallet and expect it to rpc connect to say your docker server. you could do HTTP calls to the docker rpc server. but cannot go client windows -> client docker

**Comment by meilon** [comment]
I tried it with the -rpcconnect via command line in windows, but still my windows wallet was opened, not the one in the docker container. I tried adding the arguments for username, password and port, but that changed nothing

**Comment by iFoggz** [comment]
thats because there is no daemon for windows. daemon would of been gridcoinresearchd.exe not gridcoinresearch.exe. we are aware of this. it is on the list of to dos

**Comment by tomasbrod** [comment]
It is **unsupported** to connect GUI wallet to remote running daemon. Only CLI rpc access is supported.
We are sorry. There is intention to bring this functionality in the future (~2y).

**Comment by jamescowens** [comment]
If you do the full autotools build yourself, using cross-compile or using WSL, there is a gridcoinresearchd.exe that is produced during that build process in addition to the gridcoinresearch.exe GUI version. The gridcoinresearchd.exe executable will not fully daemonize ON ITS OWN, because "forking" the way Unix/Linux does it is not supported in Windows. The executable IS functional, however and can be used in the following manner...

1. It can be made a service in Windows 7 and above by starting as a task in task scheduler. (This is the replacement for the old srvany.exe)

2. From the command prompt, gridcoinresearchd.exe can be used in RPC mode.

So, if you have the GUI running with server=1 in the config and RPC enabled and configured properly, then doing gridcoinresearchd.exe getinfo will operate as expected. If you set up gridcoinresearchd.exe as a task on startup that is running the actual wallet, then talking to that by running gridcoinresearchd.exe getinfo will also work. Using gridcoinreseearchd.exe to talk to a remote wallet should also work if rpc is configured properly.

Note that the NN is NOT loaded when running the gridcoinresearchd.exe as a "daemon" in Windows.

**Comment by jamescowens** [comment]
@tomasbrod @Foggyx420 please see my above comment. My work with the fQtActive flag (which is in production) to fix the simultaneous compile of both gridcoinresearchd.exe and gridcoinresearch.exe actually is all we needed to solve the gridcoinresearchd.exe problem.

Self daemonization will never be supported on Windows, but the gridcoinresearchd.exe can be easily wrapped by a startup task in task scheduler to operate in a headless manner similar to systemd in Linux, and gridcoinresearchd.exe also operates properly from the command line in rpc mode. I have actually done this on my Windows VM and logged off/on and the gridcoinresearchd.exe survives the logoff/logon...

I would say we are done with the Windows "daemon". We simply need to publish the gridcoinresearchd.exe that is being built along with gridcoinresearch.exe.

**Comment by jamescowens** [comment]
I already tested with the task scheduler. It works.

**Comment by meilon** [comment]
Then I'd like to program my own little web GUI. Is there a full Gridcoin RPC API documentation? I guess most of http://chainquery.com/bitcoin-api is still true, but I'm sure because of staking there are some additions/changes? Using the "help" method from the JSON RPC is a bit tedious.

**Comment by jamescowens** [comment]
@meilon The best place is to reference the code. Go to the staging branch, which will become release very soon with very few changes, and start with https://github.com/gridcoin-community/Gridcoin-Research/blob/staging/src/rpcserver.cpp line 270.

**Comment by tomasbrod** [comment]
@meilon Please search around. There is someone who was/is already working on alternative GUI with rpc support.
Can someone add a link to the Steemit article, please?

**Comment by meilon** [comment]
@tomasbrod I searched but only found a NodeJS library for the rpc part, not a full GUI. If someone finds it, please hit me up. Otherwise I'm going to write a NodeJS web app using the mentioned node-gridcoin.

**Comment by jamescowens** [comment]
closing this issue.

**Comment by meilon** [comment]
> It is **unsupported** to connect GUI wallet to remote running daemon. Only CLI rpc access is supported.
> We are sorry. There is intention to bring this functionality in the future (~2y).

Coding a Web GUI never took off, and now, pretty much two years later the big GUI release happend. Sadly, while using either the gridcoinresearch.conf rpcxxx options or via the CLI, the GUI still doesn't connect to the remote daemon.
@tomasbrod any new estimates?

**Comment by cyrossignol** [comment]
@meilon The latest release presents a new appearance as an intermediate step on the way to a full GUI rewrite. It does not include the ability to connect a GUI as a thin client to a remote node. This is still a desired feature, but there is no estimated timeline yet. Like the RPC server, remote GUI features are vulnerable to malware, so the implementation needs to be carefully designed for wider use. This is much less of a concern for the in-process GUI that we have today (the RPC server is disabled by default when starting the GUI).

Since you run the wallet in a container, you might consider building the image with the GUI executable and [Xpra](https://xpra.org/) as a short-term solution. Xpra provides for a secure remote connection to the wallet's GUI window running under a dummy X server in the container. I use this approach for some of my nodes. It's a bit nicer than plain X11 forwarding.

**Comment by meilon** [comment]
Thank you for the update, maybe I give your suggestion a shot. Otherwise I'll just ask again in two years 😉
