### ISSUE TITLE
Rain on all user in Neural Network

### ISSUE THREAD

**Issue by startailcoon** [gridcoin-community/Gridcoin-Research#125]
Currently you can only rain on all users in a specific project. 

I'm going to reward all users of the network with rain from whatever I make on votes on my Gridcoin Weekly posts on Steemit. But currently it doesn't seem possible.

I propose a "Rain" button on the main Neural Network window to allow rain on all users. Below the buttons for syncing/refreshing the data would be a good spot?

**Comment by grctest** [comment]
You can recreate project rain with the 'sendmany' command.

https://grcnode.co.uk/NeuralNetwork.html
https://grcnode.co.uk/Stats/Reports/NNReport.json (not always up to date)

Then here's some javascript for creating the sendmany command for individual projects instead of the whole neural network: https://github.com/grctest/grcnode/blob/master/Front%20End/source/js/MISC/xml.js#L148

I could look into providing this project rain script on the neuralnetwork page?

But yeah, through the client there's only individual project rain.

EDIT: I've provided this functionality here: https://grcnode.co.uk/NeuralNetwork.html

**Comment by startailcoon** [comment]
Thanks to grctest we can now get a sendmany string to use in the wallet directly. A new issue has arisen with this method tough.

The string generated is so long that the console in the wallet can't handle it. The string has to be split in two. The input can't handle more than roughly 1000 addresses.

Doing the payments twice is no problem now, but it would be very nice if this could looked at in the future.

**Comment by grctest** [comment]
Perhaps instead of extending 'sendmany' to more than 1000 recipients I could instead edit my script to create multiple 'sendmany' transactions?

**Comment by startailcoon** [comment]
It's a good enough solution for the time being. Still a bug that can be addressed along the road, absolutely not something that has to be high priority.

**Comment by grctest** [comment]
@startailcoon Fixed the neural rain page, the individual projects still haven't been fixed but i'll get around to that later. https://grcnode.co.uk/NeuralNetwork.html

I've added in 5 fields for up to 5000 users, if we get more than that I can increase it (or work out a better system by that point).

**Comment by grctest** [comment]
Neural network grcnode page is still glitched out because of 'null' values included in the output, I believe the 'sendmany' command can support thousands of recipients & that it's my fault you were getting the error. Probably worth closing here & opening the issue on the grcnode repo.

Cheers :)

**Comment by startailcoon** [comment]
Issue closed on request by grctest
