### ISSUE TITLE
Allow more than two outputs on CoinStake transaction

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1256]
Allow more than two outputs on CoinStake transaction so  #1244 can more efficiently split coins.

**Comment by jamescowens** [comment]
@tomasbrod Yes.... this would be a welcome change, because splitting into 2 works, but being able to split n-ways for really large UTXO's, is much more efficient.

Since we are talking about this... is your thinking to make the following generalization...

main.cpp:3186...

                    for (unsigned int i = 3; i < tx.vout.size(); i++)

and (in #1244 version) miner.cpp:730

    else if (nUTXOCount > 2)
        nUTXOCount = 2;

the "3" and the "2" a function of block version... i.e. something like

unsigned int MaxCoinStakeOutputs(int nVersion)
{
    unsigned int MaxStakeOutputs = (nVersion >= 10) ? 5 : 2;
    return(MaxStakeOutputs);
}


So the "3" becomes (MaxCoinStakeOutputs(nVersion) + 1)

and the 2 becomes MaxCoinStakeOutputs(blocknew.nVersion)

? (I used 5 here as the split limit..)

**Comment by jamescowens** [comment]
Sometimes I HATE markdown...

**Comment by tomasbrod** [comment]
It looks like the original code only checks for non-empty outputs. This should be preserved up to bv9, to avoid forks. From bv10 on, just `it (block.vtx.size() > 6) return error()`.

**Comment by jamescowens** [comment]
Do you think 5 non-zero outputs is enough? (check if vtx.size is 6 or greater), or should we use a higher number? I like the harder check of ensuring there are no more than 6 outputs (or whatever we select as the new limit) rather than simply verifying that the outputs above are zero. Why would you want to allow those outputs to be there anyway, if they are zero...

**Comment by jamescowens** [comment]
This is in Camilla. Closing.
