### ISSUE TITLE
rejecting stakes

### ISSUE THREAD

**Issue by vgiaime** [gridcoin-community/Gridcoin-Research#1274]
I've been doing Boinc since 2012. been crunching for a couple years, still a rookie.
for last 6 months+, constant error "rejected stakes" haven't received rewards in 11 months. 
07.11.12.0 fixed forking issue but no reward since. I have no idea how to resolve.
From gridcoin stats:
Beacon Status: advertised about 3 weeks ago @ 1320548
Neural Network Share: 0.01%
Estimated Minted/Day: 3.57 GRC
Estimated Interest/Day: 0.05 GRC
Time Since Last Reward: 11 months, 3 weeks, 3 days, 17 hours, 17 minutes, 17 seconds ago
Estimated Research Owed: 1,282.28 GRC
Estimated Interest Owed: 16.97 GRC

any help would be greatly appreciated.

**Comment by iFoggz** [comment]
hello, lets see if we can figure out why your stakes are being rejected;

First when a stake is rejected it can be due to no problems at all or an issue;

Have you noticed any mining error messages on the ui or in getmininginfo?

Have you checked out `beaconstatus` rpc to make sure there is no issues with your beacon or keys?

After a rejected stake have you checked your debug.log file for any information that may be helpful to understanding your situation?

Have your used the `cpids` rpc call to make sure your project settings are valid for gridcoin?

Also note the look back period for payments is 6 months. anything beyond that would not actually come through unfortunately. I wish you would of came for assistance sooner then later.

If you find any information feel free to share. however if u find information in your beaconstatus of concern do not post the private key

**Comment by vgiaime** [comment]
"Beacon Exists" : "Yes",
"Beacon Timestamp" : "07-30-2018 19:03:23",

**Comment by vgiaime** [comment]
unfortunately, I leave it running on a desktop un-monitored most of the day.

**Comment by vgiaime** [comment]
I was on a fork about a year ago, was getting rewards that never were confirmed... I lost about 1500 coins. went from 220 to 690-something. I updated from a zip file to 07.11.12.0 and it seemed to resolve. I am definitely not on a fork, yet no rewards in almost a year :(

**Comment by vgiaime** [comment]
I replied to you on GitHub. I’m sure most of my reply is useless to you but I am trying 😊

 

Victor Giaime

vic@veneer1.com

Ph: (516) 536-6480

**Comment by tomasbrod** [comment]
@vgiaime Most interesting from `beaconstatus` is the line where it says success of fail. If fail, than also the error message in there.

**Comment by vgiaime** [comment]
"Magnitude (As of last superblock)" : 14.00000000,
"Block Signing Test Results" : true,
"Configuration Status" : "SUCCESSFUL"

**Comment by vgiaime** [comment]
Is it possible that with 1154 coin it could take a year to get a reward? I can't think that is possible.

**Comment by vgiaime** [comment]
the only error I have seen in the ui is  "2 stakes rejected", "4 stakes rejected" and so on.

**Comment by tomasbrod** [comment]
First of all, ensure you are running the latest version of wallet: **3.7.15**.0 .

@vgiaime We need more info to debug this issue. Please search for your `debug.log`, locate line like `StakeMiner: Block vehemently rejected` and post the messages leading to that error. It should tell us why the staked blocks were rejected. If it is too bothersome for you, just post the whole thing. "Attach files by dragging & dropping, selecting them, or pasting from the clipboard." Please note that the wallet truncates the log fine when you (re-)start it.

**Comment by iFoggz** [comment]
@vgiaime staking a probability thou more coins you have the less time it can potentially take. follow @tomasbrod 's message and lets see if we can sort out your issue. thanks again

**Comment by vgiaime** [comment]
I am running 3.7.12.0 / i was unsuccessful installing it today.

[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/2307520/debug.log)

**Comment by vgiaime** [comment]
I meant unsuccessful installing 07.11.15 today

**Comment by vgiaime** [comment]
I realize now I restarted this morning trying to resolve. The log file I sent you is truncated ☹

 

Victor Giaime

vic@veneer1.com

Ph: (516) 536-6480

**Comment by vgiaime** [comment]
no, the msi file ran without incident. but when I look at "about gridcoin" it still says version 07.11.12

**Comment by vgiaime** [comment]
instructions for updating from the zip file?

**Comment by personthingman2** [comment]
The installation directory recently changed from "Program Files (x86)" to "Program Files". So if you're using a shortcut you'll have to update it to point to the new installation directory.

**Comment by vgiaime** [comment]
[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/2307668/debug.log)
found an older one in backup

**Comment by vgiaime** [comment]
[debug (2).log](https://github.com/gridcoin-community/Gridcoin-Research/files/2307678/debug.2.log)
and another from July

**Comment by iFoggz** [comment]
will review the logs. also u can always uninstall the wallet and install the 3.7.15.0 . ur wallet and config file are stored elsewhere in appdata so the uninstall will not affect them thou u can always backup the appdata folder for gridcoin if u wish.

**Comment by iFoggz** [comment]
in the second debug.log:

```08/18/18 04:36:54 
CreateCoinStake: Found Kernel;
08/18/18 04:36:54 CreateCoinStake: added kernel type=1 credit=15.416651

08/18/18 04:36:54 StakeMiner: created rest of the block
08/18/18 04:36:54 GetHistoricalMagnitude: Last staked block found at height 1005668, but cannot verify magnitude older than 6 months (min 1158189)!

08/18/18 04:36:54 CreateGridcoinReward: for ce2a4b70c866643a115da634fc7f06fc mint 1.347401 {RSAWeight 11.000000} Research 1.110000, Interest 0.237336 

08/18/18 04:36:54 ERROR: CreateGridcoinReward: Mint 1.347401 of 1.375000 too small
08/18/18 04:37:02 
CreateCoinStake: Found Kernel;
08/18/18 04:37:02 CreateCoinStake: added kernel type=1 credit=15.416651

08/18/18 04:37:02 StakeMiner: created rest of the block
08/18/18 04:37:02 GetHistoricalMagnitude: Last staked block found at height 1005668, but cannot verify magnitude older than 6 months (min 1158189)!

08/18/18 04:37:02 CreateGridcoinReward: for ce2a4b70c866643a115da634fc7f06fc mint 1.347401 {RSAWeight 11.000000} Research 1.110000, Interest 0.237336 

08/18/18 04:37:02 ERROR: CreateGridcoinReward: Mint 1.347401 of 1.375000 too small
```

u have been trying to stake but your last reward is over 6 months old so it has no previous basis to make a reward with using history so it tries to make a newbie block (without being a newbie) with the calculation of that plus the interest owed on the coins staking is less then the minimum mint. so if u wait awhile longer u will get that initial block so that from there on out u can stake regular normal por since u will have a previous block. I wish you would of came for help on this topic sooner then passing the 6 month period then things would be more in your favor.

your biggest input is almost at an age where u will get that POR block soon. so give it a little more time and get your foot back in the door.

you appear to be where you should be in terms of being able to stake a POR or POS block.

as for your july log it appears you had CPID issues but those have since been addressed.

Keep on staking and you will know when you succeed and get a stake.

Keep monitoring your debug.log as staked are rejected. you will get a stake with your setup as is as all appears in order now. Note the mint limiter is also based on network difficulty. the higher difficulty for next block means a higher mint needed. Patience and cheers. hope thaat helps

**Comment by iFoggz** [comment]
@tomasbrod if u notice anything else i have missed let this user know as ur more familiar with the miner then i am.

**Comment by vgiaime** [comment]
So in this case, my patience worked against me. I’ll use the same patience and will advise when rewards flow. Will I lose all the coin I’m currently owed? (according to gridcoinstats)

**Comment by jamescowens** [comment]
Have you tried 4.0.1.0? It fixed a number of corner cases with people having problems staking.

**Comment by jamescowens** [comment]
Closing for no response. Will reopen if warranted.

**Comment by vgiaime** [comment]
Hi all.. received 1 payout since we last spoke. I don’t want to wait 6 months again. I have not received any rejected stake error messages since last payout

 

Beacon Status: advertised about 2 months ago @ 1472446 <https://gridcoinstats.eu/block/1472446> 

Neural Network Share: 0.01%

Estimated Minted/Day: 3.77 GRC

Time Since Last Reward: 4 months, 5 days, 13 hours, 25 minutes, 52 seconds ago

Estimated Research Owe: 473.82 GRC

**Comment by vgiaime** [comment]
Hi all.. received 1 payout since we last spoke. I don’t want to wait 6 months again. I have not received any rejected stake error messages since last payout

Beacon Status: advertised about 2 months ago @ 1472446 <https://gridcoinstats.eu/block/1472446> 

Neural Network Share: 0.02%

Estimated Minted/Day: 4.37 GRC

Time Since Last Reward: 4 months, 3 weeks, 2 days, 6 hours, 54 minutes, 37 seconds ago

Estimated Research Owed: 625.59 GRC

**Comment by denravonska** [comment]
@vgiaime It looks like you have a lot of tiny transaction, presumably from a faucet. These small transactions might be too small to stake. What you can do is to merge the coins into one or two UTXOs by enabling coin control and sending the coins to yourself.
