### ISSUE TITLE
Gridcoinresearch.exe not running at all

### ISSUE THREAD

**Issue by pls2000** [gridcoin-community/Gridcoin-Research#1302]
When started, gridcoinresearch.exe runs for about 1/2 second, then exits with exit code 3. There are no messages, no debug logs (and adding -debug does not produce a debug log either), no relevant entries in the Windows event log. Nothing at all that I can see. Installing the latest version from GitHub did not help.

I hope the exit cod 3 means something to someone.

Any suggestions?

**Comment by tomasbrod** [comment]
Nope. Code 3 does not mean anything.
Please try `-debug -printtoconsole` options from console to direct the messages to console.
Usually there is debug.log file written, unless the directory is unwriteable for the current user. This can happen when you accidentally start the program As administrator.

**Comment by jamescowens** [comment]
The official builds are not published on Github. Do you mean you installed 3.7.16.0 from https://www.gridcoin.us/index.htm#Downloads?

How did you do the install? Did you uninstall the previous version, then install the new one? Also, what was the version of the previous one you were running?

Tomas' idea is a good one. If you accidentally ran the program for the first time as an administrator (with elevation), the data directory may have the wrong permissions. You can try running the wallet as an administrator by right clicking the icon and selecting run as administrator and see if that works. If it does, you will need to adjust your permissions on the data directory. Otherwise...

You can try the following to see if it helps...

1. Backup all of %AppData%\GridcoinResearch for safekeeping.
2. After backing up, delete everything in %AppData%\GridcoinResearch *except* gridcoinresearch.conf, wallet.dat, and the walletbackups subdirectory
3. Uninstall Gridcoin. (This will not disturb the data files. It only removes the executables.)
4. Check and make sure that old files are not left behind from the 32-bit version in C:\Program Files (x86)\GridcoinResearch. If you find that directory, delete it. (It will ask for elevation to do that.)
5. Install the most up-to-date version from https://www.gridcoin.us/index.htm#Downloads. This is a 64-bit application, so it will install to C:\Program Files\GridcoinResearch by default.
6. Download the snapshot from https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip. Unzip the snapshot into the %AppData%\GridcoinResearch directory. If you did it right you should see the following files/subdirectories in that directory...

blk0001.dat    (from the snapshot)
gridcoinresearch.conf (not deleted from your original data)
\txleveldb (from the snapshot)
wallet.dat (not deleted from your original data)
\walletbackups (not deleted from your original data)

7. Try and run the wallet and see if it starts up normally and begins to sync from the snapshot forward.

Report back your results here.

**Comment by pls2000** [comment]
I will do that later today. 

One question, just to clear things for me. What is the default location for the GRC database on Windows? And does this location change depending on whether you select All Users or Current User on installation?

**Comment by pls2000** [comment]
jamescowens:
I uninstalled from the control panel, then deleted the GridcoinResearch directory to make sure nothing remained behind. The reinstall was done by downloading from the URL you give. I have no idea what version I reinstalled because there is nothing on that site that tells me what version I'm downloading. And since I can't run the program, I can ask it what version it is. The control panel says I have version 45.8 installed. I suspect that isn't helpful.

After following your instructions, I run gridcoinresearch.exe non elevated. It runs for about 1/2 second and exits. No messages, no log files, no event log entries. Adding -debug -printtoconsole yields exactly the same results.


Are there instructions for building the Windows version? Or can some give me a debug Windows build with symbols. I'm thinking that running the program inside Visual Studio is the only thing that will give any information. 

  ++PLS

The acl on C:\Users\pls\AppData\Roaming\GridcoinResearch is full control for Administrators and full control for my login.

**Comment by jamescowens** [comment]
That is not necessary.

**Comment by jamescowens** [comment]
The Windows executable is built with gcc and autotools (the main executable), and the boincstake.dll is built with VS. So debugging is a bit of a pain. This is one of the many reasons we are going to retire the VB NN in favor of a native C++ NN.

Anyway. Please try this to see if it is the NN that is causing the problem. Please (temporarily) move the boincstake.dll file out of the C:\Program Files\GridcoinResearch directory to somewhere else. (The computer will ask for elevation to do that.) Then try to start the wallet.

If it starts without boincstake.dll in place, it is on the NN side, and may indicate you have a problem with your .NET runtime.

The latest release version is 3.7.16.0 BTW, which is what you downloaded.

**Comment by iFoggz** [comment]
if u move the boincstake.dll the boincstake.dll will not load. CLSID is pointed to its location and only a few other locations are involved. i find the error code odd. no debug log creation means it occured early. also boincstake.dll is not loaded till the gui is loaded completely.

**Comment by elhippiesupremo** [comment]
I've had a similar problem today when my computer restarted from a power outage. Gridcoin wouldn't start at all. Ran Windows updates, installed new version of gridcoin from the site, and it still wouldn't start. **It turns out that my gridcoinresearch configuration file was blank**. When I copied the config from a backup, gridcoin started right up again. easy fix.

**Comment by jamescowens** [comment]
@Pls2000 please check your config file with an editor and make sure it is not damaged.

**Comment by jamescowens** [comment]
@pls2000 Update?

**Comment by pls2000** [comment]
It was the config file. It had been overwritten with nulls. I wish I knew how that happened.  The wallet is running now, out of sync but catching up.

This really needs to have an error message added.

Thanks for the assistance. I'm going to close this and open a new issue to provide error messages if the config file is unreadable or badly formatted.

**Comment by pls2000** [comment]
jamescowens: What is the status of converting the Neural Network to C++. I have more years experience as a C++ programmer than I care to think about and would be willing to contribute.

**Comment by jamescowens** [comment]
You should talk to @Foggyx420. He has done a lot of work on the conversion... You might be able to assist.

**Comment by jamescowens** [comment]
Fix merged for Camilla. Closing.
