### ISSUE TITLE
execute advertisebeacon checking for > 1.01 GRC instead of 0.00011 GRC

### ISSUE THREAD

**Issue by comprehendreality** [gridcoin-community/Gridcoin-Research#132]
https://github.com/gridcoin/Gridcoin-Research/blob/e135ffb1a4ef2fa428396c13172d39870b27e40f/src/rpcblockchain.cpp#L1445

Is there a reason this function will only advertise the beacon when GRC balance is greater than 1.01? The cost of the beacon is 1000x less than this amount. 

If this IS the intended behavior for some reason I do not know about, then I would recommend the error message be modify to indicate the minimum balance of 1.01 GRC as it is very confusing for new users like me.

**Comment by comprehendreality** [comment]
added a pull request for a new error message.

https://github.com/gridcoin/Gridcoin-Research/pull/133

**Comment by gridcoin** [comment]
It was rounded up to 1.01 because it is quite common for network fees to be charged when the current block is > 1meg in size, but there is no way to predict the fees ahead of time.  Ill pull this in when I do my next round of pulls.  

We dont want to make it lower as that would make it easier for people to expiriment with beacons, so lets leave it at 1.01 for now until we see how things go.

**Comment by comprehendreality** [comment]
Ah, that makes sense now. Hopefully this will save the next newbie from spending too much time googling for a solution to a non-issue. Thanks for the quick response.
