### ISSUE TITLE
Superblock (de)serialization using internal mechanisms.

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1384]
We currently use a homebrew, Gridcoin specific format for superblocks which mix tagged syntax with binary data. This format is cumbersome to use and it does not leverage existing serialization mechanisms.

We should replace all the contents in Pack/UnpackBinarySuperblock with serialization of classes using the functions in serialize.h. This has several benefits:

- Less code
- More readable
- Easier to maintain
- Faster
- ~Builtin endian handling~
- Smaller contracts

This may be a future issue as it changes the format of the superblocks and will require a mandatory.

**Comment by tomasbrod** [comment]
The endian handling is not actually built in serialize.h . Last time I checked it always used native endian. We get away just because there are no mainstream big endian machines. Importing updated serialize from bitcoin should solve.

**Comment by jamescowens** [comment]
I agree. We should pull in the bitcoin serialize and then redo the superblock format at the next mandatory. We should also change the hashing of the SB contract to native double SHA256 too at the same time.

**Comment by denravonska** [comment]
Oh, oops. You're right about the endian support. I [yoinked that](https://github.com/denravonska/Gridcoin-Research/commit/9a2331559772abe3a795a43007de5fc439d4de34#diff-1fc2d3d7edc00ab8ea29eb1ca30cdcbb) from bitcoin in the big-endian work branch.

**Comment by tomasbrod** [comment]
I like to write htons-like calls explicitly (eg: y[0]=(x>>8)&0xFF; y[1]=x&0xFF;) because htons is a library function that does not inline.

**Comment by denravonska** [comment]
I believe most libraries will translate ntohs/htons to byteswap instructions via defines. See [this](https://godbolt.org/z/J_8tHg) output which translate the `htons` into a `rorw` instruction.

**Comment by grcjamezz** [comment]
speaking no mainstream big endian , there is but gridcoin seems to ignorantly ignore the amount of risc machines out there running gnu unix that could be on the network supporting gridcoin. there is a reason i ported to powerpc64  , want to port to gnu linux on my sub ultra 80 and been waiting on mercosity and his dec alpha 21064. SRC should compile and work on everything. Maybe pull your heads out of x86/amd64/arm only. Remiinds br @denravonska , was going to power on my silver g5 mac tower as you asked so can update the porting to powerpc64 as you asked just been physically limited. I still ave 3.5.#.# that I ported and got working , you getting the genesis block added in since i am not a block chain knowledgeable person ffs i dont even code. Gridcoin is missing out on the thousands with real unix machines since the real world has them sitting around. Kids and their intel macs and pc's coding things only. BTW was bullshit , I am a community member and accomplished what people like Erkan tried and was working on while he was still GRC8 , go back to the vote sd it doesn't state locked down to a group circle jerk it says open to all of us but you guys reject what isn't from your little dev click " didnt say push the creator out of dev " it says open to all no matter if updating the centralization of/at seednode level in /src/net.cpp or porting it says ALL are welcome but since that passed the ignorance of a secret buddies only and only who we like thats kissing our ass seems not to be working GRIDCOIN has tanked to not any value and you guys refuse to listen and accept work from the community. That and the word " official " and " trusted community members " where people in those places have their own agenda and remove who THEY don't like such as NeuralMiner because he was first to setup a discord server for himself named Gridcoin just like Barton26 and the slack testnet.... The community is falling apart and the value is tanking even lower and it already looked like GRC was R.I.P. and if can't pull heads out asses there is no reason to fix the code if its going to keep going to a $0.00 so maybe hold off of code and work on unity of the team and allowing others to be involved , we ain't here to make friends but we are a team.

**Comment by barton2526** [comment]
Your toxic rants have no place on this github.  Stick to the topic at hand.

**Comment by denravonska** [comment]
@grcjamezz Deleted your post. Feel free to repost it, leaving out the slander.

**Comment by jamescowens** [comment]
This is addressed by @cyrossignol's commits in https://github.com/gridcoin-community/Gridcoin-Research/pull/1488

**Comment by jamescowens** [comment]
We will keep this open until the mandatory is released that uses this new functionality.

**Comment by jamescowens** [comment]
Closing this as it has been addressed and is in the development branch for release in Fern.
