### ISSUE TITLE
Reindex Process Taking very long Time. Is it correct?

### ISSUE THREAD

**Issue by mariajohnfranklin** [gridcoin-community/Gridcoin-Research#1386]
I have updated snapshot and started reindex yesterday.  Sync Process is still running. Can I stop in halfway? Normally how long time it will take to sync?

my debug.log shows below

01/15/19 10:51:48 Received block 109417c70d887e1742b4e27db069edcc80f24b45852f452e7ef8d2684c1aa516;
01/15/19 10:51:48 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:51:48 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:51:48 {SBC} new best {109417c70d887e1742b4e27db069edcc80f24b45852f452e7ef8d2684c1aa516 1488883} ;
01/15/19 10:51:48 {PB}: ACC;
01/15/19 10:52:47 Received block bb4996298b457134dd16ab9320ae35bfe51fd36a21016b1f6e13631f4b37f99a;
01/15/19 10:52:47 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:52:47 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:52:47 {SBC} new best {bb4996298b457134dd16ab9320ae35bfe51fd36a21016b1f6e13631f4b37f99a 1488884} ;

**Comment by mariajohnfranklin** [comment]
How to find Reindex progress status?

**Comment by tomasbrod** [comment]
We do not call it reindex, so I am not exactly sure what are doing. If you downloaded *snapshot* and installed it correctly (delete txleveldb, blk0001.dat and extract), then the process will be finished as soon as the wallet window shows up. The snapshot was made in the past, so the wallet needs to download blocks made since then. This is accompained by spinning progress indicator and `{SBC} new best` messages. The last number on the sbc line (1488884) is block height your wallet is at. You can use getblockcount to get that number alternatively. Current block number can be found at https://gridcoinstats.eu/ . Download is finished as soon as your height reaches network height.
