### ISSUE TITLE
No Rewards almost 5 months?

### ISSUE THREAD

**Issue by vgiaime** [gridcoin-community/Gridcoin-Research#1420]
Beacon Status: advertised about 2 months ago @ 1472446
Neural Network Share: 0.02%
Estimated Minted/Day: 4.37 GRC

Time Since Last Reward: 4 months, 3 weeks, 2 days, 6 hours, 54 minutes, 37 seconds ago
Estimated Research Owed: 625.59 GRC

**Comment by jamescowens** [comment]
1. Your balance is pretty low. If gridcoinstats.eu is correct you have about 1400 GRC. The network difficulty has been averaging about 9.5 lately, so the 80% confidence interval for staking with that balance is 16000/1400 * 9.5 = 109 days or about 3.6 months. Staking is a random process, so you are in the “20%”. GRC is dirt cheap right now. It is about $50 to get 10K GRC.

2. As @denravonska pointed out in the other issue, you are receiving almost daily near dust like transactions presumably from a faucet. You would be wise to send your entire balance to yourself to consolidate all of that. Technically any UTXO larger than 0.0125 GRC should stake, but we have seen some corner case reports of people having trouble staking get things going again by consolidating very small UTXO’s. If you don’t know how to do this let us know and we will help you through it.

3. Just to be sure you should run a beaconstatus and make sure it reports successful.

**Comment by vgiaime** [comment]
I would really appreciate the help to consolidate UTXO... 
It says cpid is already in chain beacon sent 2 months ago.

**Comment by jamescowens** [comment]
Did it report “successful”?

If you don’t mind your whole balance being on one address, then all you have to do is send your whole balance to yourself. (Just put your own address in the send address.) You will need to leave a little room for the transaction fee, which should be far less than 1 GRC.

**Comment by vgiaime** [comment]
10:31:25



advertisebeacon

 


10:31:25



{
"Result": "FAIL",
"CPID": "ce2a4b70c866643a115da634fc7f06fc",
"Message": "",
"Errors": "ALREADY_IN_CHAIN",
"FAILURE": "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
}

 

Victor Giaime

vic@veneer1.com

Ph: (516) 536-6480

**Comment by vgiaime** [comment]
I executed wrong command. Beaconstatus reported successful.

 

Victor Giaime

vic@veneer1.com

Ph: (516) 536-6480

**Comment by jamescowens** [comment]
Did you try sending your balance to yourself?

**Comment by denravonska** [comment]
@vgiaime It looks like this is a duplicate of #1274. Please only update one if they are the same. Just to reiterate my reply in that post:

> It looks like you have a lot of tiny transaction, presumably from a faucet. These small transactions might be too small to stake. What you can do is to merge the coins into one or two UTXOs by enabling coin control and sending the coins to yourself.

If you have the option, please join Slack for more direct communication.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Maybe if the Gridcoin community was better at helpdesk and leadership ( really whom ever controls or setup what ever service & dictates it ) as not every user is part of the cult clique. If they were more direct vs beat around the bush this issue submission and many others would #1 be closed #2 a new user and presumably many other new and older user's alike would know to consolidate UTXO's let alone know it's a wallet receive address #3 Gridcoin could possibly recover in value after 2 years this coming 4th of July 2019. These threads benefit more than the user whom submit's an issue even if it explains it's because it's by design. 

vgiaime , as I know gridcoinstats.eu is and always will be beta and isn't a 100% reliable source for user info on balance as it shows I have 28k but I am 300grc away from 30k ( I staked and hit 30k as I was typing this), I can only give you an example of direct direction's based off the balance shown at this minute of 1,443.84 GRC without you providing your true realtime balance value. Send 1,443.00 GRC from your wallet's send tab to the address SHRRPhL323ugkDDhFondQn2hFtLkNUzq6Y as it has your lumpsum & I assume was the first generated wallet's default install address. Then also only use that address of SHRRPhL323ugkDDhFondQn2hFtLkNUzq6Y for faucets, irc/discord/slack bot's etc & any GRC purchases.

I could say join irc.freenode.org #gridcoin-help & #gridcoin and/or slack and " The Gridcoin PRIVATE discord but if the supposed " trusted community leaders " and Gridcoin get along gang will mute and or ban you from the channel and or server's if they do not like you and/or agree with you and your own opinion's or views that you voice as it's a 90% community made up of pocket protector sporting squares with their own agenda's. This here is THE best support location as it's 100% just use your web browser no app needed support system and where you came for help. 
They have even tossed discord & slack user account's for posting public domain info, they have done ALL of the above to me but here I am trying to help you, as I have always tried to go out of my way to help any user as I only have always had the best of intentions. at heart 
Also there is the Gridcoin hangouts via the mumble app and #fireside-chat on discord verses typing and real time verbal help is far more helpful in my opinion.

I would also like to advise you on a way for you to possibly earn more Gridcoin but it's your Boinc & your hardware. You should pick 1 CPU and 1 GPU project vs either being so spread out or just being the same hardware attached to so many project's. This will do the same effect as consolidating wallet addresses or UTXO's. If it's the same machines attached to 11 project's you allowing the Boinc project's admin's dictate what project's get priority to process work. Some project's set a short 2-3 day deadline where others are even 70+ day & if you don't correctly set project priority value's you are not in control. This could possibly give you a higher magnitude value thus higher GRC per day. I would base my choices from https://gridcoinstats.eu/project as you can see what projects are flooded with user's thus yielding very little GRC and less users yielding more. There is another factor being team Gridcoin user's attached to project's hosts/core count or GPU's and you would need to dig into and decide that for yourself. 

I hope I have been helpful, I had 100+ UTXO's and it corrupted my wallet.dat and the very helpful dev @jamescowens had me consolidate all of my balance to a new wallet install and 1 UTXO.
I have 5 now but the 99.9% lumpsum goes to my main address as you can see here https://gridcoinstats.eu/cpid/1ac793c529cd6ffa942afaef7c5068c2. This sort of setup of UTXO's is what we are trying to get you to do, using myself as an example. 
Don't worry about splitstake'ing or sidestaking if you read about it till 50k+ GRC or more either.
As I type this I staked a block after watching difficulty go from 6.### to 36.### and between then down to 3.### erratically for the last week and longer.

P.S. I didn't know what a UTXO was for a year and I spent every and all day & night chatting via the freenode irc channels and weekly/bi-weekly multi hour long hangout's and after party. Not all of us are crypto baller's like the whales and dev's dedicating our lives to crypto currency and blockchain and ran into GRC accidentally. So sometimes you have to spell it out verses being so short with user's and making them feel stupid. #blockchain4lyfe

**Comment by vgiaime** [comment]
this is the single most helpful response I’ve ever gotten, I need to put some time and thought into how to rearrange things.

**Comment by philipswift** [comment]
What a rant, that must of taken ages to write. This place is only for dev's to be brutually honest. In the time it took grcjamezz to write all that he could of researched and found a resolution ! Use Slack to attack from now on and just buy some GRC as others have previously suggested. 
PS: I have not had any rewards for ages either and I have all pass marks under diagnostics and also some staking. I'll try and replicate the error on a new windows build.

**Comment by vgiaime** [comment]
Thanks everyone. Combined UXTO's and resulting stake and payout commensurate with 5 month wait.
