### ISSUE TITLE
Crash on Loading Screen

### ISSUE THREAD

**Issue by adolgov** [gridcoin-community/Gridcoin-Research#1452]
At 1610000/1610000 Blocks Loaded, the app crashes with an `Assertion failed!` error.

```
File:kernel.cpp, Line 735

Expression: pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)
```

![image](https://user-images.githubusercontent.com/6618631/57109405-3e025c80-6cea-11e9-9ff4-d064a92791ee.png)

64 bit Windows version. Client used to run previously, but I haven't run it in a couple of days.

**Comment by jamescowens** [comment]
Indicates a corrupted blockchain. Please install the snapshot and resync...

1) Make a backup of your wallet.dat and gridcoinresearch.conf files as well as your walletbackups folder. 
2) Delete everything in your Gridcoin Research directory (Linux = .GridcoinResearch/, Windows = %appdata%\GridcoinResearch) EXCEPT your wallet.dat, gridcoinresearch.conf, and walletbackups folder. 
3) Download the latest snapshot. 
4) Extract the snapshot into your Gridcoin directory. 
5) Launch the wallet.

**Comment by adolgov** [comment]
Thanks. I did the above steps, but I get a different error now.

The wallet starts up and begins to sync the chain; however, it gets an `EXCEPTION: St13runtime_error` at block 1548333, and then stops making progress.

![image](https://user-images.githubusercontent.com/6618631/57147112-b2391080-6d7b-11e9-812b-68db73c82d22.png)

I have tried the above process twice; however, it stops in the same place.

**Comment by jamescowens** [comment]
So that is your wallet file. There are two different databases in Gridcoin (just like Bitcoin). You have wallet.dat, which is the wallet database, and the blockchain database, which is blk0001.dat and the txleveldb directory. It appears your wallet file is also corrupt. You can try a backup from the walletbackups folder.

Here is the procedure...

1. Shut down the wallet.
2. Go to %AppData%\GridcoinResearch in Explorer and rename your wallet.dat wallet_save.dat to set the corrupted version aside.
3. Go to the %AppData%\GridcoinResearch\walletbackups directory and look for a recent wallet backup in the form of wallet.dat-yyyy-mm-ddThh-mm-ss. If you find a recent one, copy that file to the parent directory %AppData%\GridcoinResearch. Rename that file in %AppData%\GridcoinResearch to wallet.dat
4. Restart your wallet.

Assuming the backup copy is fairly recent and is not corrupted, you should be ok.

Did your computer have a hard crash recently? The only time we see this sort of problem is when people's computers experience a power failure or have a hard lockup, or other severe hardware issue.

We were also seeing some of this due to Windows 10 aggressive shutdowns during updates. This was fixed in 4.0.2.0.

**Comment by tomasbrod** [comment]
`Fund Creation of HD Wallet for GridCoin`? Do we even have hd wallet?

**Comment by jamescowens** [comment]
That is one of the bizarre polls that someone put up in mainnet.

**Comment by adolgov** [comment]
Thanks. Reverting to a backup wallet.dat seemed to have worked.

I'm not 100% sure, but I do think that there was a hard power cycle at some point, so that could have been the initiating cause of the corruption, as you suggested.
