### ISSUE TITLE
Tried to compile new version 4.0.3.0. Problems with curl

### ISSUE THREAD

**Issue by michaelblucher** [gridcoin-community/Gridcoin-Research#1458]
Hi 
I tried to compile version 4.0.3.0, but the config is giving me problems with Curl.
I get the following messages from the config:
Checking for CURL... no
configure; error; libcurl  not found
Note: When I compiled version 4.0.2.0 I did NOT get this problem. It compiled OK.

When I attempt to install Curl, the package manager tries to install Curl3,
which is a problem as I have a lot of software that requires Curl4, including BOINC etc.
I don't seem to be able to install Curl4, assuming Gridcoin-Research needs Curl4.
Has anyone come across this problem before?
Regards
Michael B.

**Comment by jamescowens** [comment]
Which distribution are you using?

**Comment by jamescowens** [comment]
If you are on Ubuntu, try doing sudo apt install libcurl4-gnutls-dev

**Comment by michaelblucher** [comment]
Hi
I'm using knoppix 8.1 which is debian based, but not debian
I tried the command you supplied, it gets lots of errors, missing packages and ip addresses not found.
Just curious.  I've compiled every update previously without issues, why this version?
Michael B.

**Comment by jamescowens** [comment]
Not sure. We can't test every Linux distro out there. Some additional dependencies are necessary for the native C++ scraper/NN functionality. We haven't had any issues with the various flavors of debian/Ubuntu or even OpenSuSE.

Why don't you try the depends build path instead of the brew path? It takes longer, but reduces the dependency requirements to the minimum.

Here is an outline of the procedure.

1. Pull down/update the master branch for your build in the usual way. Assuming this is in <some path>/Gridcoin-Research and you have changed to that directory...
2. cd depends
3. make HOST=x86_64-pc-linux-gnu QT_59=1 -jX where X is the number of cores you have or the free memory you have in GB, whichever is less. This will take a fair amount of time, and does a local build of all of the dependencies.
4. cd .. (back to the build root)
5. ./autogen.sh (to regenerate the configure script)
6.  CONFIG_SITE=$PWD/depends/x86_64-pc-linux-gnu/share/config.site ./configure --prefix=/ --enable-qt59
7. make -jX where X is the number of cores you have or the free memory you have in GB, whichever is less.
8. If this successfully completes, your executables will be in the ./src and ./src/qt directories respectively for the daemon and qt versions.
9. To remove debugging symbols and make them smaller you can do
cd src
strip gridcoinresearchd
cd qt
strip gridcoinresearch
10. You can then copy those files to a directory of your choosing for execution, or use the sudo install command to put them in the desired system directory.

**Comment by jamescowens** [comment]
What this does is create an executable with all of the first level dependencies statically linked in and incorporated into the executable.

**Comment by michaelblucher** [comment]
Thanks for that
I figured you can't test for all distros, there's just too many of them.
I trialed 12 distros before picking Knoppix. In hindsite, I would have been better off with Ubuntu or Mint.
Anyway, I'll give your notes a try.  Honestly, I don't understand some of it, but will give it a try.
The reason I have been compiling Gridcoin Research is because I could not install the binaries.
If I could just get the Gridcoin Research binaries (32 bit) and install those manually it would be so much easier.
Cheers
I'll let you know how these notes pan out. Much appreciated.
Michael B.

**Comment by jamescowens** [comment]
I hope you try it out! If you are running the 32-bit version of Linux, then you need to change the x86_64 in all of the above to i686

**Comment by caraka** [comment]
Michael, For all my Debian/Ubuntu builds, I have libcurl4-openssl-dev as a build dependency, and it is the only curl package in my container, unless that dependency pulls actual curl in when it installs. Give this one a try! It should be fine in knoppix, people have used my debian builds on knoppix in the past

**Comment by jamescowens** [comment]
Michael, follow caraka's advice first before mine. He is our build guru!

**Comment by michaelblucher** [comment]
Thank-you Caraka.  
I was able to install the suggested library, although it only worked when I hooked in the unstable switch.
The config completed and recognizes curls as existing.
I've got the make running as I type.  Which takes a little while to run on my little machine.
I'll keep you posted on the results.
Much appreciated. Thank you every-one.
Michael B.

**Comment by caraka** [comment]
You should be able to use my stretch builds on knoppix 8.1, unless you like to roll your own.

**Comment by michaelblucher** [comment]
Hi Caraka
Its not a matter of liking to roll my own.  
Knoppix 8.1 has problems downloading from depositories, some sort of access issues.
Anyway, long story short, unless I can download the binaries and install them, I have to roll my own.
Cheers
Michael B.

**Comment by michaelblucher** [comment]
Hi All
The compile went well and I'm now running 4.0.3.0
Thanks for all your help.
Much appreciated.
Michael B.

**Comment by jamescowens** [comment]
Awesome!
