### ISSUE TITLE
Possible diagnostics bug in v3.5.8.2?

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#146]
I was helping another user on irc whom also is setup as a windows node due to him getting " Verify TCP 32749	Outbound connection to 32749 failed. Please try unblocking outbound traffic to 32749.  Result	FAILED " so I went to my windows wallet and ran diags knowing I had no issue with and am serving connections.  http://xion.dopeshit.net/~blah/gridcoin/diagerror-v3.5.8.2-g-research.png and it fails on mine although shows inbound.  The other user has other issues , such as 0 magnitude after last superblock.

**Comment by Mercosity** [comment]
I have a fail error on the diagnostics section of my windows client - Verify Tcp 32749. 
The Diagnostic Result is Outbound connection to 32749 failed. Please try unblocking outbound traffic to 32749.
32749 is unblocked for both inbound and outbound traffic and has been unblocked since I first installed my wallet/client some 3 months + ago. I have not reset any parameters and there has been no change in my firewall permissions or router permission since then. I fact according to these permissions this port is open inbound and outbound.

I also have a 0 Mag condition on my wallet.

**Comment by gridcoin** [comment]
It looks like the external node.gridcoin.us went down about 500 blocks ago and thats the node it tries to perform the test against.   I reset it.  Please try again now.

For 0 magnitude, check the magnitude in the last superblock (list magnitude CPID).  If its 0, then we are waiting for a superblock with your CPID in it.  If thats the case, check the neural network to ensure your future magnitude will be picked up.

**Comment by 47an** [comment]
The TCP Outbound connection to 32749 is now Passed
Do to 0 magnitude the superblock did change this and solved the issue for us.
