### ISSUE TITLE
Run code through a beautifier

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#159]
The code has been touched by many different developers, all with with different coding conventions such as indent sizes, newlines, bracket placements etc. It could be a good idea to, after a release, do all pending pull requests and run the entire code base through a beautifier such as [astyle](http://astyle.sourceforge.net) or something similar.

The reason this is an issue is partly because it's hard to read but mostly because it's difficult to contribute. I spent over an hour trying to submit a pull request but no matter how I tried I always got these massive diffs because half the file used CR as newline and the rest was CRLF.

**Comment by gridcoin** [comment]
A beautifier is not the same issue as knowing how to edit a text file with CRLFs in it.  CRLFs are used in the windows world and unix uses a linefeed.  

So I would recommend editing the file in a text editor with the correct config settings set when the file is loaded, and then the diff will only contain what you changed.

Im not going to agree with you on a beautifier.  I look at the code every other day, and there is no magic silver bullet that is going to make gridcoin great because it was run through someones limited program.  The code does not look bad, otherwise I would be fixing the codes beauty instead of working on the code.  There is a risk associated with running programs that have data embedded in them for one, and another thing is the tabs and linefeeds that are in the code neither look horrible, but in some cases have a purpose.  Sure there are patches of code that could be improved but it might be dead code that should be removed.  Id be up for refactoring the code first.  The reason that is not happening is because we have a plethora of commits from bitcoin that might be integrated in which changes the structure of the code.

**Comment by denravonska** [comment]
Fair enough on the Bitcoin integration. I guess that's actually a good reason not to streamline the coding conventions.
When it comes to CR/CRLF, it was not my decision to mix and match. The source came with arbitrary line endings.
