### ISSUE TITLE
Wallet shows incorrect amounts in transactions

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#161]
I have had this issue for at least 2-3 weeks now. It seems that my wallet shows the incorrect amount for transactions, usually way larger than what they should be. The wallet balance is still correct though.

For example, one transaction shows up as `"amount" : 3515.14740728`. If I check that txid on explorer.gridcoinasia.com I can see that the proper amount should be `56.79270124` which is what I have concluded to be correct when I have monitored how much my balance increases. What's interesting is that the block explorer over at http://www.gridresearchcorp.com shows the exact same, incorrect value of `3515.14740728`. So the two explorers show different values for the transactions.
Another thing is that gridcoinresearchcorp shows the _correct_ transactions for each block for my CPID if I just look at my CPID stats page.

I have verified through IRC that I'm not on a fork and I have tried to rescan for missing transactions. I have also scanned the wallet for errors but it came up as ok. Anything else I can do?

**Comment by gridcoin** [comment]
It sounds like you are viewing a transaction with Change.  Basically, since POS was released, for higher security, a client will stake its balance that was Change from a prior transaction and pay itself change in the amount of the prior transaction minus stake owed, so as to completely use up the prior transaction and not bloat the wallet.
Let me give you an example.  Suppose you received 500,000 grc once.  Then you spent 2000 of it.  Now you have 498,000 left.  When a stake occurs, if this was the only coin record in your wallet, and if you were owed 100 on the stake, you would pay out 498000 and receive 498100, leaving you with 100 addl grc.
So what you can do is try 'getrawtransaction txid 1' and see if each leg of the tx adds up to the behavior mentioned here.

Thanks,
Rob
