### ISSUE TITLE
Copy transaction id

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1675]
The output of the " copy transaction id " function gives an incorrect output. it adds a suffix -000 attached to the transition id. This makes it very difficult for a new user to interface with the platform. With current explorer the output does not show any results, removing the suffix instead everything is displayed.

**Comment by div72** [comment]
Seems like the problem is in [this line](https://github.com/gridcoin-community/Gridcoin-Research/blob/development/src/qt/transactionrecord.cpp#L345)?

**Comment by jamescowens** [comment]
Hmm... that suffix is there because a transaction in the core may actually be decomposed into multiple transactions in the GUI model for viewing. The suffix is actually a sequence number to label the subtransactions.

The intent of passing that when GetTxID() is called is misguided, however, because that composite ID is not actually a real thing that can be used to look up transactions. It is safe to remove the strprintf("-%03d", idx) I think, because the only thing that consumes it is the transaction table model for display purposes.

@div72 If you would like to do the one-liner and test it, then submit a PR, that would be great.
