### ISSUE TITLE
Replace consolidatemsunspent's Multi-Sig-Type Numbering System

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1689]
consolidatemsunspent uses a number for determining what type of multisignature wallet you are using. It has numbering which is inconstant, and doesn't capture all of the ways you can have a mulitsignature wallet configure.

Instead of using a single number, it should use two. One for the number of signatures you need and another one for the number of signatures you have total. Or if possible, extract it from the multisignature address that it has as an input

**Comment by jamescowens** [comment]
You want to PR the change?

**Comment by RoboticMind** [comment]
I would if I could figure out how to compute the reedeemscript sizes. It appears to get values that come from magic in the code so I don't know how to replace it

**Comment by iFoggz** [comment]
I see what your getting at here. I thought the notes were detailed but guess there could be more information. I'll look into this and redeemscripts as predictable in size if you know how many signatures required and how many there are. i'll get back to you on this one.

**Comment by iFoggz** [comment]
Ok i've looked into it. it is possible to determine how many signatures the address needs and the total number of signatures that can sign the said transaction. your wallet would contain the redeemScript so that information is obtainable by the OP codes. You can assign this to me james and I will get around to it.
