### ISSUE TITLE
RPC JSON Output for Disabled Polls

### ISSUE THREAD

**Issue by startailcoon** [gridcoin-community/Gridcoin-Research#1965]
Disabled polls does not output the poll title for v1 poll types.
This makes it impossible to track these disabled polls when they come in.

Examples
```
      "txid": "4461db021906f96e35ce5df6a68fdc07083f6eed99fe8650b665167ba2f680ff",
      "version": 1,
      "time": 1438645382,
      "locktime": 0,
      "hashboinc": "<MT>poll</MT><MK>Foundation_Coin_Burn_Refund_Jens</MK><MV>1</MV><MA>D</MA><MS>MEQCID9cU6xBi6qv/hnTNja9fqnChbfRRVN3zHDCbviWq5RuAiAhbgXjZa8kU4ZdRTQleabkHEx3qZKkmMfef/8Rps9ZZQ==</MS>",
      "contracts": [
        {
          "version": 1,
          "type": "poll",
          "action": "D",
          "body": {
            "version": 1,
            "title": "",
            "question": "",
            "url": "",
            "type": 1,
            "weight_type": 0,
            "response_type": 3,
            "duration_days": 0,
            "choices": [
              {
                "id": 0,
                "label": ""
              }
            ]
          }
        }
      ],
```

**Comment by presciencia** [comment]
It looks like it is possible to parse title from from `hashboinc` property for workaround?

**Comment by jamescowens** [comment]
Yes, but that would not be the proper way to fix it. Essentially this should be coming from tx.GetContracts(). Since it is version 1, it should be in the

`        if (nVersion == 1 && vContracts.empty() && GRC::Contract::Detect(hashBoinc)) {
            REF(vContracts).emplace_back(GRC::Contract::Parse(hashBoinc));
`

which means it should be Parsing the hashBoinc.

We have

`Contract Contract::Parse(const std::string& message)
{
    if (message.empty()) {
        return Contract();
    }

    return Contract(
        1, // Legacy XML-like string contracts always parse to a v1 contract.
        Contract::Type::Parse(ExtractXML(message, "<MT>", "</MT>")),
        Contract::Action::Parse(ExtractXML(message, "<MA>", "</MA>")),
        Contract::Body(ContractPayload::Make<LegacyPayload>(
            ExtractXML(message, "<MK>", "</MK>"),
            ExtractXML(message, "<MV>", "</MV>"))));
}
`

So my guess is that the problem is somewhere in Contract::Body(ContractPayload::Make<LegacyPayload>... this is pretty fancy virtual function gymnastics, and something is probably going wrong in there...

**Comment by cyrossignol** [comment]
@presciencia The `hashboinc` field is a legacy artifact that's difficult to parse reliably, and we may deprecate that field for removal from RPC output in the future. We should prefer to enable clients to gather data from structured JSON when interacting with the wallet's RPC interface to minimize the amount of legacy nonsense that client developers need to learn.
