### ISSUE TITLE
Create a GUI for the consolidateunspent Command

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1984]
Currently the only way to consolidate UTXOs with the GUI is manually with the advance coin control or you have to open the console and run the `consolidateunspent` command. Since a fair number of people run into issues with having too many small UTXOs, a simple GUI for this would be helpful

**Comment by delta1513** [comment]
I think that this feature should be as thin as possible to reduce development load.

Here are my suggestions:
1. Have this a setting you can toggle on or off. Considering the command is meant to be run regularly, have some set default arguments to the the `consolidateunspent` command  and have it run on some regular basis or event.
2. Make a button somewhere in the wallet (or in coin control) to basically achieve the same functionality as idea (1) except it will be at the user's discretion instead of on a regular basis.

Personally I like idea (2) because it is less spammy.

**Comment by jamescowens** [comment]
I was hoping to get to this in Hilda but just didn't have time.

**Comment by jamescowens** [comment]
I am going to do a full wizard in another PR, but #2111 should be sufficient in the interim.
