### ISSUE TITLE
Lost Coins?

### ISSUE THREAD

**Issue by vgiaime** [gridcoin-community/Gridcoin-Research#1993]
Somehow 3350 coins that are connected to my cpid are not in my wallet and I can't figure out how to retrieve them?

**Comment by jamescowens** [comment]
Can you provide more details so we can help? Did you see these coins in your actual wallet or on the explorer? When was the last time you saw them? Did you upgrade late (after the hard forks)?

Please provide more information.

**Comment by vgiaime** [comment]
vgiaime (CPID:ce2a4b70c866643a115da634fc7f06fc)
Balance: 3,369.59 GRC on gridcoin stats,.. only 7 in wallet rn. its been some time since i saw them last in my wallet. last upgrade was 11/09/20

**Comment by jamescowens** [comment]
This is you I think. http://main.gridcoinstats.eu/address/SHRRPhL323ugkDDhFondQn2hFtLkNUzq6Y

Can you confirm that SHRRPhL323ugkDDhFondQn2hFtLkNUzq6Y is listed in your receive tab as a valid address you own?

**Comment by vgiaime** [comment]
I own that address but lost access to it around 05/19/20 when my pc crashed. SHRRPhL323ugkDDhFondQn2hFtLkNUzq6Y is no longer listed in my receive tab but those are my coins I have been trying to recover.

 

You can see it is owned by my cpid. What can be done?

**Comment by jamescowens** [comment]
If you don't have the private key for that address, there is nothing we can do. What happened when your PC crashed? What did you do to recover?

**Comment by jamescowens** [comment]
Update? I will wait another day and then close this issue.

**Comment by vgiaime** [comment]
We had to do a complete windows reset. I though my wallet backup was good but it seemed to make a new wallet.  Advice on how I find my former private key?

**Comment by jamescowens** [comment]
Do you still have the backup files? Did you backup the entire data folder? In particular your original data folder backup should have a subdirectory in it called walletbackups that contain backups of your wallet in the form of wallet.dat-<date>. This series of backups will be frozen in time at the time the backup of the data directory was taken before the machine was reset.

The reset machine was likely to create new backups in the data folder on the reset machine, so these backups will likely not have the right key. You need the backups from the old data directory to get the key back. (I am saying this because you seem to imply that you tried using the old wallet.dat from the old backup and you said it didn't work, probably because it was corrupted.

**Comment by vgiaime** [comment]
Thanks James, I will give it a try.

**Comment by jamescowens** [comment]
Status?

**Comment by vgiaime** [comment]
Haven’t had the time James I hope to get to it this weekend.

**Comment by jamescowens** [comment]
Ok.

**Comment by vgiaime** [comment]
I found a wallet backup from 2017 and yet it still loads without previous private key. I am thoroughly frustrated. Yet I still receive beacon rain that I think is tied to the value of my wallet from before. I am completely unqualified to figure this out. ☹ the 2017 backup wallet.dat was on my server completely separate from my pc crash…

**Comment by jamescowens** [comment]
If you have lost that key, those coins are gone. If someone sends rain to that address, those coins are effectively burnt. You either need to find a backup with that key, or readvertise your beacon to put it on a different key. You will not be able to recover those coins or any future coins sent to that address unless you find the private key for that address.

**Comment by jamescowens** [comment]
Closing. You can open again if there are further updates.
