### ISSUE TITLE
Rename staking field to reduce confusion?

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#2032]
Links to #847

Currently among new users there seems to be confusion around the staking line on the main page of the wallet.

I propose having it renamed to smth like: On Cooldown.

**Comment by cyrossignol** [comment]
The precise term is "immature". If we need more clarity, we can label the field as "Immature (staked)" with a tool tip that reads, "Amount staked for a recent block that must wait for 110 confirmations to mature before you can spend it."

It isn't perfectly accurate because the field aggregates amounts for all immature UTXOs, but I think this tool tip is less confusing for most users than an alternative that tries to express those details. A majority won't stake another block before the previous stake matures.
