### ISSUE TITLE
When voting on 'have you downloaded the latest...'; [Discussion URL] infers 'Fern' is the latest when Hilda is current

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#2044]
**Clicks**: Wallet>Voting, choose to load/reload and wait, right click to vote on 'installed latest..', left click 'vote', UI='Placevote', then it's second line down for [Discussion URL].
Right clicking and choosing 'results' offers up the same out of date [Discussion URL]. BTW this is currently set to land on Reddit.
Maybe just remove the [Discussion URL], period? The wallet has 'Community>Chat room' that hyperlinks to [https://gridcoin.us/contact.htm#GridcoinWallet](https://gridcoin.us/contact.htm#GridcoinWallet) that will suffice if the user needs info' on the vote subject?

**Comment by div72** [comment]
There isn't much that can be done here, that is a poll made before the Hilda release.

Also according to the passed [poll proposal](https://github.com/gridcoin-community/Gridcoin-Tasks/issues/227) all poll types require a discussion link except for opinion polls. Since protocol-wise there's nothing separating opinion polls from other type of polls, it really isn't possible to remove the discussion link just from those and it doesn't really make sense to remove it from all.

**Comment by jamescowens** [comment]
@philipswift we can't change this because polls are immutable and not changeable by a central authority. This poll was made before the Hilda release, and was made with a ridiculously long lifespan. This really is a much larger discussion about people making bad polls and what to do about it from a community and protocol perspective.
