### ISSUE TITLE
Version info does not change after wallet upgrade

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#209]
After upgrading to the newest wallet, I looked in "Control Panel/Uninstall a program", and I noticed that the "Installed on" date, and the "Version" information have remained unchanged since I did a fresh install with MSI 41.7 on November 2, 2016.

I am running Windows 8.1, and through IRC I have confirmed that @barton2526 is also experiencing this symptom on Windows 10.

**Comment by gridcoin** [comment]
This is a long standing bug in the installer.  Its been happening since the first version.  I have been incrementing the version and Guid.  The only way around it is to change installers.  We have an issue with that solution, due to having a TLB file that needs registered.  

You can work around it by uninstalling first, then reinstalling.

The easiest way to upgrade is to use the upgrader:
grcrestarter upgrade

It will upgrade the files automatically without version problems.

**Comment by Peppernrino** [comment]
Oh shit, sorry! Didn't know it was an old bug. :P

And yeah, I usually uninstall and reinstall programs as a matter of course, but I was stoked on getting the upgrade feature working.
