### ISSUE TITLE
New GUI: Hard to see empty check box

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#2121]
Checkboxes in Coin Control utxo list is very dark and hard to see in the new GUI.
![image](https://user-images.githubusercontent.com/79360493/116806785-8bab3d00-ab2f-11eb-85ce-a55a93fd3703.png)

Looks better in the Send tab.
![image](https://user-images.githubusercontent.com/79360493/116806819-c7de9d80-ab2f-11eb-9dfe-5b1cff017ef7.png)

Running Win10

**Comment by jamescowens** [comment]
I noticed this too and reported it to @cyrossignol when I was working on the consolidate GUI PR.

**Comment by cyrossignol** [comment]
Yes, checkbox and radio button controls are being redesigned. These are a bit more involved, so they didn't make it in the first pass.

**Comment by nathanielcwm** [comment]
Additionally the poll pie charts have a white background:
![image](https://user-images.githubusercontent.com/22572406/116994159-f06ebf00-ad0a-11eb-97ec-c59a3592ef7a.png)

QR Codes also suffer from this issue:
![image](https://user-images.githubusercontent.com/22572406/116994380-33c92d80-ad0b-11eb-94a3-6856d3690b1a.png)

**Comment by nathanielcwm** [comment]
I don't see any options for qr code styling in libqrencode docs so the latter may just have to stay ;(

Edit: There does seem to be color support in libqrencode but it's not mentioned anywhere in the docs.

**Comment by nathanielcwm** [comment]
https://github.com/fukuchi/libqrencode/blob/715e29fd4cd71b6e452ae0f4e36d917b43122ce8/qrenc.c#L212

Looks like qrencode just changes the colours?

**Comment by jamescowens** [comment]
I am not sure the QuickResponse code standard allows white bits on a dark background. I will have to look.

**Comment by cyrossignol** [comment]
I looked into theming the QR code images earlier. There is less to say about standards than there is about realistic portability. While many scanners function just fine based on contrast difference, so the colors don't really matter, some may have trouble with non-light backgrounds. We can dim the images for dark mode or change the foreground color, and inverted colors can work for some scanners, but I don't think it's worth the effort if we risk sacrificing portability. The QR code dialog is hardly open for a moment, if ever, during normal use.

I'll address the poll result charts when I get to the voting section.

**Comment by nathanielcwm** [comment]
Also not sure if this is intentional but the width of: Overview, receive and favourites is different from the other tabs.

![image](https://user-images.githubusercontent.com/22572406/119797157-8feb3000-bf0c-11eb-9445-a5d1966b73a8.png)

![image](https://user-images.githubusercontent.com/22572406/119797189-95487a80-bf0c-11eb-819b-6a0ba146c838.png)

**Comment by cyrossignol** [comment]
@nathanielcwm I made pages that can't really use the extra space more responsive to window sizes... instead of diluting the content with spacing, the margins start to grow when above a certain window size. We have to put the space somewhere unless we can think of a way to use it for bigger windows.

In the old UI, it was hard to track where information lined up when the columns expanded above a certain point because everything was so spaced out.
