### ISSUE TITLE
Wrong transaction dates for imported private keys

### ISSUE THREAD

**Issue by mherrmann3** [gridcoin-community/Gridcoin-Research#2130]
Dear Gridcoin wallet devs,

I'm importing a few private keys / addresses into a new wallet.

Importing the first private key (here: of the beacon, let's call it _'pk1'_) into a new empty wallet works well regarding the restore of all "transactions". But as soon as I import a second private key (let's call it _'pk2'_), all its transactions (after the rescan is complete) get the same date as the most recent 'transaction' related to _pk1_ (here: the last time it rained on the beacon address). After some transactions occurred on an address of the new wallet (let's call it _'add0'_), I restored a copy of the new wallet (its state: with imported _pk1_, but before I had imported _pk2_), imported _pk2_ again, and: all transactions related to _pk2_ get the date of the most recent transaction (now: of _add0_).

So I believe it's a general issue and not related to the initial beacon address/private key import. Or is it?

Thanks in advance for looking at it!

**Comment by jamescowens** [comment]
@div72 can you take a look at this?

**Comment by div72** [comment]
@jamescowens Will do.

**Comment by div72** [comment]
@jamescowens Apparently, this is the intended behavior of `nTimeSmart` calculation. I propose to deviate from the upstream and use `nTime` instead of `nTimeSmart`. Thoughts?

Relevant:
https://github.com/bitcoin/bitcoin/blob/6d1d33d33491a98bb0dbf64ea7e4743200e71474/src/wallet/wallet.cpp#L3756
https://github.com/bitcoin/bitcoin/issues/6662
https://github.com/bitcoin/bitcoin/issues/11703
https://github.com/bitcoin/bitcoin/issues/20181
https://github.com/bitcoin/bitcoin/pull/12024
https://github.com/bitcoin/bitcoin/pull/20591

**Comment by jamescowens** [comment]
Ugh. I want @cyrossignol's opinion on this too.

**Comment by cyrossignol** [comment]
@div72 The `CTransaction::nTime` field is an old artifact from Peercoin's proof-of-stake protocol used to determine coin age. Since Gridcoin's current protocol doesn't base consensus and block subsidy on coin age anymore, the `nTime` field can be considered vestigial (even though it's buried pretty deeply in our current code). I'd avoid using `nTime` in new code unless we have a reasonably strong case for it to allow for more flexibility in how we can deal with that field in the future. 

That said, the `nTimeSmart` routine doesn't seem appropriate for transactions imported when rescanning for an existing key. I think the time of confirmation of the block that contains a discovered transaction would make more sense.

**Comment by jamescowens** [comment]
@div72, I agree with @cyrossignol on this.
