### ISSUE TITLE
[Gui] Transaction History becomes cluttered after rainbymagnitude

### ISSUE THREAD

**Issue by NetherStar64** [gridcoin-community/Gridcoin-Research#2165]
After doing a rainbymagnitude, the transaction list in the gui is cluttered with many small transactions. It would look better if e.g. it was in a single entry
![image](https://user-images.githubusercontent.com/63533734/120917870-d893ad80-c6b1-11eb-9534-14103690e8a3.png)

**Comment by jamescowens** [comment]
This cannot be supported right now, because a rain transaction is currently essentially a regular transaction that has a lot of outputs. There is no separate contract for rain, and so there is no programmatic way to distinguish between a regular transaction and a rain. If we decide to create a contract for rain, which is likely, I will revisit this, but I am skeptical, because the request violates the rules that the transaction lists each payee in a send transaction separately so you have a visible record of where the funds went to.

**Comment by jamescowens** [comment]
I have decided to leave this open as a feature request for discussion.

**Comment by RoboticMind** [comment]
> ... the request violates the rules that the transaction lists each payee in a send transaction separately so you have a visible record of where the funds went to.

Perhaps it could instead have a expand/contract button on the transaction instead? Although that might cause big performance issues with hundreds of transactions

**Comment by jamescowens** [comment]
That is probably not workable... and it is not worth the effort for this corner-case.

**Comment by NetherStar64** [comment]
Maybe display one transaction in the list with a rain Icon and list the
Addresses and Amount sent in the transaction details

**Comment by jamescowens** [comment]
It already is in the details. The issue is being able to special case this situation to NOT display the details for a rain in the transaction grid. This cannot be done without rain being implemented with a rain contract to be able to distinguish between a rain and an ordinary transaction.

**Comment by jamescowens** [comment]
There is a complicated decomposition function that maps between core transactions and the displayed transactions in the GUI. In general, the core transactions are much more coarse-grained. One core transaction maps to one or more displayed transaction rows depending on nature of the transaction.
