### ISSUE TITLE
[POLL] Feature request: Use all owned addresses to verify poll creation fee

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2166]
Presently, when creating a poll the user requires a balance of 100k GRC in 250 or less UTXOs *on one address*.  Given that users can vote with all addresses they own, it seems logical that one could fulfill the poll creation balance check with a valid balance spread over multiple addresses (assuming UTXO count is <250).

**Comment by cyrossignol** [comment]
This is a spam mitigation. Unlike votes, polls are fully verified upon receipt. A node defers expensive verification for vote contracts until it calculates the poll result. The address/UTXO limit caps the overhead needed to manage poll spam that would fail to confirm in the chain.

We can probably relax the limits without significantly eroding protection&mdash;it's pretty strict. I didn't see much need for the additional complexity, though, since a poll creator should have a strong enough understanding of the software to reorganize UTXOs as needed. Worst case, someone who wants to make a poll without that knowledge may not understand the poll requirements and should at least participate in a community that can help guide the poll creation (or that can submit a poll on their behalf).

**Comment by nathanielcwm** [comment]
Well it doesn't apprar to be that helpful as a form as spam mitigation lmao.

**Comment by jamescowens** [comment]
After careful consideration, I think @cyrossignol is right on this, and I am going to leave the code as is. I am not really interested in making it easier to do a poll, further, I actually like the idea that all of the funds in the attestation for the poll come from one address. Folks that have enough funds to do a poll should have a good enough understanding of UTXO's to be able to meet the requirement.
