### ISSUE TITLE
Whitelist issue: Amicable Numbers not showing in the NN

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#218]
The project 'Amicable Numbers' which was voted into the whitelist, is not showing up in the whitelist yet, despite having its project registration transaction broadcast.

Perhaps there are issues with amicable number's user statistics files?

Amicable numbers:
https://cryptocointalk.com/topic/52195-search-for-all-amicable-pairs-up-to-264-new-boinc-project/
https://sech.me/boinc/Amicable/

Stat Files:
https://sech.me/boinc/Amicable/stats/user.gz
https://sech.me/boinc/Amicable/stats/team.gz
https://sech.me/boinc/Amicable/stats/host.gz

I was able to download the files, the user.gz file results in a valid XML file.

```
list projects
[
	{
		"Command" : "projects"
	},
	{
		"Project" : "amicable",
		"URL" : "http://"
	},
	{
		"Project" : "amicable numbers",
		"URL" : "http://"
	},
	{ ... }
]
```

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
I have been checking every superblock since the vote passed ( 3-4 now ) and don't even get that far... RTMoney was saying something about the issue being that Amicable Numbers is behind SSL . I find that ironic after the past 6 months time spent focused on SSL and the, vote denied and focus on new projects being non ssl and the movement to get current projects to implement it into their servers.
Quoted from Freenode #gridcoin " <@RTMoney_> It's because they are behind a secure http, I've been working on a work around " " <@RTMoney_> Basically when the NN tries to download the .gz it get denied "

Also I don't even get as far as you in " list projects " since this has been awaiting , its lines of blank project info like this and in between projects without the whole list this is the top for me: 
list projects


08:23:28
￼
[
{
"Command" : "projects"
},
{
"Project" : "",
"URL" : ""
},
{
"Project" : "",
"URL" : ""
},
{
"Project" : "",
"URL" : ""
},
{
"Project" : "",
"URL" : ""
},
{
"Project" : "asteroids@home",
"URL" : "http://"
},
{
"Project" : "atlas@home",
"URL" : "http://"
},
{
"Project" : "",
"URL" : ""
},
{
"Project" : "",
"URL" : ""
},
{
"Project" : "",
"URL" : ""
},
{
"Project" : "collatz conjecture",
"URL" : "http://"
},

**Comment by iFoggz** [comment]
damn hope it gets fixed soon i was looking forward to this project. also i never check list projects seems to be slow to update even CSG doesnt show up i use list network and it seems to show everything but who knows. im gonna keep an eye out for this one. cheers all involved

**Comment by bryhardt** [comment]
I had some clients pickup Amicable in list projects and some didn't after the superblock when it was whitelisted. After restarting the clients without Amicable, it did appear in the list projects. However, as pointed out, 'explainmagnitude' isn't giving anything for Amicable yet. CSG seems to be fine though.

**Comment by Foggyx420** [comment]
ya cud be the statistics files. on gridstats in under past projects with
date 1970 year. defiently having issues.

CSG is good i did a unit already it like it at it doesnt seem to produce
excessive heat.

out of curiousity u know the best place to purchase GRC with BTC. thought
about cash route but too many sketchy sites. do plan on building least i
stake balance over time. any tips.

**Comment by iFoggz** [comment]
any updates?

**Comment by iFoggz** [comment]
project admin posted on cryptocointalk forum stating there are requests for the wrong location of stats file 

log shows
 sech.me:443 - [10/Mar/2017:06:28:56 +0100] "GET /boinc/stats/user.gz HTTP/1.1" 404 162 "-" "-" "-"

he states its located in 

https://sech.me/boinc/Amicable/stats/


https://cryptocointalk.com/topic/52195-search-for-all-amicable-pairs-up-to-264-new-boinc-project/page-3#entry235035

next steps anyone?

**Comment by iFoggz** [comment]
couldnt edit my post he stated he made https://sech.me/boinc/stats/ also work.

**Comment by bryhardt** [comment]
Looks like this could be resolved? I see Amicable now in the explainmagnitude...

**Comment by iFoggz** [comment]
good to hear, lets see what happens after next superblock and network catches up. if it all works out im glad i emailed the admin :)

**Comment by iFoggz** [comment]
amicable numbers is showing on
https://gridcoinstats.eu/projects.php

ofcouse it will probably be abit till stats are shown on the site.

also appears in 'list network' with avg rac shown. 

id say this is solved now unless something else does come up
