### ISSUE TITLE
[Rpc] memorypool and getrawmempool not matching

### ISSUE THREAD

**Issue by NetherStar64** [gridcoin-community/Gridcoin-Research#2213]
When using the command memorypool, it doesn't show any transaction, however when using getrawmempool, it shows them correctly (e.g. when I do a Transaction the right txid shows in getrawmempool)

```
pi@raspberrypi:~ $ gridcoinresearchd -rpcuser=myuser -rpcpassword=mypassword memorypool
{
  "Excluded Tx": "",
  "Included Tx": ""
}
pi@raspberrypi:~ $ gridcoinresearchd -rpcuser=myuser -rpcpassword=mypassword getrawmempool
[
"ef14c21ba6cbf36baa47201e2583f3b62e3a1f82ac5dcc78cd411d880bfcf2d2"
]
```

In Gui the same:
![Screenshot_20210706_201751](https://user-images.githubusercontent.com/63533734/124648828-02e6af80-de98-11eb-880f-e4c4808321d2.jpg)

**Comment by iFoggz** [comment]
getrawmempool:
gets memorypool data on transactions stored in the memory

memorypool:
gets excluded/included tx's in miner from when a block (by you) is staked. So If you staked a block and you excluded a tx due to a bad transaction or included any and got fees for it it'll be in this variable until wallet is shutdown. 

It's incorrectly named imo or useless.

**Comment by RoboticMind** [comment]
Yeah I think it might not be bad to remove the `memorypool` command
