### ISSUE TITLE
Monochrome Tray Icon

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#2303]
# Feature Request

**Describe the Feature Request**

Monochrome Tray Icon
**Describe Preferred Solution**

Option in Display Settings to change tray icon to monochrome
**Describe Alternatives**

**Related Code**

**Additional Context**

![Screenshot at 2021-08-26 20-55-31](https://user-images.githubusercontent.com/32637824/131027580-f82e2bbf-c09a-4a43-a78c-6bf6520b5fdc.png)
![gridcoinresearch](https://user-images.githubusercontent.com/32637824/131027602-b4204822-e9f4-4b35-9285-42b0f1a4cdd5.png)

**Comment by jamescowens** [comment]
The icon is colored to distinguish mainnet from testnet. A mainnet wallet is purple, while a testnet wallet is red. I am not a big fan of the monochrome tray icon movement, BTW.

**Comment by ghost** [comment]
> The icon is colored to distinguish mainnet from testnet. A mainnet wallet is purple, while a testnet wallet is red. I am not a big fan of the monochrome tray icon movement, BTW.

Option to turn off the tray icon then?

**Comment by jamescowens** [comment]
I don't think that is a good idea.

**Comment by barton2526** [comment]
What's the harm in allowing someone to turn off the tray icon?  You would just have to disable "minimize to tray".

**Comment by jamescowens** [comment]
Because it doesn't make sense to disable the minimize to tray @barton2526.

**Comment by jamescowens** [comment]
Also, we have to consider the docker on the MacOS, which is a lot harder to deal with.

**Comment by jamescowens** [comment]
If someone else wants to step up and try to code this and submit as a PR, I will look at it.

**Comment by nathanielcwm** [comment]
> 
> 
> The icon is colored to distinguish mainnet from testnet. A mainnet wallet is purple, while a testnet wallet is red. I am not a big fan of the monochrome tray icon movement, BTW.

Maybe it would be best to force disallow testnet to use the monochrome tray icon without a startup flag?

**Comment by caraka** [comment]
Tray icons are turned off by default in newer debian releases by default, because that is the new Gnome default. Ubuntu continues to turn them back on by default in it's customised Gnome desktop. They are a popular feature. If people are really keen to have a monochrome tray icon, we could supply one (normally unused) and tell people how to back up the original and rename the monochrome in a single command. It would likely get overwritten with each update, but it would be far less overhead on our part to support what is (currently) a fringe movement.

**Comment by jamescowens** [comment]
My change in label should indicate my stance on this...
