### ISSUE TITLE
Repair and enable disabled unit tests

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#237]
When fixing #232 some tests where disabled to get a working test runner. The tests that need repairing involve:

- base58_tests.cpp
- ~~key_tests.cpp~~
- script_tests.cpp
- transaction_tests.cpp

See https://github.com/gridcoin/Gridcoin-Research/commit/2cdcb7ae9d83232c0ad4bf7a05351032aef741b1

**Comment by denravonska** [comment]
If someone knows an easy way to create and initialize a `CCrypter` object let me know so I can test its `Encrypt` and `Decrypt`.

**Comment by tomasbrod** [comment]
Needs documentation on how to actually run the tests:
```
cd src/
make -f makefile.unix test
```

**Comment by tomasbrod** [comment]
Excellent. The autotools build systems seems to get take a good shape. I can't wait for it.

**Comment by barton2526** [comment]
@TheCharlatan What is the status of this issue in Autotools?

**Comment by sedited** [comment]
Tests now get compiled automatically when building. The new Travis recipe runs the test for every new Pull Request / Commit. However the tests @denravonska mentioned above are still disabled.

**Comment by sedited** [comment]
The base58 and checkpoint tests are fixed now, but the script tests and transaction tests remain. The transaction tests need to harvested from the blockchain again, most of them represent some edge cases that were detected at some point. 
The script tests however currently only fail, because of the assertion `assert(txin.prevout.hash == txFrom.GetHash());`  brought into the code with https://github.com/CoinBlack/blackcoin/commit/9cb3d570daef2c040d29e58411b2c66e0fb00bc6 . If the assertion is removed, the script tests run fine. I am not sure what the bug was this assertion supposedly fixed, maybe @tomasbrod knows?

**Comment by tomasbrod** [comment]
txin.prevout.hash should really match hash of the input's transaction, not sure why it is failing.

**Comment by denravonska** [comment]
Closing due to #998.
