### ISSUE TITLE
Define development process

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#238]
While the new master+development strategy caused the wallet development to really take off, it also made it a bit ad-hoc pretty quick. We now have a lot of new functionality and fixes in the development branch but very little has been done in terms of large scale testing. It could be a good idea to define some sort of process. I haven't given this much thought and it might be too rigid for continuous development, but something along the lines of:

- After a release we try to define what we want to include in the next release. Open PRs, issues, new functions etc.
- We (mostly me) try to avoid feature creep and non scheduled refactoring or fixes unless it's important enough or required to proceed.
- When the scheduled fixes have been implemented in development we merge it to staging.
- Staging only receives bug fixes from now on. Any fixes done in staging is merged to development.
- When we feel staging is stable enough we merge it to master and tag a new release.

But, as I said, it can't get too rigid. We still want a way to merge pull requests without having them go stale for a month. We might need another branch strategy for this. I'll keep thinking about it.

**Comment by philipswift** [comment]
I'm here if you need Alpha or Beta testing. I'll do what I can on as many platforms as possible. I'm mainly Windoze (sorry!) however, this is still the biggest OS for reaching out to hobbyists and those who are IT illiterate.

**Comment by Erkan-Yilmaz** [comment]
It really depends on what people want from that, and how much time they wanna invest. 
What you said above and what I know, I'd recommend these 2 things to be tackled first:

1. make **regular** mumble meetings
2. **test cases**: define + write up

Why only these 2 points at first? Because they can be used always, no matter what process/tools/decision is still to come/decided.

and for later (when it's more clear what all want): 
* the "process" to use ([Scrum](https://en.wikipedia.org/wiki/Scrum_(software_development)), ...?) and its stages can be bound on the successful execution of defined test cases (passed unit test U1-U7 and U12-U18, passed user stories S1-S5, ...)
then one also knows automatically in which stage one is currently, and what is missing to get to the next stage
and from this all... you can make as much bureaucracy as people like... or not ;-)

------

So, the initial task is:
* set a date for mumble
* define topics for mumble
more [here](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/93)

----
meetings in audio form:

1. can/should also be **separate** from normal hangouts:
 * why? since it can become too technical sometimes, or exceeds the usual hangout time which there is already like 1-2h in avg

2. meetings every 2-3 weeks
* later on we can see if/what dev process to apply, if there is enough man power and make shorter times
* ofc there is always IRC to communicate, but audio is just faster when many people meet
-----
tests and test cases: (from: software builds daily without errors; unit tests all PASS; ... to important **use cases** before release, at least)

1. define test cases:
  a. for **new changes**
  b. but also **OLD**, non-changed functions
2. decide in meeting if these are enough or what is missing ? which requirements (OS, new/old users, ...) important ?
3. what kind of test cases to create ?
* a. create unit tests? using only unit tests not sufficient
* b. since there are no other test cases in written form yet: 
* b1. create them based on important use cases (e.g. as user stories with expected result/requirements), e.g.:
  * wallet can be installed + starts
  * sending/receiving GRC
  * generate a block
  * upgrade wallet over previous version(s)
  * ... above are only titles, not the real test cases
4. creating good test cases takes time: 
* time investment should not be underestimated
* so it has to be decided how the initial test cases should be available (first in doc? later on someone makes it better: detailing, ...?)
* e.g. the user story above "wallet can be installed + starts" involves steps/requirements like:
  * which OS? get new version how? (download, internal); "starts" means: UI + functions available in no more than x seconds; doesn't crash immediately (or after x mins); for old users: their existing settings are not lost; balance still same as before; ...

------
tools to use:
* build tools
* for "testing":
  * writing test cases (testlink, ...): history available for each version
  * "At first I figured we should switch from boost::test to QTest to get one test framework for both the UI and the lowlevel code." (see [here](https://github.com/gridcoin/Gridcoin-Research/issues/232))
  * static/dynamic

but first make in meeting a list which tool to use, or if to use

**Comment by philipswift** [comment]
Can I put my penneth worth in? Can we also consider image? I know it's perceived in many ways but it counts a lot with uptake and retention of all user types. EG: The Gold 'G' when a shortcut is made to gridcoinresearch.exe. There are some super slick looking imagery and styles about and it maybe that we are not giving enough consideration to ...well there are many words to describe it....wow factor, fluidity, impressivenes....

**Comment by Peppernrino** [comment]
actually... no bullshit, i am uploading a new icon set today! :D i've been having some trouble committing to development branch. i blame github. ;)

**Comment by denravonska** [comment]
@Erkan-Yilmaz I agree that we should start with Mumble, and to start small or it will quickly become overwhelming. Initially I'm not even sure we need regular mumble meetings. It's probably sufficient with one initial release meeting to go through what we want to accomplish for the next release, how to do functionality tests and see who can help doing them. Now that we have the test runner back up every developer should try to write unit tests. Granted, the inherited code is certainly not written with unit tests in mind so some areas will be very tricky.

Anyway, I think we should start with Mumble in one form or another and add the staging branch. That should bring some structure without halting the development. Then we can start looking at bigger processes, but always remember that it has to be fun as well.

@philipswift Right now the Windows dev wallet is the least tested while being the one needing it the most. We'll let you know when we have the tools to build it :D

@philipswift @Peppernrino Wrong issue? :)

**Comment by philipswift** [comment]
OK, standing by. I'm trialling Ethereum new wallet on Win at the moment. Quite a slick look. Gives reassurance.

**Comment by tomasbrod** [comment]
Here are my thoughts for the branches:

- MASTER: latest version that is safe to use on the main network and make packages
- DEV: always build-able, merge PRs here
- developers' personal branches: do whatever you like, submit PR when ready
- (signed) _annotated_ tags: for releases on master branch, not necessary every commit/merge
- other/feature branches: in case there is not enough branches

Also I suggest changing the version number scheme, because it is currently weird with so many dots. Currently only BUILD number are changing.

**Comment by tomasbrod** [comment]
About version numbers:

- CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR
  - well, mayor and minor version number
  - release tags have this two numbers
- CLIENT_VERSION_REVISION    commits since release
- CLIENT_VERSION_BUILD       incremented every make run or packager run

But this is really low priority and does not add any functionality. So feel free to ignore :)

**Comment by denravonska** [comment]
@tomasbrod My idea with the development -> staging -> master branching was to have some safe zone to let the code mature while testing without having new code coming in. We could get the same by simply not accepting any more PRs but that can cause them to pile up and diverge.

**Comment by Quezacoatl1** [comment]
Can we somehow include changes on testnet first to assure that no changes corrupt the production chain? If I got it right, building the current dev branch version enables you to run a node with experimental code on the production chain IF the nodes do not ban you. Well in any case, I would suggest to take all changes to testnet.

Maybe we can even run 3 blockchains:

One for nightly builds
One for release candidates
And production.

Or maybe we just follow the lead of ETH or BTC. Can we just copy their updating behavior?

**Comment by tomasbrod** [comment]
bump
