### ISSUE TITLE
BlockFinder::FindByMinTime May Retroactively Change Computed AVW

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2407]
## Summary

`BlockFinder::FindByMinTime` uses an optimization to speed up its search by using the start, head, or cached blocks depending on what's closest by time. This creates a problem since block time does not always strictly increase. It may go up and down which makes it possible that going from the start would yield a different block than from the head or cached block. 

This is a problem since `PollReference::GetActiveVoteWeight` uses `BlockFinder::FindByMinTime` to find the last block in the poll. By chance or intentional manipulation, block(s) could be placed after the final block with a lower timestamp than the threshold. This would make the final block used in AVW calculation change when those blocks go onto the chain - after the poll has already ended. Additionally, once the optimization direction switches, it would change again to use when the poll truly ended. 

On polls close to the % of AVW threshold, this could be enough to change if the poll passes or not. This could cause consensus issues if AVW is ever relied upon for automatically adding a project or just a lot of confusion as to whether a poll met the threshold or not.

## Example

Min-time: 180
```
            1      2      3      4      5      6
           100 -> 170 -> 200 -> 210 -> 175 -> 240  ...
```

From the genesis block, it would return block 2 but from the tail, it would return block 5

## Fixes

The simplest possibility is just to remove the optimization and always go from the start.

One possible fix that keeps this optimization is to check backward after the found block until the timestamps go further than when a block crossing the minimum timestamp could be introduced (i.e block_time < min_time - max_accepted_timestamp_range ).

**Comment by jamescowens** [comment]
This is a very interesting issue you brought up. It is not limited to just AVW. The whole question of when the poll actually expires is a question. In reality the blocks are constrained (loosely) in time order. They cannot be infinitely off. However, in the case of a non-monotonic situation with regards to timestamps versus block number, does the poll expire, then "unexpire" when the duration is exceeded, and then another block is posted retrotime, which is back within the duration. I would say that is what happens with the current code, because the Expired function is not cached. it evaluates against the input parameter each time it is called.

@cyrossignol your thoughts on this would be welcome.

**Comment by div72** [comment]
What if the vote durations were in block counts instead of timestamps?

**Comment by jamescowens** [comment]
That is going to be exceedingly difficult, because the block spacing is not steady enough to make that meet people's expectations.

**Comment by jamescowens** [comment]
See https://github.com/gridcoin-community/Gridcoin-Research/pull/2522/commits/09eac0fbaa920c3aa82aeabe0ed2a236444aabbc. This solves the problem.
