### ISSUE TITLE
Team RAC in Superblock/NN suddenly dropped

### ISSUE THREAD

**Issue by startailcoon** [gridcoin-community/Gridcoin-Research#241]
In last superblock today the team RAC that are included in the block has suddenly dropped. 

CSG dropped from ~300.000 to 26.000.
GPUGrid dropped from ~5.500.000 to 290.000

It seems to be over all projects. The RAC seems to have been cut by a factor of 5-8. This has affected the rewards calculation on Gridcoinstats since its stats are based on data from each BOINC projects directly. I assume this will be corrected in the next superblock.

![projectusers_gpugrid 4](https://cloud.githubusercontent.com/assets/12114550/24124664/1da0a9f0-0dc5-11e7-920c-43d65e08b050.png)
![projectusers_citizen 20science 20grid](https://cloud.githubusercontent.com/assets/12114550/24124665/1da0f892-0dc5-11e7-9562-f99e9da306f6.png)

**Update: It also seems like the wallet is rewarding based on these new Mag calculations as well**
See [this CPID](https://gridcoinstats.eu/cpid.php?a=view&id=0639771c67d7f228d327c2984b465560)

I haven't been able to look in the NN report in the wallet, but it looks like just a handful of users where included in the last Superblocks calculation. This would account for the low RAC score. See the following screenshot if miners since yesterday.

![wp_ss_20170321_0001](https://cloud.githubusercontent.com/assets/12114550/24133855/910ae212-0e00-11e7-8b36-38b231a347cd.png)

**Comment by iFoggz** [comment]
thats messed up even noticed in cpids on gridstats that a test-grcpool.com is included in it, is that normal? didnt know testnet stats were on gridcoinstats.eu and alot of info seems to be out of whack. hopefully it corrects itself or maybe it needs sum encouragement.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
a user/person/entity can name their user what ever they wish , in that list that is what it shows.
For example my cpid is associated with the user name jamezz , as that is what I set for my " user name " on my first project... you could be " swimming.pool.webcam " if you had the domain or even if you didn't or you/they could even name themselves " pool  . Testnet is separate and our testnet clients are on a different block chain at a much lower block like around/just passed 275000 and testnet doesn't use B.O.I.N.C. and is even more " dummy wallet " than an investor/bank wallet. That user name could be someone possibly but not limited to someone testing the new Open-source Gridcoin pool software https://github.com/bryhardt/grcpool or someone designing another pool under different code. Pool's are not limited to certain community members , as any Gridcoin related project or idea anything is open and anyone is more than welcome to contribute.  I hope that helps , looks like from what I read we forked on the last super-block , having multiple nodes I hope this sorts itself out without a wallet client upgrade due to forgotten code timers along with additional replacement and re-downloading of a newly signed block-chain and syncing everything up.

**Comment by iFoggz** [comment]
thanks i learn something new everyday :) and i agree lets hope for the best.

**Comment by Erkan-Yilmaz** [comment]
The [!stats](https://cryptocointalk.com/topic/50958-dpp-and-dpr/) data shows 56% cpids who are usually in there, are missing now

**Comment by tomasbrod** [comment]
I am affected. Startail's site shows crazy mag=133 but wallet show mag=0. I am on the same chain as gridcoinstats.eu (verfied now), so If there was a fork, we are all on a fork. I  believe this is caused by the neural network. Also difficulty has dropped to 5.

```
"CPID" : "46f64d69eb8c5ee9cd24178b589af83f",
"Beacon Exists" : "Yes",
"Magnitude (As of last superblock)" : 0.00000000,
"Warning" : "Your magnitude is 0 as of the last superblock: this may keep you from staking POR blocks.",
"Block Signing Test Results" : true,
"Configuration Status" : "SUCCESSFUL"

getblockhash 849323
eb93b91f8955a4efaf32a16e201c0c1a36861feee0e1ece34849d23e3b6bf523

```

**Comment by startailcoon** [comment]
**Why Gridcoinstats shows other Mag than Wallet**

The site takes the RAC from each project directly, the data that the wallet uses, and then calculates the Mag based on the projects Team RAC in the last Superblock. It doesn't know who is in the NN, it doesn't read that information since NN isn't available on Linux. The calculations of Mag are correct, but only if you are in the NN, that is why the % share is way off today. If you are not in the NN, ie your wallet sais 0 Mag, this means the CPIS was not included and the Est. Mag isn't valid that the page displays.

I will see if I can find a good way to determine or at least display a warning message in the future.

**Comment by Mercosity** [comment]
startailcoon the premise that "If you are not in the NN, ie your wallet sais 0 Mag, this means the CPIS was not included and the Est. Mag isn't valid that the page displays" certainly does not follow for me as I'm a Windows user and I can see my CPID in the NN with what should be my correct mag.

There seems to be a disconnect between the client and the NN which is causing the abberation. I'm hoping that a new superblock will sort it out, if it doesn't we are in new territory.

**Comment by bryhardt** [comment]
Just to followup on "test-grcpool.com" in the stats. That userid is primarily for the testnet pool. However, since it uses production BOINC,  I run a production GRC client with it. Therefore that node can earn some POR for using its resources instead of just earning testnet GRC.

**Comment by grctest** [comment]
User who staked the superblock: https://www.gridcoinstats.eu/cpid.php?a=view&id=0b5ef259411ec18e8dac2be0b732fd23 (Gained 8100 Mag due to this superblock).
SuperBlock in question: https://www.gridcoinstats.eu/block.php?id=848820 http://www.gridresearchcorp.com/gridcoin/?777fed9bda70e13cb7f50ce9186408a03213c42962c21e24f058409a146ba1d4

Run the following two commands and we'll all compare the results:
'execute  neuralreport' https://github.com/gridcoin/Gridcoin-Research/blob/941eb66862134292f342fd1bf0c0b0ed370874dd/src/rpcblockchain.cpp#L2167
'execute  currentneuralreport' https://github.com/gridcoin/Gridcoin-Research/blob/941eb66862134292f342fd1bf0c0b0ed370874dd/src/rpcblockchain.cpp#L2172

In between the time where the bad superblock was created and the two new superblocks were created, myself and a couple other users had completely different results for the above commands.

How secure from Sybil attack is the neuralhash voting? Considering that it's upheld by windows users only, if it's 1 vote per valid cpid present staking then it might not take many virtual machines..

**Comment by bryhardt** [comment]
neuralreport
{
"Neural Hash" : "Popularity,Percent %",
"6fdf0e63ecd93129341ad38d2163591b" : "4; 14.78%",
"903127e8ba59972bce2e1fd6503758df" : "24; 85.19%",
"Pending" : "849742",
"Superblock Age" : 2501
}

currentneuralreport
{
"Neural Hash" : "Popularity,Percent %",
"541770e136f3ec8fda759afcdd1a2dee" : "2; 2.22%",
"5e7a73e2998dd73f664c8cbf4d1c04e7" : "2; 2.93%",
"6fdf0e63ecd93129341ad38d2163591b" : "4; 4.90%",
"72b2ace21029a57cc7a19c69f8e798f3" : "33; 39.99%",
"903127e8ba59972bce2e1fd6503758df" : "24; 28.23%",
"cafc8fad8f8b2e16caabb96bfe574fef" : "16; 19.20%",
"cf906a1cae8538381e978f55308ed5be" : "2; 2.53%",
"Pending" : "849742",
"Superblock Age" : 2524
}

**Comment by ghost** [comment]
```
{
"Neural Hash" : "Popularity,Percent %",
"6fdf0e63ecd93129341ad38d2163591b" : "4; 14.78%",
"903127e8ba59972bce2e1fd6503758df" : "24; 85.19%",
"Pending" : "849742",
"Superblock Age" : 2693
}
```
```
{
"Neural Hash" : "Popularity,Percent %",
"541770e136f3ec8fda759afcdd1a2dee" : "2; 2.22%",
"5e7a73e2998dd73f664c8cbf4d1c04e7" : "2; 2.93%",
"6fdf0e63ecd93129341ad38d2163591b" : "4; 4.90%",
"72b2ace21029a57cc7a19c69f8e798f3" : "33; 39.99%",
"903127e8ba59972bce2e1fd6503758df" : "24; 28.23%",
"cafc8fad8f8b2e16caabb96bfe574fef" : "16; 19.20%",
"cf906a1cae8538381e978f55308ed5be" : "2; 2.53%",
"Pending" : "849742",
"Superblock Age" : 2734
}
```

**Comment by startailcoon** [comment]
```
[
        {
            "Neural Hash" : "Popularity,Percent %",
            "6fdf0e63ecd93129341ad38d2163591b" : "4; 14.78%",
            "903127e8ba59972bce2e1fd6503758df" : "24; 85.19%",
            "Pending" : "849742",
            "Superblock Age" : 2666
        }
    ]
```

 ```
[
        {
            "Neural Hash" : "Popularity,Percent %",
            "541770e136f3ec8fda759afcdd1a2dee" : "2; 2.22%",
            "5e7a73e2998dd73f664c8cbf4d1c04e7" : "2; 2.93%",
            "6fdf0e63ecd93129341ad38d2163591b" : "4; 4.90%",
            "72b2ace21029a57cc7a19c69f8e798f3" : "33; 39.99%",
            "903127e8ba59972bce2e1fd6503758df" : "24; 28.23%",
            "cafc8fad8f8b2e16caabb96bfe574fef" : "16; 19.20%",
            "cf906a1cae8538381e978f55308ed5be" : "2; 2.53%",
            "Pending" : "849742",
            "Superblock Age" : 2701
        }
    ]

```

**Comment by philipswift** [comment]
This seems the right time to look at anti-Sybil. The cycling of nodes and the startup calculation mentioned here http://bitcoin.stackexchange.com/questions/42177/can-we-make-sybil-attacks-virtually-impossible
looks interesting. A vote for promoting PoW.

**Comment by denravonska** [comment]
This can be considered a result of the previous consensus difficulties.
