### ISSUE TITLE
GUI: Suggestions for installation

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2434]
**Describe the Feature Request**
I was recently making a "how to install the gridcoin wallet" video as a guide for newbies, and I was struck by a few things that might improve ease of use. This was while installing the latest release on Windows 10.

**Describe Preferred Solution**

1. In the installer, one must click "next" a few times. The only real choice it gives the user is a non-standard storage directory for the blockchain. On page one of the installer it should have a checkbox for "configure advanced settings" and if not checked by the user, their first click in the installer should install the Gridcoin wallet with all default settings. Otherwise, their first click takes them to the storage location customization screen. 
2. Once installed, it is not immediately clear to me as a user that I must wait for the wallet to sync before sending/receiving transactions. Two proposed solutions for this: solution 1 would be a splash screen that shows before the wallet loads (after installation) showing the sync status and saying the wallet must be synced before use. If the user clicks the splash screen, it goes away and loads the main wallet. AND/OR a more visible warning taking up more of the wallet (perhaps red or caution tape pattern) saying the wallet is not in sync, that the user must wait for it to sync, and showing current sync status.
3. Final point, and this is a very small one. After installation, the wallet immediately hides to the system tray instead of opening. As a user, my instinct would be to think that the install was completed and once again go open it from the start menu, but this is not needed as it's already open. If this is some function of the installer that can't be changed, a warning about it at the end of the installer would be nice.

I know the devs work tirelessly on the wallet and these may seem like nitpicky things to point out, and obviously they are not top priority, but they do impact usability.

**Comment by RoboticMind** [comment]
1. I'm not sure that this can be changed without a fair amount of work. There's no obvious way I can see to stop the installer from doing all that with the installer tool that Gridcoin uses

2. There is a red out-of-sync badge in the upper left, however, a popup explanation of what that means might not be a bad idea. 

3. The wallet doesn't dismiss to the system tray, it just doesn't show up on the taskbar until it's loaded. That might be worth changing since it's a bit confusing. See #1483. Might be worth re-opening that issue in my opinion
