### ISSUE TITLE
Researchers Reward Pays too much

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#245]
Wallet was out of sync even with good connectivity so I checked the logs and found this.

`ERROR: CheckBlock[ResearchAge] : Researchers Reward Pays too much.`

[grc-error001.txt](https://github.com/gridcoin/Gridcoin-Research/files/865395/grc-error001.txt)

`ERROR: Bad CPID : height 851463,000000, CPID 5fafbe6930402bb3d4a46897287ab2c3`

[grc-error002.txt](https://github.com/gridcoin/Gridcoin-Research/files/865491/grc-error002.txt)

v3.5.8.6-g-research-317 941eb66862134292f342fd1bf0c0b0ed370874dd

**Comment by iFoggz** [comment]
ya saw the same error while figuring out list staking etc since i bought sum grc to be able to move to solo and checked logs make sure i am not preventing myself from making investor stakes and i noticed same error and i was like interesting and then an email from github with your post. funny how things work lol

**Comment by startailcoon** [comment]
My Dev server are having issues since block 851463. 

`03/23/17 16:38:41  Received block 2abf8dedf9e55a9ae6a3cae83d3106180f90244f8fa3c3a515d8885f2626956f; ERROR: Bad CPID : height 851463.000000, CPID 0390450eff5f5cd6d7a7d95a6d898d8d, cpidv2 0390450eff5f5cd6d7a7d95a6d898d8dc66c389b96333e679899c9c94291cc34c74169379b6498666796353a9c3bc63e6573666a637041686e792f6566, LBH 59411359d6fee070780ebc49ad7c619503e0d4af66fa45f6d626f029a239c73b, Bad Hashboinc 0390450eff5f5cd6d7a7d95a6d898d8d<|><|><|>0<|>0.00000<|>0<|><|><|>0<|>0<|>v3.5.8.6-g-research<|>8.06<|>1490279648<|>0<|>0390450eff5f5cd6d7a7d95a6d898d8dc66c389b96333e679899c9c94291cc34c74169379b6498666796353a9c3bc63e6573666a637041686e792f6566<|>580<|>S8ytydsTx4o1zJgMMs2wAKGUgRq3NB95z1<|>59411359d6fee070780ebc49ad7c619503e0d4af66fa45f6d626f029a239c73b<|>3.18<|><|><|><|><|>8.06<|>0.055556<|>0.250000<|>580.00<|>1de76f86e88864f9381885370b81c94686a0c5bd03ca5fb77e40de59dbcf5fb2<|>87142603469c1f27de06b8898856bcc2<|>04b097853d156578abde5ef93ee16220574bc473cfdf32e915b6b7fad45cf3c3d063fc9c6f56af85ac1cac1b3ea883f92d553a83fc33b4b27293408669b89a69d9<|>MEQCIFKzTJNEBWZvZe0Hu1pUStPWH2og26HgMBPMDLYkb/M3AiBA2vfRVWi2slw83jf7uZ30Lgph4elDd05dzku/AL26iA==
03/23/17 16:38:41 ERROR: ProcessBlock() : CheckBlock FAILED`

My main server for Gridcoinstats did not fail on this block and has this CPID as staker. The wallet on my dev server seems to be unable to process past this block because this error.

**Comment by denravonska** [comment]
@startailcoon Is your dev server running the dev branch? If so, which commit?

**Comment by startailcoon** [comment]
My dev server is running the main stable v3.5.8.6-g-research

**Comment by tomasbrod** [comment]
After restore from previous filesystem snapshot, everything seems running as usual. That error happened to me few times already, but I never bothered.

**Comment by startailcoon** [comment]
This should recover itself. The ChecBlock fails. After a while the wallet runs "getblocks .... limit 1000" for something. Pasting some more debug log...

[debug.txt](https://github.com/gridcoin/Gridcoin-Research/files/865958/debug.txt)

**Comment by iFoggz** [comment]
so to add to this my wallet is as investor and no email setup in config so just investor wallet. ive been seeing this checkblock failed for multipul cpids over the course of hours. each time it happens my wallet goes out of sync and takes along time to come back and then catch up... 
edit: my linux latest client

**Comment by grctest** [comment]
This issue has affected my windows client, but my linux clients are running without issue.

**Comment by philipswift** [comment]
Same with Windows test clients, seems to get to about 20th or 21st March then gets confused

**Comment by tomasbrod** [comment]
Happened again. Unfortunately I don't have the full logs. I atttach part of. And fixed itself after few minutes.
[grc-error003.txt](https://github.com/gridcoin/Gridcoin-Research/files/914144/grc-error003.txt)

**Comment by iFoggz** [comment]
yes i have been seeing this on and off but it recovers as it should but can take up to  30 minutes in some cases for me. it does the bootup..b..b. again and goes fine. I have mentioned it to ravon before

**Comment by denravonska** [comment]
I think this is because the tally hasn't run. I got this when receiving a large number of blocks but before the tally thread had started. We need to a) run the tally before doing anything else, and b) maybe consider running it on each received block.

**Comment by iFoggz** [comment]
i often get this during my nodes runnings. its always one node that gets stuck on this not the other. one accepts it as its correct while other has not. there discrepancies in calculations and they may of been preexisting as we allow a 25% buffer zone to begin with and 5 times for PPD seems like more compensation on the issue. ive done the manual calculations on a few of these and they are in fact paid correctly.

**Comment by tomasbrod** [comment]
Seems to happen less often nowadays. Almost never on testnet, but I have not searched the logs too much.
On the other hand, on prod, magnitude > neural error was quite common.

**Comment by tomasbrod** [comment]
#922 hopefully fixed
