### ISSUE TITLE
Create RPC Command to Run Diagnostics 

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2477]
# Feature Request

**Describe the Feature Request**
Currently, the diagnostics mainly only exists in the GUI. While the status of some of the individual components of the diagnostics can be seen in different commands, it's more work to find them and some don't exist in other commands. 

**Describe Preferred Solution**
Adding an RPC command that gives the results of the same diagnostics that exist for the GUI

**Comment by jamescowens** [comment]
This is a good idea but is not a trivial task. The diagnostics are written currently on the GUI side and the code needs to be refactored to run in the core, with the RPC and GUI consuming the results rather than the code being in the GUI itself. Some of the diagnostics tests, such as the fallback to ntp checking for time and verifying the outbound TCP connections (which needs to be reworked anyway), use Qt specific functions and will have to be rewritten to run in the core.
