### ISSUE TITLE
Add RPC/command line call to rewind block chain

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#250]
After all these issues with the chain a lot of people have been doing a _lot_ of chain redownloading and resyncing to try to catch up from a bad state. It could maybe be a good idea to add an RPC command to rewind the user's chain to a certain hash. That way they could maybe get off a fork and onto the main chain without going through the unnecessary hassle of downloading a completely new chain.

**Comment by tomasbrod** [comment]
I am Working on it.
Available as commit 9c48ac2, which should be cherry-picked.

**Comment by denravonska** [comment]
@tomas Nice work. You mentioned that you could rewind but not process any blocks after. Did you sort that out?

**Comment by tomasbrod** [comment]
This new reorganize command is of limited functionality. You can force a reorganize to any block by hash that is already in block index. You must have the output that staked the new block in chain you reorganized to, in order to process it. To overcome this limitation you can gradually reorganize to the highest block in your index and let it download the rest. Orphan blocks are not added to index. Blocks already in index won't be automatically processed, unless a higher block is received. This command won't help you with corrupted transaction/block index database.

**Comment by denravonska** [comment]
Sort of fixed by @tomasbrod with the "reorganize" command.
