### ISSUE TITLE
Beacon renewal seems to need the wallet to be restarted

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Research#253]
I tried the auto send beacon when the beacon expired. It succesfully sent the beacon but "execute beaconstatus" reported conflicting keys in the config file. The config file holds the new keys as expected. Restarting the wallet resolved the issue. So I assume that the wallet updates the config file after updating the beacon but still holds the old keys in memory.

If anyone can confirm this behaviour please reply.

**Comment by Vortac2** [comment]
I had the same experience. Sent a beacon, got conflicting keys error. Did a repairwallet (because some coins were missing) and restarted the client. Apparently the latter resolved the issue.

**Comment by iFoggz** [comment]
edited

i had an issue on the 25th may be unrelated but during the chaos one beacon never made it and then on 26th i had to send a second one and it said public keys didnt match which they did so it failed the sign test. it recommened beacon deletion however i figured out it was just an error with signing test over its own confusion. i put the bad key from beacon status in and restarted and it failed and passed the signing test part and then put the right one back in and restarted and it was successful. since then ive had no issues and ive staked blocks without an issue. i think the test signing had a key from failed beacon maybe somewhere but im no expert but needless to say it worked for whatever reason and i put a request to cancel my beacon deletion. ive staked por blocks twice so far in 2 days.

**Comment by denravonska** [comment]
It seems like [MemorizeMessage](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/main.cpp#L9850) isn't called from [AddMessage](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/rpcblockchain.cpp#L4681) which causes the application to have the old keys in cache. Possibly.

Edit: On second thought, it should probably be memorized when an incoming block is received.

**Comment by denravonska** [comment]
I think I found the cause of this: https://github.com/gridcoin/Gridcoin-Research/blob/master/src/util.cpp#L1212
`ReadConfigFile` is called after updating the priv/pub keys are updated via [WriteKey](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/main.cpp#L5729). If a key is in memory (which it is), that check prevents it from being overwritten and the old one will remain in use.

Edit: I'm not sure what the correct solution is though. Maybe deleting the keys before storing them and call keys "unoverridable" from command line.

**Comment by iFoggz** [comment]
we sitll need to address this. this may still cause issues on a new beacon as well that uses new keys or someone who had problems advertising before hand and beacon not in chain but keys in the config file. i been looking at it trying to figure out the best way while only allow the instance of modifying the keys in memory when a successful beacon occurs with new keypair if a keypair that does not match is in memory.

**Comment by iFoggz** [comment]
PR #381 closes this. commit 23ade72 solves this, and commit 2c74ac8 modifies previous commit to conform to recent new changes in advertisebeacon.
