### ISSUE TITLE
Unreadable text in the about and download blocks window

### ISSUE THREAD

**Issue by matthew11** [gridcoin-community/Gridcoin-Research#255]
These dialog windows has a very light background images, and the text color is also white rendering the text unreadable. (See the attached image)

I'm using a dark theme, so I think this causes the problem. (Setting to a light theme solves, but I do not like light themes) Anyway, if the background is set by the application, the text color should also be preset accordingly.
![screenshot_20170329_011030](https://cloud.githubusercontent.com/assets/4918748/24431783/5440c0ee-141e-11e7-8826-ffc4c42e0980.png)
![screenshot_20170329_011112](https://cloud.githubusercontent.com/assets/4918748/24431782/5440ac80-141e-11e7-9734-3ae402bc3a51.png)

Some information regarding my system:
Ubuntu 16.10 x64 (KDE DE "Breeze Dark" theme)
gridcoin-qt "version" : "v3.5.8.7-g-research" from gridcoin-daily PPA

**Comment by denravonska** [comment]
@skcin Can you have a look t it?

**Comment by skcin** [comment]
@matthew11 the problems with dark color schemes are known. Most of it is fixed in the development branch. Until the changes from the development branch get merged in we have to live with these issues. You can always try the development branch if you compile it yourself but keep in mind that it is not fully tested and you might run into bugs. The safest way is to just wait until the changes are released.
The gui is under active development, you can take a look at #233 for the current discussion. 

I think this issue can be closed since it is already solved in the development branch.

**Comment by denravonska** [comment]
Sweet, thanks @skcin.

**Comment by matthew11** [comment]
Good news, thank you!
