### ISSUE TITLE
Incorrect output of fees_to_staker for rpc getblock/showblock

### ISSUE THREAD

**Issue by iFoggz** [gridcoin-community/Gridcoin-Research#2566]
# Bug Report

**Current behavior**
fees_to_staker show erroneous outputs.

**Expected behavior**
fees_to_staker should be zero unless the staker is receiving fees.

**Steps to reproduce:**
For instance on MainNet:
showblock 2656056:
however showblock/getblock shows "fees_to_staker": 18.02401069

For instance on TestNet:
showblock 1968886:
however showblock/getblock shows "fees_to_staker": 0.00000320

**Screenshots**
Not applicable

**Gridcoin version**
5.4.0.0 release .deb

**Machine specs**
- OS: Ubuntu 22.04.01
- CPU: AMD FX-8800P Radeon R7
- RAM: 16GB
- Disk size: 1TB
- Disk Type (HD/SSD): SSD

**Extra information**
- Low impact bug via rpc output (visual bug)
- Likely leisure fix

**Comment by jamescowens** [comment]
Interesting. We need to track this down. I may do a non-milestone leisure release even before the hardfork point to fix a few problems that have cropped up. All in all so far this was a pretty smooth release given the changes.

**Comment by jamescowens** [comment]
@ifoggz, do you want to take a spin at it?

**Comment by iFoggz** [comment]
i should have some time tomorrow to do so just got home a bit ago and kids have visit with there older sister who in foster care. i may find time tonight as wel.

**Comment by iFoggz** [comment]
i have updated the report. fees_to_staker/fees_collected not really related. so corrected my report on it.

**Comment by jamescowens** [comment]
No big big rush I think. But if we can get a fix pinned by the end of the weekend that would be good.

**Comment by jamescowens** [comment]
The field is misnamed for one.... It should be called mrc_fees_to_staker rather than fees_to_staker, because it is supposed to tally the total fees to the staker from all mrc's in the claim. It is not supposed to include standard transaction fees that are also to the staker. This should be zero for all blocks with no mrcs (which also means any block < v12). Unfortunately I forgot to add a 0 initialzer for the requisite member variable, claim.m_mrc_fees_to_staker. For blocks with mrc's this doesn't matter, because it is assigned the correct value, but for all non-mrc blocks (including all < v12 blocks in 5.4.0.0), it assumes a random value. I will put up a small PR to rename the field so that it is not confusing, and also initialize the field to zero in the claim constructor.
