### ISSUE TITLE
Create a Folding@Home Adapter for Gridcoin

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2568]
**Describe the Feature Request**
Create a Folding@Home adapter for Gridcoin. Such an adapter would need to scrape Folding@Home data and publish it using the BOINC statistics format so that it can be ingested by the Gridcoin scrapers. This way, Gridcoin can reward Folding@Home contributions. I am creating this as a separate issue so that bounties may be added to it. The bounty will be considered "complete" when a pull request accepted by a Gridcoin dev marks this issue as completed.

**Bounty Information**
To contribute to this bounty via PayPal, go to https://app.bountysource.com/issues/110771760-create-a-folding-home-adapter-for-gridcoin

**Describe Preferred Solution**

- The Folding@Home adapter should be published as a Docker container or VirtualBox image so that it can be deployed with anybody who has access to hosting (in case you do not wish to host it or whoever hosts it decides to stop hosting it). 
- You may scrape user data in whatever way makes the most sense. Folding@home offers an API though additional functionality may need to be added, and you may need to coordinate with them, IIRC they have indicated a willingness to help open their data up if need be.
- Since Folding@Home does not use CPIDs, you will need a mechanism for a beaconed Gridcoin wallet to verify that a Folding@home account is theirs, and this mechanism must not rely on any changes to the wallet. This will likely require user registration at your service. Such a service will require a "forgot password" mechanism and a basic mechanism (such as captcha) to prevent form spam.
- The adapter should calculate the user's average credit into a RAC much like BOINC does, and should publish user statistics in the same format/location as BOINC does so that Gridcoin's scrapers can access it and use it like any other BOINC project.
- Scraping/publishing of stats should be done at a minimum frequency of once per day and a maximum frequency of once per hour
- The adapter should also publish "available work data" the same way BOINC does, so that the project can be automatically greylisted if Folding@home runs out of work units.
- The adapter should allow a user to change/delete their user record or prevent further publishing of their user data to be compliant with GDPR.
- The adapter may not charge any fee for its use and must be published under any eligible OSS license from https://opensource.org/licenses. All copyrights to the adapter will be transferred to the Gridcoin devs.

** Related Issues **
https://github.com/gridcoin-community/Gridcoin-Research/issues/782

**Comment by barton2526** [comment]
Suggestion: Do not force the creator to use MIT licensing. Instead just allow any FOSS license (https://opensource.org/licenses).

**Comment by makeasnek** [comment]
> Suggestion: Do not force the creator to use MIT licensing. Instead just allow any FOSS license (https://opensource.org/licenses).

Done.

**Comment by jamescowens** [comment]
Also the adapter should update ALL registered F@H user statistics at a minimum frequency of once per day and a maximum frequency of once per hour. (The minimum is required by the whitelisting rules. The maximum frequency is to control the rate of change of the statistics hash so that the scrapers can achieve a stable convergence.)

**Comment by div72** [comment]
Suggestions:
- This is better suited for gridcoin-community/Gridcoin-Tasks as the bridge will not be part of the wallet.
- "All copyrights to the adapter will be transferred to the Gridcoin devs.", I **really really** dislike this. Similarly some open-source projects(mostly from big corporations but some individuals also do) have similar clauses in CLAs. The copyright of the code should stay in the hands of the author, not be taken when contributing. Anything other than a request for a developer certificate of origin is too much in my opinion.

**Comment by div72** [comment]
That being said, I do have a Folding@Home bridge in my hands that needs testing. It does differ in a few points though:
- Instead of a full bridge that runs on docker, it is just a systemd service that translates statistics and calculates RAC. It needs a web server like nginx to actually simulate a BOINC project.
- Folding@Home does offer an API where you can get the stats of an user with their passkey. Since storing and asking for the passkey is problematic and even if daily making an API request for each user can un-intentionally DoS F@H servers, I decided to use the bulk data export instead. That does come with it's own caveats but I'll refer to the comments in the fath2boinc.v file in the source code I linked below for the mitigations.
- I dislike forcing the users to register at a specific service and give/handling passwords/emails etc. so similar to other coins, I implemented a system which uses the name in order to verify the ownership of the work. The format is `<name>_GRC_<cpid>`.
- Work data is not translated (yet). It should not be hard though as the assignment servers do give the data.

Here's the link to the source: https://github.com/div72/fath2boinc
Link to the adapter: https://foldingathome.div72.xyz

**Comment by makeasnek** [comment]
> Also the adapter should update ALL registered F@H user statistics at a minimum frequency of once per day and a maximum frequency of once per hour. (The minimum is required by the whitelisting rules. The maximum frequency is to control the rate of change of the statistics hash so that the scrapers can achieve a stable convergence.)

Good point, added

**Comment by makeasnek** [comment]
> Suggestions:
> 
>     * This is better suited for gridcoin-community/Gridcoin-Tasks as the bridge will not be part of the wallet.
> 
>     * "All copyrights to the adapter will be transferred to the Gridcoin devs.", I **really really** dislike this. Similarly some open-source projects(mostly from big corporations but some individuals also do) have similar clauses in CLAs. The copyright of the code should stay in the hands of the author, not be taken when contributing. Anything other than a request for a developer certificate of origin is too much in my opinion.

The reason for the license requirement is that this functionality, once created, should be property of the "Gridcoin community" so that if the person hosting this service decides to stop doing so, somebody else can take the reigns. Otherwise, this functionality remains hostage of the original author. Unless I am mis-understanding your objection? Licensing is not my strong suit.

**Comment by jamescowens** [comment]
@div72, we don't have to have something as strong as all copyrights transferred to the community, but then we must ensure that the open source license chosen should allow someone else to pick up the baton should the original author disappear. The author will be compensated for the adapter by the bounty... that is effectively a work for hire.

**Comment by jamescowens** [comment]
I specifically do NOT want to get into the problems that Minecraft had with Bukkit.

**Comment by jamescowens** [comment]
I actually disagree with @barton2526 and believe the MIT license, which is the most permissive, should be chosen, as it aligns with  the core wallet. It also eliminates the concern about someone else picking up the baton if the original author should disappear.

**Comment by jamescowens** [comment]
There is an official whitelisting poll on mainnet now. See https://www.reddit.com/r/gridcoin/comments/yzitb4/foldinghome_adapter_whitelisting/

**Comment by jamescowens** [comment]
@makeasnek The bounty needs to be paid to @div72 and this closed out.

**Comment by makeasnek** [comment]
@div72 Go to https://app.bountysource.com/issues/110771760-create-a-folding-home-adapter-for-gridcoin to claim the bounty. That should initiate an e-mail to the bounty backers, who will vote to award you the bounty :). The claim process takes two weeks and iirc bountysource will ask you for some identifying information as well. Lmk if you hit any snags.

**Comment by makeasnek** [comment]
Also, a requirement of the bounty is that the code be publicly available and licensed under an OSS license, has that been done?

**Comment by Pythonix** [comment]
> Also, a requirement of the bounty is that the code be publicly available and licensed under an OSS license, has that been done?

Yes, the code can be found here: https://github.com/div72/fath2boinc. But IMHO it should be moved to the gridcoin community organiaztion.

**Comment by div72** [comment]
> > Also, a requirement of the bounty is that the code be publicly available and licensed under an OSS license, has that been done?
> 
> Yes, the code can be found here: https://github.com/div72/fath2boinc. But IMHO it should be moved to the gridcoin community organiaztion.

I'll need Jim's cooperation for that.



> @div72 Go to https://app.bountysource.com/issues/110771760-create-a-folding-home-adapter-for-gridcoin to claim the bounty. That should initiate an e-mail to the bounty backers, who will vote to award you the bounty :). The claim process takes two weeks and iirc bountysource will ask you for some identifying information as well. Lmk if you hit any snags.

Bountysource really does not like my e-mails. I tried two different providers but neither got the verification email.(I checked the spam of course.)

**Comment by makeasnek** [comment]
@div72 unfortunately bountysource's email problems are a little out of scope of what we can solve, try a third e-mail, something reliable like a gmail address? Make a support ticket w them?

**Comment by makeasnek** [comment]
If that doesn't work lmk and I can send them an e-mail as well

**Comment by jamescowens** [comment]
@div72 do you want me to make a new repo for you? Then you can do an initial commit into it.

**Comment by philipswift** [comment]
Re: FAH adapter & '_**NOT a BOINC project, see crunching guides for how to setup account**_'

The current wallet (5.4.1 Win64) is showing FAH as a valid project (researcher>beacon configuration wizard>projects>name) that could be assumed to be a BOINC project. This is because the 'eligible' column says 'not attached' when FAH is not an accepted project (if 'attached' you get a black tick in green circle). Possibly 'not attached' infers BOINC. 
The last sentence in the GRC website description (gridcoin.us>guides>project whitelist) or https://gridcoin.us/guides/whitelist.htm makes it clear it is not a BOINC project and refers the reader to 'crunching guides' for setup. I cannot find any guides within gridcoin.us or FAH that mention FAH setup, but there is, obviously, some mention in Folding Forum [https://foldingforum.org/search.php?keywords=gridcoin](url)
Maybe the crunching guides can refer to gridcoin.us/community/discord

This message will self destruct in 30 days.

**Comment by jamescowens** [comment]
@philipswift for the "not attached" comment, please see https://github.com/gridcoin-community/Gridcoin-Research/pull/2625.

**Comment by jamescowens** [comment]
F@H specific instructions in the guides are being worked on, but not up yet.

**Comment by jamescowens** [comment]
@philipswift ...

https://github.com/gridcoin-community/Gridcoin-Site/pull/356

**Comment by makeasnek** [comment]
@div72 any luck setting up an account at bountysource? I'd like to see you get paid for the F@H adapter

**Comment by jamescowens** [comment]
I also am ready to transfer the adapter to a repo here.

**Comment by div72** [comment]
@jamescowens I initiated a repository transfer, you should receive an e-mail in a bit.

@makeasnek Sent an e-mail to support@bountysource.zendesk.com 5 days ago, no response so far. Trying the contact form at the website now.

**Comment by jamescowens** [comment]
Repo transfer was successful.

**Comment by jamescowens** [comment]
You are currently the only one with write access to it.

**Comment by div72** [comment]
Successfully created a BountySource account. Closing the issue in order to redeem the bounty.
