### ISSUE TITLE
OpenAlias support

### ISSUE THREAD

**Issue by CyberTailor** [gridcoin-community/Gridcoin-Research#2630]
# Feature Request

**Describe the Feature Request**
Accept domain names in addition to wallet addresses in the official wallet.

**Additional Context**
1. https://openalias.org

**Comment by jamescowens** [comment]
I really strongly dislike this. You are injecting a third party (DNS) that is partially, or essentially, completely centralized into the address resolution to know where to send money, and I guarantee you that people will not take the time to check the actual address to see if it is correct. That is the whole point of this to begin with... to dispense with those pesky addresses that are the only link to the public/private key pair of the party to which you are trying to send funds. This is not a good thing IMHO.

...


There are only a handful of DNSCrypt compatible resolvers worldwide, and fewer still that additionally support DNSSEC validation, support Namecoin resolution, and don't log DNS requests. Additional DNS resolvers that meet these criteria will be launched and operated by OpenAlias and by contributors in the coming months. In order to make your life easier, you can get a list of available resolvers that meet all these criteria by fetching the TXT records from any of the following domains:

resolvers.openalias.org
resolvers.openalias.ch
resolvers.openalias.se
resolvers.openalias.li

...

**Comment by jamescowens** [comment]
There are four name resolvers across the entire world that you can use now, and they all are operated by the same org.

**Comment by div72** [comment]
@jamescowens The data is stored in TXT records for DNS which can be accessed by any DNS resolver, see:

```
div72@home ~ $ dig @1.1.1.1 TXT openalias.org

; <<>> DiG 9.18.10 <<>> @1.1.1.1 TXT openalias.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17564
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;openalias.org.                 IN      TXT

;; ANSWER SECTION:
openalias.org.          300     IN      TXT     "v=spf1 mx ptr a:67-20-77-24.unifiedlayer.com include:_spf.google.com ~all"
openalias.org.          300     IN      TXT     "oa1:btc recipient_address=1FhnVJi2V1k4MqXm2nHoEbY5LV7FPai7bb; recipient_name=Monero Development; tx_description=Donation to Monero Core Team;"
openalias.org.          300     IN      TXT     "oa1:xmr recipient_address=46BeWrHpwXmHDpDEUmZBWZfoQpdc6HaERCNmx1pEYL2rAcuwufPN9rXHHtyUA4QVy66qeFQkn6sfK8aHYjA3jk3o1Bv16em; recipient_name=Monero Development; tx_description=Donation to Monero Core Team;"

;; Query time: 222 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Tue Jan 17 00:13:11 +03 2023
;; MSG SIZE  rcvd: 497
```

Those DNS servers are only mentioned because they support the requirements in the paragraph you listed.

But I absolutely agree with your point otherwise. I am surprised to see Monero not adapting an in-chain solution and adopting this instead.

**Comment by jamescowens** [comment]
That's even worse IMHO...
