### ISSUE TITLE
Idea: Reminder for polls

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2648]
**Describe the Feature Request**
If a user has not voted in a poll, there should be reminder notifications made. Perhaps one the day before and one the day of the poll's end date. A way for the user to indicate "stop notifying me about this poll" would be nice as well, as well as a "turn off all poll notifications" in case the user really doesn't like notifications (or has a low enough balance in a wallet to never care about voting with it). There are certainly users who dismiss the initial notification and indeed would have interest in voting but simply forget.

A lower threshold on the poll's current achieved AVW or yes/no ratio could be included so that "spam" polls don't result in reminders. Though I'm not sure this is ideal as it essentially encourages users to vote a certain way. 

My understanding of the current polling architecture is that getting and updating poll information in wallet can be a bit computationally or otherwise intensive, so I'm not sure how easy a feature like this would be to code or to run on a user's machine. 

On the other hand, since this is not a particularly important feature worthy of dev time, but may be rather simple in terms of how many changes need to be made, perhaps it is a good candidate for a bug bounty.

**Additional Context**
The more engagement we can have via user polling the better. 

- Every time a user votes in a poll, they feel they are an important part of the network, and it increases their emotional stake. 
- Being reminded that Gridcoin exists will increase engagement with Gridcoin in general, not just in polls
- Poll responses are as transactions which reward stakers with a small amount of fees, lowering the total needed CBR/inflation rate. The flipside of this is that it increases the cost of running a "full node" because poll responses take up blockchain space.
- More poll responses make polls more likely to pass
- Other apps that you might have, for example, on your phone will of course notify you to death because notifications increase engagement

**Comment by jamescowens** [comment]
I hate the term "engagement," because it sounds too Facebook like. That being said, the idea of doing reminders for people to vote is a good one.

Some technical considerations and other comments on the above:

1. The wallet has, in memory, a map of the polls in the poll registry going back to the lookback limit (currently 180 days), and for each poll, there is a vector of linked votes that came in via the contract handlers. The poll contracts are validated upon receipt, while the HASHES (txids) of the vote contracts are simply linked to the polls and no other work is done on them until the poll results are tabulated, which is currently done on demand.
2. A while back I added the concept of "IsMine" to the VoteCandidate object. This is pretty much the lowest level primitive that has the concept of whether a person voted or not. This is propagated up the call chain to eventually end up in the poll tab on the GUI to indicate the details of the self-vote when the vote(s) are tabulated for poll(s) on demand. Note that the VoteCandidate object can be immediately constructed from a transaction containing a vote contract, and calling the IsMine method will indicate whether this vote has been cast by the current walletholder. We can do this much work on vote contract receipt instead of delaying it and then know when a walletholder has voted. What we don't know with this is whether the vote was actually valid or not, or any of the details. You don't know whether the vote was actually valid until the vote (attestation) is resolved. But... perhaps this is good enough for the purposes here. We can know the IsMine vote status of the walletholder for each poll in the registry that is not expired, and from the transaction times we know the time the vote was cast (or not). We also from the poll registry also know the expiration time of the poll.
3. Given the above, we can use the wallet scheduler to drive notifications. We need to make some decisions about the method of notification. Normally notifications are made using the standard notification API's that are wired in for the operating system. This also means they can be suppressed by config in the op sys (i.e. silence notifications). Currently standard notifications can also be turned off at the wallet level by GUI option. Using the standard notification API is less intrusive, but also decreases the chance of the walletholder noticing that the poll is about to expire when they haven't voted yet. The alternative is to use some sort of dialog box, i.e. nag screen. I am really not in favor of that, because while it could be better at informing people about expiring polls where they haven't voted, it could be really irritating for some. (Me included... ) I think we also have to be careful about the rules for repeat notification. Two or three times at key times before expiration is good enough...

**Comment by jamescowens** [comment]
This MIGHT be simple enough for a bounty type approach. The developer doing the PR will have to have a pretty good working knowledge of how the polling system is put together, and also how the CScheduler class and the main static global scheduler object is implemented and how new items to schedule can be added to that.
