### ISSUE TITLE
Bundling dependencies considered harmful (BerkeleyDB)

### ISSUE THREAD

**Issue by nethershaw** [gridcoin-community/Gridcoin-Research#2663]
As a Gentoo user and (erstwhile) package maintainer, I must ask that you _please_ consider not bundling BerkeleyDB -- or any dependency, ever -- into your source tree.

Distribution and package maintainers far more experienced and patient than I have already documented why doing this is a Bad Idea:

- https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
- https://fedoraproject.org/wiki/Bundled_Libraries

It is correct to drop support for BDB 4, but pinning the BDB dependency to version 5.3 should be the province of packaging, not your source code. RPM and DEB both support versioned dependencies (e.g., `Requires: libdb >= 5.3`), so I am perplexed as to why you did not simply take advantage of those.

Once upon a time, I thought I might attempt to create and maintain a Gentoo ebuild for Gridcoin. However, I suffer from severe depression and no longer have the bandwidth to manage expectations between a distribution and a vendor, so I pulled that repository. Had I the spoons to have noticed Gridcoin's intentions to bundle BDB three or more months ago, I would have thrown a flag on the play.

I continue to maintain that ebuild for my own personal use because I want Gridcoin and I want Gridcoin installed _correctly,_ according to my distribution's best standards and practices. For my part, this means that if I were a real Gentoo developer and want my ebuild accepted, my ebuild _must_ now include a patch that effectively reverts 4d9a9587ff817b1e2715935e1456fdfe05ffef89 to prevent inconsistencies with the system BDB installation. In Gentoo, Berkeley DB is considered to be a base system package and it will not be removed from the Portage tree while significant packages still depend on it. It is **highly unlikely** that the BDB binary packages will become unavailable to users of binary distributions any time in the near future because Yum, DNF, and Apt all depend on BDB.

If you absolutely believe bundling BDB is justified and that there is absolutely no solution in RPM/DEB packaging features to ensure the correct dependency is present in a less disruptive way, I must ask instead that you introduce a build-time option for compiling against system BDB instead of the bundled library (enforcing checks for version >= 5.3 as necessary) _and_ pledge never to modify the bundled BDB library.

This way at least it won't be necessary to keep porting forward the 4d9a9587ff817b1e2715935e1456fdfe05ffef89 revert patch to every new release _ad infinitum._

I'm not likely to have the stamina to follow up on this, so please accept the wisdom of the distribution overlords if not my own small-time whinging. Thank you.

**Comment by barton2526** [comment]
Send this report to Bitcoin then. We are just following their lead...

**Comment by jamescowens** [comment]
@nethershaw, I will politely disagree with you on this. We have to support MANY different architectures, including Windows, where there is no bdb at all. Prior to moving bdb to the source tree, it was downloaded in the "depends" builds among other packages to provide a "miniature operating system" to support the Windows compilation. Linux users can also use the depends build to reduce dependencies on the system package versions, or get Gridcoin to run on an outdated Linux distribution. although using the depends build is discouraged on Linux.

The decision to move bdb 5.3 into our source tree was carefully considered. Arch recently moved to bdb 6+, which is not compatible with bdb 5.3 or 4.8 and involves more extensive changes, in addition to arguably license issues due to Oracle. One of the important goals is to insure portability of the wallet.dat file across any Gridcoin architecture. This is assured by running a consistent version of the bdb database for the wallet.

And as to unavailability of bdb versions, 4.8 is already not available on some (Debian/Ubuntu and Arch), the default version on others (Fedora and OpenSUSE).

Many other cryptocurrency native wallets have already gone to flatpacks or similar packaging to eliminate the hassle, which is similar, but even more heavyweight than the depends build we offer for dependency decoupling.

I would **strongly** advise you NOT to revert the bdb merge commit. Using the system bdb if it is other than 4.8 or 5.3 is not tested and cannot be assured to work properly in the production wallet.

Rest assured we do not make the decision to bundle lightly. The dependencies that we are bundling are the minimum to maintain compatibility with Bitcoin Core and also achieve our stated goals.

I can ask @div72 if he will put an option back in to use the system bdb instead of the in tree version. The decision will be up to him.

I will also tell you that we will not support problems stemming from using a version of bdb that has not been tested by us.

Thanks!

**Comment by jamescowens** [comment]
I have also changed this to an enhancement from a bug, since this is not a bug.

**Comment by Tahvok** [comment]
@jamescowens Archlinux still has bdb 5.3 https://archlinux.org/packages/core/x86_64/db5.3/
Arch basically has 2 versions now.

I have already pinned it to use bdb 5.3, and have been using this line to build:
```
BDB_LIBS="-ldb_cxx-5.3" BDB_CFLAGS="-I/usr/include/db5.3" ../configure --prefix=/usr --with-gui=qt5 --with-incompatible-bdb
```

However, from what I understand the recent gridcoin versions simply ignore this flags.
Is there a reason that we can't use a flag to use a system provided bdb package as long as it's the required version by gridcoin?

**Comment by jamescowens** [comment]
Yes. Because we want to control the version at this point. I will let @div72 make the call on whether he wants to put back bdb control flags.

**Comment by CyberTailor** [comment]
I fully agree with you, and I tried to avoid bundling libraries entirely in PR #2676. Although I faced some issues:
1. `univalue` is not packaged on most systems
2. Revdeps of `secp256k1` need different versions of the library

So vendoring them is justified.

**Comment by jamescowens** [comment]
On secp256k1, our code requires some slight alterations of the API IIRC, which also means we cannot just use the Bitcoin upstream...

**Comment by jamescowens** [comment]
I also want the version of bdb pinned to 5.3 if we are going to use system lib versions. which means compilation should fail unless the 5.3 versions are installed if system libs are used.

**Comment by div72** [comment]
> On secp256k1, our code requires some slight alterations of the API IIRC, which also means we cannot just use the Bitcoin upstream...

That just applies to the key parsing code that's independent of libsecp256k1, we do use the same libsecp256k1 as the upstream unaltered. Hell, I think our (pub)key.{cpp,h} is identical to upstream right now except for the Taproot functions.

**Comment by nethershaw** [comment]
Thank you all.
