### ISSUE TITLE
create official bootstrap link

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#298]
there is:
* http://download.gridcoin.us/download/downloadstake/signed/snapshot.zip

but not:
* http://download.gridcoin.us/download/downloadstake/signed/bootstrap.zip

**Comment by Peppernrino** [comment]
also, we need to start serving all content from the main site over SSL.

**Comment by Peppernrino** [comment]
for the record:
https://spideroak.com/share/N4YFAZLQOBSXEMDP/public/d%3A/%5BGridcoin/Gridcoin.Tools/Share/snapshot.zip
https://spideroak.com/share/N4YFAZLQOBSXEMDP/public/d%3A/%5BGridcoin/Gridcoin.Tools/Share/bootstrap.zip
are my shares, and NeuralMiner has been keeping the snapshots up to date on his google drive:
https://drive.google.com/drive/folders/0B_s1cP1ZtRpqMHFUOERzWk44aHM

takes some of the edge off the main site for downloading, but i can understand why somebody would not trust a package maintained by community members. :)

**Comment by barton2526** [comment]
This is a web issue that requires @gridcoin to fix.

**Comment by RoboticMind** [comment]
Hasn't this been done with https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip?

**Comment by Peppernrino** [comment]
that is the snapshot. this is for the bootstrap. apparently, the new block mechanism @denravonska has been working on builds faster and is actually more secure than the bootstrap (relies on network rather than file source), and we can arguably do away with bootstraps once that development drops. :smiley_cat: 

that said, i got @NeuralMiner to make a new one the other day, and there is a copy in both of our web shares.

**Comment by denravonska** [comment]
Do we still need this or are we satisfied with the Camilla sync speeds? There might still be rooms for improvements.

**Comment by jamescowens** [comment]
I think we can close this.
