### ISSUE TITLE
Numerous Tolerances allow staking up to 25% more than Fair

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#370]
In the block checking code there are lot of places where reward is checked with considerably high tolerance. This allows hacked wallet to stake more reward than is fair.
I haven't checked how exactly and how much can be staked this way, but I tried to add few cents to my reward and the blocks passed.

**Comment by denravonska** [comment]
Why do we have these tolerances though? Just for rounding errors?

**Comment by grctest** [comment]
Let's certainly get these sorted out!

**Comment by iFoggz** [comment]
Kinda seems like this is over time. possibly time differences. thou 25% seems like a high tolerance for average staker perhaps real high magnitude wallets need the extra buffer?

we have seen the "Researchers Reward Pays too much" here and there and wallets have gotten stuck on those blocks while other wallets have not. and usually it reorg's itself out or a restart can help.

above this allowance in connectblock there is an allowance of a time drift as sometimes ResearchSubsidy can be slightly smaller due to RA time span increasing. perhaps this is for time span decreasing giving a higher ResearchSubsidy. kinda seems like time is a factor.

**Comment by RoboticMind** [comment]
Has this since been fixed?

**Comment by denravonska** [comment]
No, there are some constants to allow for wiggle due to the old tally mechanisms. It should be a non issue now so the offending constants can possibly be removed. Very carefully and with a lot of testing, and it will possibly require a mandatory.

**Comment by tomasbrod** [comment]
This WILL require a mandatory, possibly not a hard-fork.
