### ISSUE TITLE
Broken menu strip and menu entries

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#391]
Since the new style, the menu strip and the menu entries are broken:
- the menu strip proportions are wrong
- the menu entries are not visible

Clicking on the "empty space" in the submenus works fine and triggers the corresponding menu action.

Affected platform: arm64
Version: 3.5.9.0-g
![grc_menu](https://user-images.githubusercontent.com/29569497/27328770-8be8a850-55b3-11e7-8fc1-76be195c8b3d.jpg)

**Comment by denravonska** [comment]
Strange, which dist is this on?

**Comment by ghost** [comment]
This is on Ubuntu 16.04, MATE desktop, Kernel version 3.14.79

EDIT:
interesting finding: I changed the display style from "native" to "light", and voilà... everything looks fine now o_O

**Comment by denravonska** [comment]
@Bierchen84 Those are stylesheets so maybe something is missing from Native.

**Comment by skcin** [comment]
hm, interesting. The "native" style uses a stylesheet file that is striped down to the minimum. So the look and feel is determined mostly by the desktop you are using. Since mate is gtk based and not qt based this might cause the issues. You could try to install qt compatibility packages. 

Not sure this is a bug we can solve on our end without destroying the idea of a native scheme. We could change the default scheme, though?

**Comment by ghost** [comment]
@skcin Ok, I understood, that the "native" style sheet is designed to use local system preferences (which could be wrong/missing in my case).
I think changing the default style sheet would be a feasible way to prevent this behavior. From my point of view, there is nothing wrong in doing so ;)
