### ISSUE TITLE
The magnitude for several projects is 0, again.

### ISSUE THREAD

**Issue by volatility1** [gridcoin-community/Gridcoin-Research#392]
The magnitude value for several projects (e.g. Amicable Numbers, Collatz Conjecture, World Community Grid) is 0.
![grc_wallet](https://user-images.githubusercontent.com/7209723/27342008-2fa3d930-55df-11e7-9056-f2a65b23a965.jpg)

edit:
![fireshot screen capture 017 - gridcoin projects status latest headlines wu status and more - www_gridcoinstats_eu_project](https://user-images.githubusercontent.com/7209723/27343038-0d073586-55e2-11e7-9789-eadc59ef8230.png)

**Comment by iFoggz** [comment]
yes we are aware of the bad superblock should be ok next block hopefully. still watching and investigating

**Comment by grctest** [comment]
Was this actually a bad superblock though, or is this a matter of the project beacons expiring after 6 months? https://github.com/gridcoin/Gridcoin-Research/issues/352

**Comment by 47an** [comment]
If it could be, but if it was project beacon running out of time it should end up as false now. 
All project in whitelist is =true

We are still waiting to new superblock and nerualhash look fine with 3 different hash with highest at 59%

"Command" : "neuralreport"
},
[
{
"Neural Hash" : "Popularity,Percent %",
"1a9f2bc000022a02f56b96314aec1688" : "25; 59.86%",
"3fde8605c98e94dfdef48979a62248b5" : "2; 5.91%",
"f6789f189c2fd26deb625139621d3651" : "14; 34.21%",
"Superblock Age" : 245010,
"Last Sync" : 938640.00000000,
"Next Sync" : 938670.00000000,
"Next Quorum" : 938670.00000000
}

Have followed NN and synced few times and popular hash change after each sync. Debug2 show QUORUMDATA to and now show popular hash to it.

few minutes later this hash it out not listed anymore. 1a9f2bc000022a02f56b96314aec1688

End up with list:
"Command" : "neuralreport"
},
[
{
"Neural Hash" : "Popularity,Percent %",
"3fde8605c98e94dfdef48979a62248b5" : "2; 16.33%",
"f6789f189c2fd26deb625139621d3651" : "12; 83.59%",
"Superblock Age" : 245397,
"Last Sync" : 938670.00000000,
"Next Sync" : 938700.00000000,
"Next Quorum" : 938680.00000000
}
]
]
Trying to figure out why it got lost/rejected with and does not get used. 67h since last superblock but no consensus? or any trigger?

gridcoin: could you have a look why wallet do not generate a new superblock?

**Comment by denravonska** [comment]
It seems like the boinc servers are fairly unreliable. Maybe they have always been like that but some of them seem to randomly stop responding to stat requests. Maybe that's what causing the many different hashes.

**Comment by ghost** [comment]
Just done a test where I deleted the contents of the NeuralNetwork folder and then manualy run the `execute syncdpor2` command. I did this test two times and after each time run the `execute myneauralhash` command to determine hash. 

The results are:

15:33 - f32921b352e7d3e580d91e2ead7eeb66 (24 Projects out of 25 synced. Rosetta failed) 2170 CPIDS
15:42 - 4a85241813349638f2c64ca110d7411c (24 Projects out of 25 synced. Rosetta failed)  2170 CPIDS

As you can see the hashes even after running the command straight after each other are different. I'm not 100% certain but I think it might have something to do with the way the VB.NET code filters the CPIDS using the nodes local time and the `expavg_time` in the user.xml.gz file.

```vb
'Dont bother writing timestamps older than 32 days since we base mag off of RAC
Dim lRowAgeInMins = GetRowAgeInMins(sTemp)
  If lRowAgeInMins < (60 * 24 * 32) Then
    oSW.WriteLine(sTemp)
End If
```
I'm also seeing a lot of file locking errors in the debug2.log when trying to store magnitudes which might have something to do with it.

```
Jun 24 2017 15:38, Attempt #0 While storing data row Projects,Project, PK: NeuralNetwork : The process cannot access the file 'C:\Users\windev\AppData\Roaming\gridcoinresearch\NeuralNetwork\project_projects_NeuralNetwork.dat' because it is being used by another process., Retrying.
Jun 24 2017 15:38, Attempt #0 While storing data row Projects,Project, PK: leiden classical : The process cannot access the file 'C:\Users\windev\AppData\Roaming\gridcoinresearch\NeuralNetwork\project_projects_leiden classical.dat' because it is being used by another process., Retrying.
Jun 24 2017 15:38, Attempt #0 While storing data row Projects,Project, PK: numberfields@home : The process cannot access the file 'C:\Users\windev\AppData\Roaming\gridcoinresearch\NeuralNetwork\project_projects_numberfields@home.dat' because it is being used by another process., Retrying.
```

**Comment by denravonska** [comment]
@3ullShark Interesting. Are the results sorted differently or is the timestamp included?

**Comment by 47an** [comment]
rosetta@hometeam.xml is 8 days old from my NN and they had maintenance , and this is would be an issue.
From Debug2 these attempt did not show as problem for this project at each sync. Making new full sync to look for any changes.

Meanwhile i see Rosetta did makeover to website and are online. stat surl show empty. https://boinc.bakerlab.org/rosetta/stats/
Mod responds: I'll look into this later today.

EDIT: stats xml are now back, time to try new sync.
EDIT2: URL to Whitelist might need change to http://boinc.bakerlab.org/rosetta/stats/
This it the url they hand out.

We need a way for handle superblock even if 1 project is out for maintenance, if rules are set to hold sb 14 days we might be able to wait. Even if so changes could be made to other stats and set ignore to any changes to project would be better then reject new sb.
