### ISSUE TITLE
Neural Network sync when trigger-block was skipped

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#393]
Hi there,

the NN syncing process is triggered every 30 blocks. My client just skipped the block at that the sync process would have been triggered because of lag or reorganisation or something like this.

I suggest adding a check whether the sync has been triggered, otherwise it should trigger it again to improve consensus finding.

Kind Regards,
Quez

**Comment by iFoggz** [comment]
note that not all nodes participate in the NN. only 25% of the nodes will on a given day roughly it seems.
if your not with the lowest 25% of md5 hash created by ur grc address plus "_" + dayoftheyear hashed then u wont participate and a NN sync will not occur every 30 blocks so that it doesn't stress the network or project servers,etc.

**Comment by Quezacoatl1** [comment]
Oh thanks @Foggyx420 ! Well if that was intended we do not need to "enhance" anything I suppose. @denravonska we can also close the issue?
