### ISSUE TITLE
No BOINC data directory on nodes...

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#425]
When starting a node, you get the "Error: Cannot find BOINC data dir"... because there isn't one. Can we eliminate checks for BOINC data for Investor wallets?

**Comment by iFoggz** [comment]
This is part of checking whether or not a user is a miner.  I mean maybe we could add another config file entry such as suppressboinc=true and we can just exit boinc.cpp from there on and resume functionality; much like it checks for boinc data dir in config file.  it could be placed before it in the code. just that's something @denravonska would have to approve on but it is doable if someone really wanted it. I cud even do the code for it but up to ravon if this should or should not be added.

EDIT:

thought of another thing is this could be useful for users who want to run more then one wallet for whatever reason. one could be an investor wallet yet all machines have boinc on it and instead of putting in a false path for boinc u could just suppressboinc and save that message from showing

**Comment by ghost** [comment]
I think a simple check for a CPID in the conf before logging that error might work.

**Comment by iFoggz** [comment]
that would if a user had there cpid in the config. a new user wouldn't have that in there. perhaps just a check for email in config which is required for boinc mining could be checked instead. if no email then no check for boinc.

**Comment by iFoggz** [comment]
I only have my windows wallet with PrimaryCPID which is required for NN stuf I believe. but Linux doesn't require it. Id think that check for email would be best way without adding arguments to config

**Comment by iFoggz** [comment]
another note the change would likely be in main.cpp not boinc.cpp itself as I think it would be a better choice there so there is no additional messages added to logs about not finding boinc folder,etc which are located there as well if file is not found and less code.

EDIT: have to look at code but I may have to just put it in boinc.cpp after all I don't want to write more code to help prevent interference of the code after so I can eliminate the message comes on screen at load. but the debug.log messages would remain which is fine.

**Comment by tomasbrod** [comment]
Preferably move the rest of boinc - related functions to boinc.cpp.
