### ISSUE TITLE
Remove all options but balance or mag+balance for polls

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#433]
Right now you can create a poll where the vote weight is one of the following:

- Magnitude
- Balance
- Magnitude & Balance
- CPID count
- Participant Count

Out of these the Magnitude and balance is the ones that actually make any sense given how easy the latter two are to exploit. However, there are very few, if any, reasons to pick just Magnitude or Balance over just Magnitude&Balance. Since we are wasting so much time discussing if a poll should be this or that I think we should remove all options and make all polls Magnitude & Balance.

**Comment by tomasbrod** [comment]
I don't agree.
Magnitude only polls should be used for decisions that will affect crunchers only.
Balance polls for investor interests.
The other two are useless due to Sybil attack vulnerability.
I don't like removing functionality (unless conflicting).
What about making it more general by allowing custom weight scaling (Wm and Wb in `w=Wb*b+Wm*m` weight formula)?

**Comment by denravonska** [comment]
The current system and the one you propose both add complexity and try to solve a problem that does not exist. Crunching power is just another distribution of balance so why complicate it?

I love to remove functionality that does not serve a purpose :)

**Comment by ghost** [comment]
I would remove the magnitude as well because we are all investors in the coin even if primarily crunching. 

There should be more incentive to hold onto the coin and using balance greatly simplifies things making it easy for people to understand. The more balance you hold or retain from crunching, the more invested you are in the coin and therefore should have the most voting weight. 

People who crunch and sell everything shouldn't be allowed to have the same weight no matter what the poll is for.

**Comment by denravonska** [comment]
@3ullShark You hit a very valid point on IRC: with mag all polls with new votes have to be invalidated on a bad superblock.

**Comment by ghost** [comment]
Also people like kikipope can exploit polls. I think mag should be removed.

**Comment by gridcoin** [comment]
I do see that mag votes done during a bad superblock should be invalidated (too bad our system does not have a good average consensus but thats some day in the future I guess), but BullShark how does kikipope exploit polls?  The new patch was supposed to fix that.

**Comment by ghost** [comment]
He exploits them because he's running a botnet. Apparently he has installed malware on peoples machines that runs BOINC.

**Comment by gridcoin** [comment]
We have a virus in one of the boinc projects?  This sounds terrifying, which one?

**Comment by tomasbrod** [comment]
I still think that removing it from the source is too drastic. Instead it should be removed from new create polls.

**Comment by tomasbrod** [comment]
The virus is not in project. It is somehow installed on victim pc, installs boinc and attaches to projects under attacker account.

**Comment by XaqFields** [comment]
The important thing with the bad SuperBlocks that we get a fix out (somehow) that eliminates or minimizes their impact on polls. Until then, I would suggest any poll with multiple answers within ~10% of each other should be declared invalid and run again, especially if there were votes cast on days we had a SB issue. 

As for removing all options we don't wish for people to use, I think it makes sense. We could choose to create a poll about it and formalize the rules first (IE: do people want to no longer have the option to create polls with Mag-only weight or are there certain polls where we want that option?) But ultimately I agree we should clean that up.

**Comment by NeuralMiner** [comment]
@gridcoin I sent you an email on 3/3 about the malware being used and a full break down of how it works. 
I can resend it to you if you like.

**Comment by NeuralMiner** [comment]
I don't agree with removing mag from the voting options. If the argument is that kikipope is exploiting voting with mag that isn't his, then he's also exploiting voting with GRC that isn't his. Also, removing it because of the recent issues with the SB is treating the symptom, not the cause.

I agree with @tomasbrod that mag only should exist for votes that affect crunchers, and balance for votes that affect investors.

@3ullShark, there's already an incentive to hold your GRC; 1.5% interest. If crunchers want to use the GRC they earn crunching to help cut the costs involved in BOINC, then they shouldn't be penalized for it. If anything, I would think it would help get more power behind our team; I know several people in IRC have mentioned selling their GRC to buy video card upgrades to in turn earn them more GRC.

What sets GRC apart from 99% of alts is DPoR; we're not just wasting energy churning out blocks. We're doing math, looking for cures; finding aliens. Pushing the importance more towards holding the coin, I think, begins to take away from that.

**Comment by skcin** [comment]
My opinion on this depends on what this voting mechanism should be used for. I don't think it is suitable for decentalized government of the Gridcoin project.  There is no minimum participation, it does not represent the blockchain consensus and the polls are not rejected by default.
It is a nice tool for surveys though. And for that usecase it could be interesting to have mag only votes.

In my opinion we need to create a new voting mechanism for binding decisions / decentralized government and should keep the current one for surveys like: which projects do you crunch? What color do you like best for the gridcoin logo?

Voting on foundation expenses or critical protocol changes should represent the blockchain consensus to prevent forks. A proposal is rejected until the majotity of the last 1000 blocks (or any other number of blocks) signaled a yes vote.

**Comment by fffffgggg54** [comment]
I think that a new type should be added, something along the lines of participation time, whether by beacon time or by oldest transfer.

**Comment by tomasbrod** [comment]
Good idea. @fredoguan

**Comment by iFoggz** [comment]
i still don't agree to removal of these options; rather better more defined uses for them (Maybe a poll type documentation should be created for making polls).

1) balance -> should be used for voting in case of where stake holders are required for a vote (health of network/Major decisions)
2) mag -> should be used for voting in case of where project votes are required (researchers should only vote on whitelist projects/should only vote on topics that affect researchers only)
3) mag + balance -> should be used for voting in case of where a vote is needed on a subject that affects both researchers and investors. (researchers get a boosted vote weight so this would essentially be a vote style where researchers out weighs investors weight for decision)
4) cpid -> should be used the same as a mag vote; except 1 vote is 1 vote and weight is not involved in the decision making it basically a single vote from each researchers decision
5) participant count -> should be used same as balance; except 1 vote is 1 vote and weight is not involved. 

I think we stray too much on options and don't have concrete documentation that defines the poll type and whether it is valid for vote or not.

**Comment by fffffgggg54** [comment]
Perhaps a guidlines for polls page in the wiki?

**Comment by jamescowens** [comment]
@cyrossignol For Fern...

**Comment by iFoggz** [comment]
Well back to this one I want change how I feel about this with regards to my mention in a previous comment on here. 

I think we can work towards reducing the types of polls. Only ones I see beneficial are balance, mag + balance for most part.

balance->  where as coin holders have a say based on what they have in wallet supporting the network. (issue with this is exchanges could potentially vote imo)

mag + balance -> is just like balance except using this to allow crunchers have more weighted say (thou i wonder if that the best imo)

mag -> for when it affect those who crunch but not the investors/balance holders

I think for cpid/participant count these should be removed and consolidated into a single vote system for that. where 1 vote is 1 vote. but with this comes some challenges as we will have to make sure that it is one vote from a wallet only. 

essentially imo:
the mag vote type covers the cpid vote type thou it is weighted and this doesnt even really prevent a investor from making a vote.

the participant count can be apart of a single vote system as well. 

just throwing some thoughts out there about this

**Comment by jamescowens** [comment]
closed by #1809.
