### ISSUE TITLE
too large value (X = 163 million) in field: "Stake Weight X; Searching for coins"

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#476]
the "_Stake Weight X; Searching for coins_" (last row: "Client Messages") text shows a probably too large stake weight:
* with X being constantly >100 million (e.g. max I have seen so far was 163 million)

my DPOR weight shows normal:
* so, not like this bug: #410
* perhaps related, though ?

version 3.5.9.8 from master branch with today's commit: 2262b07291aa30c491d77ab6c6ee5a7a46e55a04

**Comment by tomasbrod** [comment]
(cross post, because it applies)
In ~dev~ ~staging~ master branch, the stake weight is reported in two places on the overview screen. 

The "DPOR Weight:" as shown in the screenshot is calculated somewhere in gui code as balance+magnitude and **may not reflect real staking weight**.

Second is in "Client message:" is calculated in stake miner as sum of weights of all mature UTXOs and reflects the **real weight**. It is **not in coin** units.
For version **8** blocks 1 GRC equals to 80 of weight.

**Comment by tomasbrod** [comment]
For **version 7** blocks, 1 GRC equals to **800** of weight *in investor mode*. For researchers, the weight is boosted, quite complex, by magnitude.

**Comment by tomasbrod** [comment]
In private chat, we confirmed that the reported weight was right. I think this should be closed, @Erkan-Yilmaz .
