### ISSUE TITLE
Question marks in interface

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#48]
Lots of question marks in the interface. I've downloaded the client from Gridcoin's website and installed under Windows 10. Windows interface language is Ukrainian.
<img width="490" alt="bug" src="https://cloud.githubusercontent.com/assets/2746199/10878057/e4a0abea-8153-11e5-9ce0-5d851626c70c.png">

**Comment by orest1s** [comment]
Same here :( 
I run Windows 8.1 64-bit and language is English.
![qm_issue-grc_client](https://cloud.githubusercontent.com/assets/15845587/11163682/497797f4-8ae1-11e5-93d7-27a02ce3a1d4.PNG)

**Comment by orest1s** [comment]
SOLVED! Just in case you have the same problem, my working solution was to go to Control Panel/Region/Formats and change the Format to English(US). Then I reinstalled the app and everything is fine now.

**Comment by ghost** [comment]
@orest1s Thank you! Still doesn't work for other languages (Ukrainian and Russian) whatever format I choose. As a workaround, I keep Gridcoin interface language set to English and switch format to US as you suggested each time before starting Gridcoin.

**Comment by gridcoin** [comment]
Hi all-

This issue is caused because we have a bad translation file in 
/src/qt/locale/bitcoin_ru.ts.
It looks to me like this file was pulled in unicode and its stored in github in ascii.
Hence all the ??'s.

Note that the locale/bitcoin_de.ts file for Germany is working fine along with some other languages like French.
Fixed, will be in the next version.

**Comment by gratiscoin** [comment]
this is not fixed yet for greek
