### ISSUE TITLE
voting reminders, URL in polls

### ISSUE THREAD

**Issue by chri2** [gridcoin-community/Gridcoin-Research#56]
Two ideas to improve the voting experience for users:
- Provide information about the vote along with the vote (e.g. short text, url with md5 over the important part of content, ... - more ideas?)
- reminders for votes: 
  - gui: Show regular reminder about open votes (maybe only for votes on which were not voted yet)
  - headless: Provide same interface as for e.g. wallet notify: call a skript to generate a reminder if configuried by the user

If I understood correctly votes become part of the blockchain. If so they become historical documents that can't be proved. We shouldn't miss to put the content and subject of votes or at least a information to validate the external information into the poll on the blockchain to make our documents complete. As of know we just save a minimal subject along with the voting itself.

To get more users to vote it would be nice to remind them (as long as they don't decide not wanting to be reminded or do not setup a reminder script for their wallet).

**Comment by gridcoin** [comment]
Yes the poll and the votes do become part of the blockchain.  Did you mean to say "can be proved"?  (I assume thats what you meant).  Currently a user can vote on headless, but receives no warning that a new active poll exists (on windows you see the latest active poll in the overview).  A nice reminder page would be nice.  We do have an rpc command on headless to list the active polls (execute listpolls).  We are probably splitting hairs on headless anyway because the user will need to execute a command to see the active polls... So technically that means the only wishlist item here is a windows GUI to remind the user to vote, correct?

**Comment by gridcoin** [comment]
Recircle back to this after the ease-of-use features are integrated in for new users.
