### ISSUE TITLE
No payouts since 8/05 - Not forked, BOINC running fine

### ISSUE THREAD

**Issue by Penumbra69** [gridcoin-community/Gridcoin-Research#587]
I've been running the wallet and boinc religiously since I setup shop again on 6/25.  
I was getting regular payouts until 8/06 - when all transactions that I didn't manually trigger stopped.

I've checked that I'm not on a fork, and some guys in the #gridcoin channel in freenode went over some details and it looked like I'm fine, but there's "Potentially a NN issue".

How do I find that out, and fix my payouts?
CPID: 49f5d6ae6795dc13de42bc56af591a42

I don't mind that I don't stake with my current low balance, but I would like the POR to work at least.

**Comment by iFoggz** [comment]
your information looks fine. Also you have a 1.6K balance which I can see. The PoS v8 kernel is in effect. It uses your weight with no magnitude included anymore due to security.

Currently you need 20K balance to stake every day. So Id' say your probably gonna stake every 15 to 20 days. and your PoR payments are on top of a staked block. 

Its actually a good idea since the new kernel if you can use coin control and select all your inputs and send it to a address in your wallet from the receive tab . This consolidates all your coins into a single UTXO. When v7 kernel was running the more UTXO you had the higher chance to stake however now its not the case. With v8 it's about the weight of your UTXO. so if you have the 1.6K in a single UTXO you will stake every 15-20 days and get ur full reward at that point.

**Comment by Penumbra69** [comment]
Ok, so I'm, not in some "Dead Zone" - or feeling some effects of what could be a hacking attempt.

You're saying to just "send" myself all of my coins, so they consolidate?  Seems odd, but OK!

**Comment by Penumbra69** [comment]
Doing so has lowered my stake weight to 0 - I am no longer staking.  (12+ confirmations on the tx).
I'll let it run tonight and see what happens tomorrow, but sending myself all my own coins didn't seem to be  "good" thing?

**Comment by tomasbrod** [comment]
@Foggyx420 Merging UTXOs is not necessary. Smallest stake-able UTXO is 0.0125 GRC. The stake weight of each output adds together.
By sending all your coins together to yourself, @Penumbra69, you their maturity status (and also lost their pending interest...). Now you must wait 16 hours for them to mature, and your weight to return.
Another con of having all coins in one output is that this will happen again once you want to send them somewhere.

**Comment by iFoggz** [comment]
ahh! my bad i was under the impression you didn't add the outputs all together. didn't seem to stake with my separate ones so i made them into one on my wallet and I managed to get a stake. will try separate. Also when staking the Stk appeared different with separate ones versus a single one. I'll review more

**Comment by Penumbra69** [comment]
I realized after I posted that I had to wait for them to mature 16h again.  I didn't realize I would lose their interest.  I don't think it was that much, but dang .. Thanks guys - I'll watch for another month and see.
