### ISSUE TITLE
Enhancement request: In GUI, button to open gridcoinresearch.conf with system editor

### ISSUE THREAD

**Issue by Bouowmx** [gridcoin-community/Gridcoin-Research#598]
In GUI, a button to open a commonly used file, with the system editor. Something like in Advanced menu, "Open gridcoinresearch.conf", and the file is opened as if the user double-clicked file in the system explorer.

**Comment by pwnorbitals** [comment]
Or even better, a configuration editor which would do the insertions in gridcoinresearch.conf (thus avoiding syntax errors), like a custom key/value editor. Looks like a lot of work, and may not prove very useful in the long run though... Because just double-clicking the file works too, you know
Another option is to make an "open config folder" button so that the user can double-click himself

**Comment by tomasbrod** [comment]
+1 for open data directory

For config editing, ideally should be stored in DB, with config as override.

**Comment by tomasbrod** [comment]
There must be a warning that editing config is only supported when wallet is closed.

**Comment by tomasbrod** [comment]
Text editors would ignore the write lock on non windows systems.
