### ISSUE TITLE
feature: show who created a poll

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#611]
please show to each poll who/which address created it

**Comment by tomasbrod** [comment]
If there were projects enabled, I would add this to Poll overhaul project.

**Comment by grctest** [comment]
Impossible to implement this, I could create a new address with an investor CPID and you'll never know it was me. You could show the CPID, but this is just going to serve personally attacking the poll creators.

**Comment by grctest** [comment]
Why though? So users who disagree with a poll can harass the poll creator?

**Comment by Erkan-Yilmaz** [comment]
> Why though? So users who disagree with a poll can harass the poll creator?

this feature request came to birth like this:
* @denravonska asked startail actually to make that feature into the block explorer
* and startail said it will come, iirc

I guess we can send your comment now also to startail then ?

**Comment by Erkan-Yilmaz** [comment]
...and before that, actually someone claimed something about me, assuming I made a few polls
* so in that case it would have helped me to prove that it was not me, or that even that claim came to existence

**Comment by grctest** [comment]
It's fairly trivial to figure out who created a poll by taking the 'created time', navigating to the blocks around that time, looking at the transactions and seeing the poll tx. Startail can do what he wants with the block explorer, I believe this would be used to harass the poll creator if included within the client.

Rather than providing ammunition, we should work towards eliminating the toxic practice of witch-hunts and harassment against poll creators.

All you'd need to do is say "I didn't create the poll, stop this witch-hunt as it's an unhealthy community practice.".
