### ISSUE TITLE
every POR-reward i get disappears despite showing confirmations

### ISSUE THREAD

**Issue by mr-snipes** [gridcoin-community/Gridcoin-Research#681]
I got 3 por-rewards so far. They are visible in the gridcoin-client and i can see that the confirmations are rising. While this POR-reward is pending, my wallet goes offline and back online after several minutes a lot. 
Once it reached more than 100 transactions, my grc-client is not showing the reward anymore. 
I have run the client-upgrade to make sure i am on the latest grc-client (v3.6.2.0-unk) - however this keeps happening and already ate 15 grc. 
What can i do ?

**Comment by iFoggz** [comment]
when u pull it up in transaction description (double clicking the por in transactions tab what does it say for Status:

**Comment by mr-snipes** [comment]
I see no por-transactions in my transaction-panel. The last transaction i see is the beacon-transaction 28 days ago.

**Comment by pawelzajdel** [comment]
Maybe an unrelated issue. I got 1 POR reward about a week ago, which also disappeared but I assumed it was due to the last fork. However, now I am not so sure. After running the client upgrade (a week or so ago) I am still on v3.6.1.0-unk, which is also the current version on https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi
What's strange, running "Upgrade client" hangs on "Waiting for Gridcoin Wallet to Exit". The same for grcupgrade.bat.

**Comment by iFoggz** [comment]
its really easy to stake on a fork because not many clients are staking on that fork. and it becomes orphaned and disappears. thats strange that in client upgrade hangs. are you running as administrator? i can't remember if it needs to be in order for upgrade to work.

**Comment by pawelzajdel** [comment]
I've read about forking issues that's why I was not worried
I'm worried now as I am still on the old version
Yes, I have admin rights and even tried to run both upgrades "as administrator". Still hangs on "Waiting ... to exit"
Can someone switch the gridcoin.us Win installer version from 3.6.1.0 to the latest?

**Comment by mr-snipes** [comment]
Now back to my original issue: what can i do to troubleshoot/fix this thing ?

**Comment by pawelzajdel** [comment]
mr-snipes, what does https://www.gridcoinstats.eu say about your cpid?

**Comment by mr-snipes** [comment]
my ID is 87ea9070ad53177b876a7d0607fc91a3 - in the grc client is says status boinc mining, shows my magnitude and the project correctly. On gridcoinstats it shows nothing.

**Comment by mr-snipes** [comment]
Here are two screnshots: https://unsee.cc/sumozida/   https://unsee.cc/rezinapu/

**Comment by tomasbrod** [comment]
What @mr-snipes is describing looks exactly like staking on a fork. Your wallet somewhat got on a fork. And as there is lower difficulty on forks, It forged (staked) several blocks. Also showing "offline" status when on fork is common. Then the situation turned and your wallet reorganized and jumped on the right chain, leaving the staked blocks behind. They can't be transferred. You can compare your block hash against one of the explorers or your friends to see if you are on a fork.

**Comment by mr-snipes** [comment]
Why did you make a thumbs down ? How can i fix being on a fork now ? Have the client redownload the chain ? How can i see it the next time without manual interaction ? I just want to run boinc and the client, i dont want to make my own research if my client got misconfigured. I would like the client to tell me if it is having an issue. And other users surely also want that. Imagine one day people start 'real' mining and loose big POR-payments because of this error. 

Your thumbs down is making me kinda angry. What do you expect ? That someone who does some boinc-mining is knowing all this and has an outlook-entry to check if a fork happened and the chain is wrong ? Whisky Tango Foxtrott, you have no idea how usuability and user-frienndlyness looks like!

**Comment by pawelzajdel** [comment]
Is you nick humpydiddle? There seem to be several cpids connected to it. The cpid you have sent (87ea90...) has 1 staked block but has large mag . Is ce5c32c54e986594e6388045a7ca33f9 also your ID? It has minimal mag but has all GRC. Also if you are "Boinc mining" you should see DPOR weight rather then Coin weight. Right?

**Comment by mr-snipes** [comment]
My accountname is ka0t. I am part of team gridcoin and participate in rosetta@home. My ID is 254924

**Comment by tomasbrod** [comment]
When I put thumbs down I  don't like the comment itself eg: repeating requests, links to adult/spam sites, unreadable, duplicate issues. On the two links you posted, there are only advertisements. Also notice, that I put few thumbs up to appreciate good issue reporting.

Now back to the issue we know that the client is not very stable. Similar issues: #424 #402 #525 #587 #566. I already told you that it is normal for Reward transactions to disappear after fork. But the reward is not lost, instead it is "added back" to your owed rewards. And the system is designed so that next time you stake, you should get that reward back, plus any reward that you accrued since the event.

There was a bug, which caused this disappeared rewards to not add back under some conditions. I fixed the bug (#578), but it was found that under even less probable conditions it can happen again. Also the wallet is *designed* to recover from forks, but you can guess, there are bugs.

**Comment by mr-snipes** [comment]
The site unsee.cc is designed to give you the option to add pictures with a expiry-time. I set it to 1 hour. I dont want my screenshots to be on github forever. 
I have never got any stake despite the ammount of grc i have. The beacon was sent a month ago. When i read current posts from others, i should have staked by now.  My stake shows 0 all time. Somehow when i lookup my ID, it is not found on different sites where it should be found. I was on another team from my old Boinc-time and i changed to Team Gridcoin more than a month ago. 
When i use my CPID in these calculators the CPID is not found. 
example : http://gridcoin.co/?cpid=87ea9070ad53177b876a7d0607fc91a3
What can i do to get my client back on track ? reinstall ? rebuild block chain ?

**Comment by tomasbrod** [comment]
Your cpid was found [on gridcoinstats.eu](https://gridcoinstats.eu/cpid/87ea9070ad53177b876a7d0607fc91a3) (it will not show your balance, do not worry, your wallet is always correct). Your beacon was advertised 9.9.2017. The time to stake varies widely and depends on your balance and wallet up-time. We can check a few things, but otherwise you just have to wait.
1) Fork check
Open the [the block explorer](https://gridcoinstats.eu/block), click on the last block. It will show both block number and hash. Now go to wallet and open debug console, use command `getblockhash the_block_number`. The output should be equal to block hash shown on the website. If you get error, wait 10 minutes, it can take a while for your wallet to pick up latest block.
2) Beacon and CPID check
Open debug console, type `execute beaconstatus`, it should say SUCCESS. **Do not post private keys here.** Also by the explorer, you are attached only to Rosetta@home project. This is OK, but If you are running also other projects, please check if your CPID matches.

**Comment by pawelzajdel** [comment]
@mr-snipes My beacon was also advertised on 9/9. I am solo staking for a month and it looks like without the newbie bonus I will stake in 3-5 years. My [stats](https://gridcoinstats.eu/cpid/ad683300321a3cd88d3a3f7a3498b86c). I also got a false stake during the last fork.
@tomasbrod Is it true that newbie bonus is gone in 3.6.2.0? Not even for a single block?

**Comment by mr-snipes** [comment]
@tomasbrod  i checked both, the blockhash is same. The beacon-check i have done earlier, the beacon was sent. Is there another reason for me seeing POR-data which i finally do not get ? 

From getstakinginfo i have the following output:

"InterestPending" : 4.69800299,
"difficulty" : {
"proof-of-work" : 8.23948943,
"proof-of-stake" : 2.71209588,

"pow_reward" : 30.00000000,
"errors" : "",
"pooledtx" : 0,
"stakeinterest" : 0.01500000,
"testnet" : false,
"PopularNeuralHash" : "",
"NeuralPopularity" : -1.00000000,
"MyNeuralHash" : "d5deb84cf2bc748355c5036a17c14117",
"CPID" : "87ea9070ad53177b876a7d0607fc91a3",
"RSAWeight" : 100000,
"Magnitude Unit" : 0.25000000,
"BoincRewardPending" : 28.96706018,
"MiningProject" : "rosetta@home",
"MiningInfo 1" : "Boinc Mining",
"MiningInfo 2" : "Poll: Whitelist_Poll:_ODLK",

So somehow i have some boinc rewards which are in the system but not arriving- if i am interpreting this output correctly.

**Comment by tomasbrod** [comment]
Correct, the "BoincRewardPending" is tracked by the network and will be paid out when you stake a block. There is no longer a newbie stake weight bonus.
You can read [this steemit article](https://steemit.com/gridcoin/@tomasbrod/editing-dpor-payments-current-situation-and-proposals) to find out what efforts are being spent to solve this situation.

**Comment by pawelzajdel** [comment]
@tomasbrod OK I read it. Thanks. I think, if GRC still wants to stay around BOINC, it must take better care of POR and also solo miners. The idea of POR payments in superblock seems to me as the best option. From my POR mag I would expect 1 block in 1-3 months (50-150 GRC). It's acceptable for me. 
Now, based on coins, in 1-3 years, which is not appealing. 
I cannot BOINC in pool.

**Comment by tomasbrod** [comment]
Trust me, all of the devs want to improve the current situation. Waiting months for reward payment is just ridiculous.

**Comment by mr-snipes** [comment]
@tomasbrod  Thank you for the link. I can't say i entirely understand it all. Is the issue with seeing a POR appear, my client going offline and my POR disappearing a bug in which logs are helpful ? Most people told me my client must run on an old fork and we ruled that out. While i get that staking can take longer now, i am not sure if my por appearing and then disappearing is intended.

**Comment by tomasbrod** [comment]
Is it appearing and disappearing NOW? You were on a fork, now we verified that you are not.

**Comment by iFoggz** [comment]
if u find your on a fork usually a restart of wallet will correct it after a few minutes of being loaded

**Comment by mr-snipes** [comment]
update: i left my pc on over night and forgot to turn on boinc again. So just the gridcoin-wallet was running. Now i have a POR-payment which also shows up under transactions.

**Comment by mr-snipes** [comment]
The weird thing is that i did not really do something different which would explain that i was on a fork before and not on a fork afterwards. The client ran the same way as before. I did several restarts and update-attempts before and it kept failing.

**Comment by mr-snipes** [comment]
It just happened again - i got a "payment" incoming and then it disappeared. I cannot do the same validation again, the website is currently showing 
The page is currently replaying the blockchain and should be in sync soon. Currently 4176 blocks behind.

**Comment by tomasbrod** [comment]
It disappeared.b because there were not enough confirmations. Also there was a fork, as you may have guessed from the giant red warning in explorer.

**Comment by iFoggz** [comment]
since we haven't had a bunch of forks in last 14 days this issue hasn't continued on in context. likely cause is a por on fork so this should be closed. its possible we could update the information displayed regarding what it says in description dialog to add more information about forking and its affect on a POR.

**Comment by tomasbrod** [comment]
Still todo for me to check more code-paths where this can occur.

**Comment by barton2526** [comment]
Can this issue be closed?

**Comment by tomasbrod** [comment]
The reorgnew changeset should help this situation. Reward is calculated OK after forking according to my limited tests.
