### ISSUE TITLE
Distributed Computing Projects Not Based Around BOINC are not Included in Gridcoin

### ISSUE THREAD

**Issue by fffffgggg54** [gridcoin-community/Gridcoin-Research#782]
Projects such as Folding@Home and GIMPS have not been implemented into Gridcoin. They are distributed computing projects as well and should also get recognition through Gridcoin. They both have teams and could potentially be implemented in the same way that BOINC is.

**Comment by grctest** [comment]
We would need to establish a proof of account ownership and statistics tracking/scraping, if you can provide suggestions for both we can potentially integrate them.

**Comment by tomasbrod** [comment]
DWP would support, or at lease be extensible enough to support projects on other platforms.

**Comment by RoboticMind** [comment]
Folding@home has an API
http://folding.stanford.edu/stats/api

**Comment by fffffgggg54** [comment]
We could potentially use a method similar to that of CureCoin or Foldingcoin for tracking. A new team could be created. Becuase I have personally not used Folding@Home, it would help to know from any folders out there if there is a way to identify yourself with a secret statistic that no one other than yourself would know. I suggest something like CureCoin, as the use is similar to that of the existing Gridcoin - joining a team and downloading a client.

**Comment by RoboticMind** [comment]
We could contact the developers of those projects to see if they would be interested in helping us figure out a way to use them with Gridcoin.

**Comment by fffffgggg54** [comment]
@RoboticMind I agree. The support of these projects would help with development and improve Gridcoin as a whole.

**Comment by RoboticMind** [comment]
We could also use usernames with public keys in them so you could prove that you own a username by signing something with the corresponding private key. Maybe a styling system like this                       

[custom name] [End Of custom name string] [Public Key] or just [Public Key]

**Comment by jring-o** [comment]
i am working on a project that i hope will help facilitate more synergy between open DCN communities like curecoin and foldingcoin.  january 4th = )

**Comment by PrestackI** [comment]
Does anyone know what issues they were having when trying to use the BOINC wrapper?

**Comment by tomasbrod** [comment]
For tracking remote system (FoldingAH) user [Brod-GAA](https://github.com/gridcoin-community/Gridcoin-Tasks/issues/170) could be effectively extended. The more effective CM-SAA would require, however small, but nevertheless a modification to the remote systems' server software. Both can be used even without teams.

**Comment by PrestackI** [comment]
@tomasbrod How do you add this to the wallet to start receiving credits for it?

**Comment by tomasbrod** [comment]
@PrestackI To this date, these are only theoretical.

**Comment by fffffgggg54** [comment]
@PrestackI Folding@home used to have a wrapper for BOINC but then removed it. Has anyone tried contacting F@H?

**Comment by smoe** [comment]
I suggest to have different reward systems for different projects.  And not all projects shall be allowed to tap into Gridcoin's self-devaluation. For instance for individual projects there could be a faucet that is triggered by compute work but the project maintainers need to keep it filled - by themselves or external donations, i.e. from gridcoins they buy on the market.

**Comment by RoboticMind** [comment]
There's an opinion poll now from @cyrossignol  on if Gridcoin should look into whitelisting Folding@home. This poll is non-binding, so its more to gauge community interest. Link to the poll discussion is [here](https://www.reddit.com/r/gridcoin/comments/jvephz/opinion_poll_should_gridcoin_reward_foldinghome/)

**Comment by springfielddatarecovery** [comment]
Just wanted to add to the discussion here, I know I am a bit late to the party! One is that Dreamlab is another project worth collaborating with, though I agree that F@H would probably be the most effort vs reward one to focus on because of their huge userbase. Once we have the code added to "bring in" non-BOINC projects, adding another one such a dreamlab probably wouldn't be much extra work.

As the Gridcoin infrastructure is built up, there's no reason we need to be limited to strictly computational projects. For example, there are a number of other citizen science projects that ask people to record audio of outdoor environments, snap photos or wildlife to train AI, record audio of them coughing for covid research, track light pollution, submit geolocation data, etc. So long as these projects have a leaderboard system such as BOINC/RAC, they could be integrated and incentivized as well. The problem would be that giving them equal share of magnitude compared to traditional computational projects would probably vastly over-incentivize them. But a separate, less total coin magnitude pool could be made for such a purpose with the magnitude being split across such projects. 

F@H being integrated into Gridcoin would be a very exciting achievement and an excellent example of scientific collaboration!

**Comment by jamescowens** [comment]
Finally this one is being closed! :)
