### ISSUE TITLE
Gridcoin update enhancement and Installer versioning.

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Research#819]
I'm proposing that we start suffixing the GridcoinInstaller.msi with the relevant version numbers upon release. Example: GridcoinInstaller-3.7.0.0.msi  and Linux/mac equivalents.

This would require a minor change to the in-wallet updater, Which I would propose creating a version.txt on the gridcoin.us website or where ever you find is best, pointing the in wallet updater to it so it can fetch the latest version without issue.

And if automated builds and deploys every become a thing(I highly recommend we get something set up), one can use a script to automatically push the .msi and update said version file.

Additionally I'd like for all types of installers be it windows, Linux or mac be added to the asset section of the GitHub releases. Would provide at lease one place that's quickly updated and always available to grab updates from.

**Comment by iFoggz** [comment]
the in client upgrader grabs files from azure cloud. it doesn't use msi installer for upgrading.

When development is merged and autotools becomes the main compiler the msi versioning will likely be changed along with a few others i'm sure. also note if we change the version for msi it will affect previous installs meaning from that point it would have to be a fresh install after old version is completely installed since msi updates the files needed.

Thanks for the suggestions regarding placing all installers in the release section i'm sure something similar could and will be done.

Steps for release msi is master is updated. master is compiled and msi is then created and the msi file changes are then PR back to master. the msi changes are after the fact to keep the commit at release compiled wallet matching the linux, etc commit for the release version (the tag is where we compile from)

**Comment by jamescowens** [comment]
This is fixed in Denise now that we are going to use the make deploy feature...

It produces for Windows a file of the form gridcoin-x,y.z-win<32 or 64>-setup.exe
