### ISSUE TITLE
Remove Upgrade Client option until it's rewritten

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#834]
Since the upgrader cannot handle the new file structure people keep getting into trouble when using it. I propose removing it for 3.7.4.0 and add it back in once the upgrader is rewritten to use github or some other source.

See #824.

**Comment by iFoggz** [comment]
this about done

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
now thats a great idea , remove it till fixed although maybe back at  v3.5.8.1 when it stopped working vs at v3.7.4.0 but then fix it right use the github file server root dir organized for download links from the reop's file space and src structure and either raw located in that dir an msi , .exe , .tar.gz or  , zip etc etc and a working .dmg ( not qt4 backwards compatible so wont run on osx 10.10 or older since only qt5 is avail at 10.10 and i offer ssh access to dev a fix ) all in one centralized location or multi geographical location based ip mirrors and not a free M$ azure account especially when many of us have racks or racked servers or rented vps's and have offered to host any of the community needs even donated vps's and dedi's ... especially since this 3rd post on the same issue in 2 weeks.

also have you guys ever heard of  https://sourceforge.net ? 
Someone has https://sourceforge.net/p/gpu/news/2017/07/gridcoin-investigation-launched/ but Gridcoin should be mirrored on sourceforge and done up similar to any other opensource project such as https://sourceforge.net/projects/kb1oiq-andysham/files/?source=directory for example for structure and archive. That also adds the gridcoinresearch gui and gridcoinresearchd client to the sorceforge repo just by adding the sorceforge .rpm .pkg .rpm ( ie: http://www.somethingsomewhere.net/2012/05/04/add-sourceforge-as-repository-on-cent-os/ )

Here is how , https://www.software.ac.uk/how-create-and-manage-sourceforge-projects ..





but we do have a dev whom lies or likes to lie... " last -n 10 ravon " showed me that.

**Comment by denravonska** [comment]
Sigh, now what?

Qt 5.7 supports Lion and up while older 5.x releases might even go further back. If you have all the time on your hands then please feel free to release and maintain support for Lion builds.

I see no reason to do Sourceforge over github. That would be like going back from git to Subversion.

**Comment by tomasbrod** [comment]
Sourceforge is basically dead (like myspace), but yeah, could be used as a mirror. I put my upvote @grcjamezz , because your post is not offensive for once.

**Comment by tomasbrod** [comment]
I agree. Delete the updater and fill the missing functionality with Alert message.

**Comment by denravonska** [comment]
This has been fixed.
