### ISSUE TITLE
Error Message on Start

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#85]
Every time I attempt to start the client I receive an error message about 'src/kernel.cp'. I have tried disabling antivirus software and 'upgraded' the software. I have tried repairing and uninstalling and reinstalling the client and nothing seems to work.
![screenshot 125](https://cloud.githubusercontent.com/assets/7443442/14872299/e2b5a16e-0cb8-11e6-95ce-1b4c4cc5634a.png)
Hitting any option-abort, retry, or ignore-results in no change in result.

**Comment by grctest** [comment]
I believe this is caused by a corrupt blockchain.

Navigate to your appdata folder : %APPDATA%/roaming/gridcoinresearch/ backup wallet.dat walletbackup and gridcoinresearch.conf files.

Check that the gridcoinresearch.conf file isn't corrupt, if it is clean it up and launch the client again.

If the conf file wasn't at fault, delete all the files in the gridcoinresearch appdata folder (after having taken backups of the above mentioned files). Once deleted, reintroduce the backed up files to the folder and launch the client again.
