### ISSUE TITLE
Research earning cap of 12750GRC

### ISSUE THREAD

**Issue by Rytiss** [gridcoin-community/Gridcoin-Research#913]
Apparently there is a 12750GRC research earning cap per block. Due to the recent forking issue we could not stake in time and lost several thousand GRC because of the cap:

* https://www.gridcoinstats.eu/block/1153082/d13d57dc49d3f724d4a6c644f11314e4f9d009931cf0c4a55393ef8568df3939
* https://www.gridcoinstats.eu/block/1153081/a026b8ec033f41bdd0f890e9b25fc10cfe6dd915353a5680adea340500486949

Another user also had this issue: https://www.gridcoinstats.eu/block/1149379/d14abd6b087fc0a38fb70b2fabec2d736d956d6d1fe45f1b3814051148b00a9b

Why is there such a limit when the research earnings are supposed to be kept for 6 months? If this limit stays, why aren't the remaining coins paid out in another future block?

**Comment by 47an** [comment]
The cap  for research saving account is 12750 GRC + interest and it would be good to lower this to make nodes active, no matter if there is a fork or normal state in network. 6 month is the time to track the beacon active to CPID.
If push PoS it would be a good to also make PoR more active.

**Comment by tomasbrod** [comment]
I agree that voiding unpaid research rewards is unfair for you and other users. This "feature" is (one of two) reasons why grcpool is split to three hot wallets.
Solution is in the design phase.

**Comment by Rytiss** [comment]
We've been bit by this again (and more than once).

I started looking into the code to find out where the issue is, and I believe the cap is set at https://github.com/gridcoin-community/Gridcoin-Research/blob/0ce12a74e1aed60c1f0c44c8c6c6fe2fbf4a28fe/src/main.cpp#L2138

I am open to submitting a patch, but I would like to figure out the reason for the limit, and some guidelines on getting the patch included into the next mandatory (I guess leisure would not cut it here, as the limits must pass consensus).

**Comment by iFoggz** [comment]
This was to prevent abuse especially in many cases

examples: 
where a botnet of boinc clients were crunching for a malicious user
where users of an application were unknowingly contributing to magnitude of a cpid on gridcoin (also helping earn gridcoins for them and not getting there share if they would want it)
where other cases of abuse may occur if possible.

I agree this does affect some users and it can be "unfair" but this also covers some loop holes

**Comment by iFoggz** [comment]
another note if u kept a higher balance you could potentially stake more often instead of transferring the balance out so soon

**Comment by tomasbrod** [comment]
@Rytiss Yes, you can submit a patch, we can test it and if it works, will be released in mandatory.

**Comment by tomasbrod** [comment]
Note that it is not as simple. There are parts of the code that would break if the limit is exceeded. We plan to remove it when the other parts are fixed.

**Comment by iFoggz** [comment]
@denravonska could u set this to a milestone for v11 or something so its on our list

**Comment by jamescowens** [comment]
This is related to the magnitude limit of 32k and also the research reward magnitude cap of 20k.

The new scraper/NN supports the removal of the 32k cap, but the binary packing format of the SB needs to be changed. The 20k limit can be removed but has security implications.

**Comment by barton2526** [comment]
There is a risk here that paying out a massive RR reward swings the magnitude multiplier so much it messes up research rewards for the entire network for a short period.  I would vote to keep the current cap in place.  Why should someone be claiming more than 45.5% of our daily POR emission in a single block anyway?

**Comment by jamescowens** [comment]
There is a strong argument that it should be actually lowered to prevent abuse.

**Comment by jamescowens** [comment]
@cyrossignol and I will comment more on this in Slack, but we are finalizing the implementation of the superblock window approach to research rewards. With this we are going to be streamlining a number of the specialized rules related to this issue:

1. The 500 GRC "newbie" award limit is being dropped. The superblock window accrual calculation is very accurate and eliminates the lifetime research reward distortion in the three point average that leads to excessive rewards being awarded if this newbie limit did not exist. Newbie accruals will begin at the superblock where they achieve positive magnitude after beacon registration and will be measured SB by SB until staking...

2. We are retaining the 32767 magnitude limit, a) to control the storage requirements for the magnitudes, and b) to prevent possible abuse in a extraordinarily high corner case.

3. We are changing the floating filter based magnitude unit calculation with a fixed 0.25 magnitude unit ratio. The filter was necessary in part due to the inaccurate average accrual calculations for people with highly variable magnitude trends, and is not longer necessary with the SB window accrual and reward approach.

4. We are dropping the extra 20k mag cap in favor of just the 32k limit, but we are retaining the research reward limit PER STAKE, but at a different value. The value we have selected is 16384 (16k) limit per stake, which represents two days worth of accrual at the mag limit. 16384 / (32767 * 0.25) = 2 days. The purpose of this limit is to prevent the possible corner case abuse of low balance but extremely high magnitude staking. In particular it is the expectation of pools that they maintain balances high enough to be able to stake on a very regular basis to ensure that pool members are paid out fairly. Maintaining a corner case limit of 16384 GRC awarded per stake encourages pool operators to maintain a balance high enough to stake every 2 days and ensures the pool itself is participating adequately in ensuring network security.

**Comment by dblanch256** [comment]
Very impressive, James.

**Comment by jamescowens** [comment]
Closed. See comments in #1657.
