### ISSUE TITLE
Note from a fairly noob to the Devs :)

### ISSUE THREAD

**Issue by HopSling** [gridcoin-community/Gridcoin-Research#937]
Just a few observations, as I'm still fairly a noob, but I noticed that the 5 nodes Bunny-Shadow-Silver-Sonic-Tails have differing versions such as Bunny has v3.7.6.0-g9e60762f2 and the Sonic has v3.7.7.0-gfeb5aa77a. Have noticed Sonic stays green synced whereas Bunny seems to be a bit of a forker. Should they all be same versions ??? Also I'm trying like heck to get back on Sonic but every time I go to advance, in wallet, and click on download blocks to get back on sync ....instead of downloading blocks I get kicked-out/exited and have to restart wallet all over again. Thinkin I'm gonna just keep wallet off until all is fixed. BTW I have been reasearching/reading/learning a lot on Gridcoin and one MAJOR thing, being a fairly new noob, is the COMPLICATION to set up (outdated help files) and understanding Gridcoin terms when yall are helping noobs answer questions....most of us are click-through auto build it for us type technically inclined....and when yall start telling a noob to open this file-click this/that-then enter this/that....its like HUH ???...lol....its like trying to understand a quantum mechanics instruction with a High School GED ability. Just Sayin :) But thanks to ALL DEVS ...Marco Thom etc: I can only imagine the hair pulling and mind stressing it takes to hold the Grid together... Huge Thank You !!!

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Hello and thank you for your interest in Gridcoin , although I am not a " dev " I am more than happy to help  you out. First off , the in client download blocks is being changed as the file host/ip location is being moved , its a known issue if you look threw here in #issues so you can download http://download.gridcoin.us/download/downloadstake/signed/snapshot.zip and you will need to goto your C:\Users\Username\AppData\Roaming\GridcoinResearch and unzip it and replaced all files when it asks. This is a new current blockchain snapshot from the 2nd when 3.7.7.0 came out and fixes the last fork. Either that or sync from 0 as the client starts to download the blocks from startup. The reason it exits is a background command is initialized to close gridcoinresearchd.exe and download the blocks since it cannot be done while running. Same with upgrade client , also broken and being fixed. 
Per the website ran by startail since there is no real offical gridcoin website its an open source project: https://www.gridcoin.us - https://gridcoinstats.eu - https://gridcoin.science - https://gridcoin.network -  https://gridcoin.io/ - http://gridcoin.ch/ are all Gridcoin websites that are just as official as the other and you and I can put one up and it would qualify as just as official as the other. Now with that said startail has taken the time to setup gridcoinstats.eu and depending on package or compile from source you get the -unk or -gfeb5aa77a version ending and although I do not run the site nor know the code , I am working on an eggdrop irc bot that does similar features and I would have to say unless a version is hard required due to a change the commands have not changed to quarry the gridcoinresearchd getinfo command in the background on the node the site uses the check..  The current versions are after the v9 block hardfork and although personally myself I keep my nodes 100% updated I would think its not necessary until commands change that cause site errors... Being someones personal donation of time and effort sometimes can get put on the back burner especially if not needed like the whole if its not broke don't fix it moto. Now if startail can please fix the News section as its not updated from steemit since 8/17/2017. Now that is an example as to needing an update , steemit changed their search code string and broke gridcoinstats.eu's news page. It would be nice to get updates from @current @trending and @gridcoin all in general for gridcoin.
I hope that helps , and also thank you Startail for the wonderful site you provide to the gridcoin community gridcoinstats.eu gets more use than google here<3.

**Comment by Dr-Infinity** [comment]
Greetings gridcoiners,

Received block 2556d18b74ad53a131ae5f9484cc09515ae1a50a0f80054e82d1b72b023341e8 causes endless error messages that have resulted in my wallet failing to sync since Feb 7, 2018.

Running 3.7.7.0 on Mac OS X 10.13.4 build (17E150g).
---------------------------------------------------------
Full error message from debug log:
"02/14/18 00:43:06  Received block 2556d18b74ad53a131ae5f9484cc09515ae1a50a0f80054e82d1b72b023341e8; AcceptBlock: Proof Of Stake V8 9
02/14/18 00:43:06 ERROR: CheckProofOfResearch: Researchers Reward Pays too much : claimed 48.720000 vs calculated 0.000000 for CPID 1104d7e73072ad70bdce14b7ea434e14
02/14/18 00:43:06 ERROR: WARNING: AcceptBlock(): check proof-of-research failed for block 2556d18b74ad53a131ae5f9484cc09515ae1a50a0f80054e82d1b72b023341e8, nonce 0

02/14/18 00:43:06 ERROR: ProcessBlock() : AcceptBlock FAILED"
---------------------------------------------------------
Downloading most recent snapshot now and will install and try again.

Thanks to all for the creation of Gridcoin. I know it is a labor of love for the Devs. 

Have been Boincing since 1999 and it's nice to have a way to encourage more people to join the scientific computing community.

If the snapshot doesn't fix the issue, I'll report back.
c2

**Comment by Dr-Infinity** [comment]
Decided I'd report back if the snapshot worked.  It did.

Did a little more searching and found the attached information on Reddit.

Made the suggested additions to gridcoin research.conf and all is well again.

Took about half an hour. 

[xaminmo comments on Is it worth mining?.pdf](https://github.com/gridcoin/Gridcoin-Research/files/1722434/xaminmo.comments.on.Is.it.worth.mining.pdf)

**Comment by tomasbrod** [comment]
- not a right place for discussion of @startailcoon's block explorer. What versions he's running is up to him. Actually running different versions is better (one issue is not going to wipe them all).
- do not 'download blocks' more than once a week
- #903 
- It is Tom and Jerry, not Thom and Jerry.

**Comment by RoboticMind** [comment]
Can we close this @denravonska
