### ISSUE TITLE
Voting Issue when CPID is null

### ISSUE THREAD

**Issue by startailcoon** [gridcoin-community/Gridcoin-Research#947]
Due to some issue with the wallet the field `CPID` can be null, which should never happen. CPID is either `INVESTOR` or a valid CPID.

Neural Miner noticed that the poll https://gridcoinstats.eu/poll/project_whitelist_and_greylist_process_proposal had a different count compared to what the wallet said.

### Counting Double Votes from Wallet Addresses
By extracting the wallets votes with ` gridcoinresearchd execute votedetails project_whitelist_and_greylist_process_proposal` I could find the discrepancy with three addresses that was submitted with a null CPID and later a valid INVESTOR or CPID, counting them again.

![image](https://user-images.githubusercontent.com/12114550/36392006-6a91651e-15a9-11e8-91c5-ac6707406084.png)

### Gridcoinstats Issue with null CPID (solved)
The explorer had an issue due to this as well. As the page expires a vote coming from the same address, using the new TX vote, it also looks for the same CPID not using another address for voting. Due to it not expecting a null CPID value it expired all votes for these addresses. **This has now been solved.**

**Comment by iFoggz** [comment]
your right this shouldnt happen but we also got to remember that u can vote more then once and then its the sum of the votes / number of votes to determine the voting weight in the end

**Comment by startailcoon** [comment]
I guess that makes good sense and is something I need to change if so.

When I started the page I don't think this was the case and that only the last vote counted.

I assume this was changed along the way to deal with recasting a vote when a large change in balance or mag happens

**Comment by iFoggz** [comment]
i stand corrected the devide is if u have more then one answer as to not make multiple answers equal more then one vote. perhaps if a pervious vote exists it should overwrite the existing one

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
" When voting multiple options in single transaction, the weight is split.  " than wouldn't that make multiple answer option votes such as opinion polls " what is your favorite white listed project " such type votes for example where its multiple answer results that splitting the weight throws off the votes results when a user only votes for 1 it gives full weight but if selected 2 projects only half the voters weight goes to the each selected vote answer result they selected vs their full vote weight on each answer thus throwing off the results because only half weights being counted on multiple?

ie: we will use the vote weight of 1 and say 3 people vote the 1rst person votes on 1 so their full weight of 1 is on that answer , than number 2 and 3 vote on 2 answers so than .5 goes to each of their results. Wouldn't that then show 1 answer as 1 and or if 1 of those voters selected that same answer 1.5 and the others .5? That seems like different poll types need options to select how the results are formulated as different polls have different value to the community and multiple choice results are butchered into partial weight results when the poll should still be giving full vote weight to each answer in order to get a correct result?

**Comment by tomasbrod** [comment]
More flexible vote system is called for. Create a gridcoin-task on it, if not already.

**Comment by jamescowens** [comment]
Closed by #1809.
