### ISSUE TITLE
vote costs more than what the UI tells

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#96]
I voted in a poll today, but it cost me more (1) than what the QT wallet tells in the upper right corner (2).
OK: The beacon back then cost as much as the UI tells.

Was there a change in the fee structure?

using gridcoin 3.5.6.7

(1) 0.00021 GRC
(2) "Beacons and Votes cost .00011"

**Comment by gridcoin** [comment]
The actual base fee is still .00011 which is really just a token burn amount to ensure the tx is forwarded through the network.  The total fee in your case must have included "network fees" - those are given to the miner who mines the block your vote is in.  The way it works, is the closer the block size gets to 1 mb, GRC charges higher and higher network fees in order to forward the tx.  This is something standard inherited from BTC.  It prevents block spamming abuse.  Another words your vote just happened to go in a block that was growing large.

A UI appears to warn you of total network fees when you send a tx manually, but it is not visible when voting.

Rob

**Comment by Erkan-Yilmaz** [comment]
thx for the explanation
