### ISSUE TITLE
Look into ways to reduce the storage footprint of the blockchain

### ISSUE THREAD

**Issue by fffffgggg54** [gridcoin-community/Gridcoin-Research#987]
While blockchain size is not currently an issue, the example set by Bitcoin shows that the blockchain could potentially be too big, requiring online wallets and increasing centralization. This could be looked into as research. Possible solutions include finding a way to reduce the number of blocks stored on an individual computer (ex. one computer stores relevant blocks stores enough blocks to fill a set threshold which the computer is set to hold, possibly in groups of <i>n</i> blocks, which is preassigned) or the blocks are reduced in size in some way (is it possible).
This is just an idea to look into and I have no idea regarding the feasibility or reliability of the result.

**Comment by tomasbrod** [comment]
1. Store old blocks only on some of nodes, as you said. For example, DHT based routing or ready made IPFS.

2. Optimize block serialization. Linear. I estimate that at most 30% of storage could be saved. Does not work on already created blocks.

3. Get rid of old blocks completely with something like Safebox technology of Pascalcoin. I do not really like the way they did it, but the idea is Good.

**Comment by RoboticMind** [comment]
I think here is one of the places data can be saved:

In the hashboinc data for voting under the MV tag:
the CPID is listed twice, once in the outer part, and once under the "PROVABLEMAGNITUDE"
Magnitude is listed twice, once in the outer part, and once under the "PROVABLEMAGNITUDE"
Balance is listed twice, once in the outer part, and once under the "PROVABLEBALANCE" listed as "TOTALVOTEDBALANCE"

**Comment by tomasbrod** [comment]
The voting needs to be completely redone.

**Comment by RoboticMind** [comment]
I am aware, but that is something that can be done **Now** to save some space by not wasting it on repetition until we get our better voting system.

**Comment by denravonska** [comment]
Something we can do today is to prune the block index of obsolete values.

- Store CPID as uint128_t instead of string (saves 16 bytes/block on research blocks, loses 8 bytes on investor blocks)
- Remove GRC address (saves 1 byte per new block, 35 bytes per old block)
- Remove reserved string (saves 1 byte per block)
- Use flags instead of storing the two separate flag variables `nIsSuperBlock` and `nIsContract` (saves 2+2 bytes from block 364500)

These can safely be removed since the block index is not a part of the hash. It does not save a whole lot though.

Edit: Integer serializing might not actually include the serialized size in bytes in which the savings are a bit smaller.

**Comment by tomasbrod** [comment]
Block index takes 600-700MiB, history file (blockchain) takes 1.4GiB. Block index optimizations will affect all of the blockindex, blockchain optimizations would affect only new blocks.

**Comment by jamescowens** [comment]
The new changes in Fern partially address this. More to be done.

**Comment by jamescowens** [comment]
I think we have met the criteria to close this. We have eliminated the hashBOINC field and also cleaned up in memory structures in PR's that are going into Hilda.
